module.exports = {
    transform: {
        '^.+\\.[jt]sx?$': '<rootDir>/jest-preprocess.js',
    },
    collectCoverage: false,
    collectCoverageFrom: [
        '**/*.{js,jsx,ts,tsx}',
        '!**/node_modules/**',
        '!**/public/**',
        '!**/static/**',
        '!**/.cache/**',
    ],
    coverageReporters: ['lcov'],
    coverageDirectory: './coverage/',
    moduleNameMapper: {
        '.+\\.svg$': '<rootDir>/__mocks__/svg-mock.js',
        '(gatsby-background-image|gbimage-bridge)': '<rootDir>/__mocks__/file-mock.js',
        'p-min-delay': '<rootDir>/__mocks__/min-delay-mock.js',
        '.+\\.(css|styl|less|sass|scss)$': `identity-obj-proxy`,
        '.+\\.(jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$': `<rootDir>/__mocks__/file-mock.js`,
        '^common/(.*)$': '<rootDir>/src/common/$1',
        '^components/(.*)$': '<rootDir>/src/components/$1',
        '^images/(.*)$': '<rootDir>/src/images/$1',
        '^lotties/(.*)$': '<rootDir>/src/lotties/$1',
        '^pages/(.*)$': '<rootDir>/src/pages/$1',
        '^features/(.*)$': '<rootDir>/src/features/$1',
        '^store/(.*)$': '<rootDir>/src/store/$1',
        '^templates': '<rootDir>/src/templates/$1',
        '^themes/(.*)$': '<rootDir>/src/themes/$1',
        '^translations/(.*)$': '<rootDir>/src/translations/$1',
        '^types/(.*)$': '<rootDir>/src/types/$1',
    },
    testPathIgnorePatterns: [`node_modules`, `\\.cache`, `<rootDir>.*/public`],
    transformIgnorePatterns: [`node_modules/(?!(gatsby|gatsby-script|gatsby-link)/)`],
    globals: {
        __PATH_PREFIX__: ``,
    },
    testEnvironment: 'jsdom',
    testEnvironmentOptions: {
        url: `http://localhost`,
    },
    setupFiles: [`<rootDir>/loadershim.js`],
    setupFilesAfterEnv: ['<rootDir>/setup-test-env.js'],
    clearMocks: true,
}
