import { job_types } from '../_job_types/_job_types'
import { cyberjaya, dubai, malta } from '../_locations/_locations'

export const back_end_positions = [
    {
        title: 'Database Administrator',
        id: '43130a72-bcd8-4927-8465-9458d43f7a12',
        keywords: ['Database Administrator'],
        location: cyberjaya.name,
        type: [job_types.full_time],
        team: 'back-end',
        description: [
            'You will plan, install, and maintain database systems to ensure the security, integrity and seamless flow of information for our high-traffic online trading platform. ',
        ],
        responsibilities: [
            'Plan, install, and configure world-class database systems that meet business objectives and the needs of end users.',
            'Plan and carry out the upgrade and migration of databases.',
            'Develop, implement, and test database backup and recovery plans.',
            'Manage database and data security by controlling access to data through authentication, authorisation, and auditing.',
            'Perform tests to ensure database performance and security, as well as data integrity.',
            'Document and administer database policies, procedures, and standards.',
            'Troubleshoot and debug problems in existing database systems, and find new ways to improve their speed, functionality, and scalability.',
        ],
        qualifications: [
            'Experience as a DBA, with a focus on database setup, security, replication, performance tuning, and disaster recovery',
            'SQL queries and optimisation',
            'Excellent troubleshooting skills',
            'Experience with database testing tools such as pgTAP',
            'Knowledge of Linux system administration, preferably including configuration and automation tools such as Chef as well as shell scripting',
        ],
        preferences: [
            'Experience with PostgreSQL and/or SQL Server preferred',
            'Experience with OLAP and MDX would be an advantage\n',
        ],
    },
    {
        title: 'Senior Back-end Developer',
        id: '72a07983-844e-471b-aeee-920dcf0d8103',
        keywords: ['Senior Back-end Developer'],
        location: cyberjaya.name,
        type: [job_types.full_time],
        team: 'back-end',
        description: [
            'You are a seasoned leader who can inspire your team and bolster the databases, scripting, and IT architecture of our company. You take pride in mentoring the junior members of your team and involving them in facing and overcoming new challenges, which you see as an opportunity to gain knowledge and experience. With your advanced object-oriented programming skills, you are eager to take on heavy responsibilities that go above and beyond the regular back-end workload of testing and improving the performance, speed, stability, and security of the company’s website and applications. \n',
        ],
        responsibilities: [
            'Design and launch large, complex back-end projects autonomously.',
            'Communicate with other teams to clearly identify the requirements, goals, and road map of joint projects.',
            'Undertake massive architecture challenges to reach high availability and scalability aims.',
            'Build, maintain, and optimise the technology that powers our servers, applications, and databases.',
            'Define the priority of the Back-end team’s tasks according to the company’s direction.',
            'Take the initiative to learn and work with the new technologies that are often introduced to the arsenal of our engineering teams.',
            'Collaborate with front-end developers and other teams to develop high-quality web and mobile apps.',
            'Lead your team in writing, reviewing, and documenting code to support and improve the functionality of our digital products.',
            'Detect and fix complex bugs that might result in high-risk issues during development and deployment.',
            'Elevate our data storage design to achieve greater speed, efficiency, and scalability.',
            'Supervise and engage in all aspects of the product life cycle.',
        ],
        qualifications: [
            'Expertise in any programming language, preferably Perl, Python, PHP, C/C++, Go, or Ruby, and a willingness to become highly proficient with Perl',
            'Vast experience with relational database design, and/or open-source RDBMS systems such as MySQL and PostgreSQL',
            'Extensive knowledge of information security and data protection',
            'Proficiency in Linux system administration',
            'Familiarity with Perl DBI, Moose, PSGI/Plack, NGINX, JavaScript, Redis, and Git',
            'Experience working with microservices and scalable systems',
            'Expert-level ability to produce high-quality, self-documenting code by using test-driven development (TDD) techniques',
            'Extensive experience in Linux and other open-source platforms',
        ],
    },
    {
        title: 'Database Administrator',
        id: 'a3bc0300-9dfb-4327-8eac-84cd6e31414a',
        keywords: ['Database Administrator'],
        location: dubai.name,
        type: [job_types.full_time],
        team: 'back-end',
        description: [
            'You will plan, install, and maintain database systems to ensure the security, integrity and seamless flow of information for our high-traffic online trading platform. \n',
        ],
        responsibilities: [
            'Plan, install, and configure world-class database systems that meet business objectives and the needs of end users.',
            'Plan and carry out the upgrade and migration of databases.',
            'Develop, implement, and test database backup and recovery plans.',
            'Manage database and data security by controlling access to data through authentication, authorisation, and auditing.',
            'Perform tests to ensure database performance and security, as well as data integrity.',
            'Document and administer database policies, procedures, and standards.',
            'Troubleshoot and debug problems in existing database systems, and find new ways to improve their speed, functionality, and scalability.',
        ],
        qualifications: [
            'Experience as a DBA, with a focus on database setup, security, replication, performance tuning, disaster recovery, and SQL queries and optimisation',
            'Excellent troubleshooting skills',
            'Experience with database testing tools such as pgtap',
            'Knowledge of Linux system administration, preferably including configuration and automation tools such as Chef as well as shell scripting',
            'Experience with PostgreSQL and/or SQL Server preferred',
        ],
        preferences: ['Experience with OLAP and MDX would be an advantage'],
    },
    {
        title: 'Back-end Developer',
        id: '27afa7da-e5e9-4c00-b146-a3569f7901f5',
        keywords: ['Back-end Developer'],
        location: malta.name,
        type: [job_types.full_time],
        team: 'back-end',
        description: [
            'You will be involved in troubleshooting and improving our back-end applications and processes. You will help create a more efficient process and work closely with other team members to ensure seamless user experience for our clients.\n',
        ],
        responsibilities: [
            'Develop and maintain world-class web applications.',
            'Build, maintain, and optimise the technology that powers our servers, applications, and databases.',
            'Collaborate with front-end developers and other teams to develop an effective architecture to support the deployment of new products and features.',
            'Troubleshoot and debug problems in applications during development and deployment.',
            'Optimize applications for speed, efficiency and scalability.',
            'Participate in all aspects of the product life cycle.',
        ],
        qualifications: [
            'Expertise in any programming language, preferably Perl, Python, PHP, C/C++, Go, or Ruby, and a willingness to become highly proficient with Perl.',
            'Extensive knowledge of information security and data protection.',
            'Expertise in Linux system administration.',

            'Extensive experience with relational database design, and/or open-source RDBMS systems such as MySQL and PostgreSQL.',
            'Familiarity with Perl DBI, Moose, PSGI/Plack, NGINX, JavaScript, Redis, and Git.',
            'Experience working with microservices and scalable systems.',
            'Ability to produce high-quality, self-documenting code by using test-driven development (TDD) techniques.',
            'Extensive experience in Linux and other open-source platforms.',
        ],
    },
    {
        title: 'PostgreSQL Database Programmer and Administrator',
        id: 'd7ebb3c9-8e84-4b2c-9171-34cead27eb57',
        keywords: ['PostgreSQL Database Programmer and Administrator'],
        location: malta.name,
        type: [job_types.full_time],
        team: 'back-end',
        description: [
            'You will plan, install, and maintain database systems to ensure the security, integrity, and seamless flow of information for our high-traffic online trading platform. \n',
        ],
        responsibilities: [
            'Plan, install, and configure world-class database systems that meet business objectives and the needs of end-users.',
            'Assist Back-end developers in writing production-ready SQL code.',
            'Plan and carry out the upgrade and migration of databases.',
            'Develop, implement, and test database backup and recovery plans.',
            'Manage database and data security by controlling access to data through authentication, authorisation, and auditing.',
            'Perform tests to ensure database performance and security, as well as data integrity.',
            'Document and administer database policies, procedures, and standards.',
            'Plan and execute data extraction for efficient loading in our data warehouse, and ensure extracted data is useful and properly formatted.',
            'Troubleshoot and debug problems in existing database systems, and find new ways to improve their speed, functionality, and scalability.\n',
        ],
        qualifications: [
            'Experience as a Postgres DBA, with advanced hands-on knowledge of database setup, security, replication, performance tuning, disaster recovery, SQL, and stored procedures',
            'Experience with database testing tools such as pgTAP',
            'Experience with data extraction and reporting for data warehouse/cube',

            'Knowledge of Linux system administration, including configuration and automation tools such as Chef as well as Shell scripting is preferred',
        ],
        preferences: [
            'Knowledge of Perl and other scripting languages is a plus',
            'Experience with Multidimensional Expressions (MDX) is an advantage',
        ],
    },
]
