import { TMarketData } from './_types'

export const synthetic_index_mock_data: TMarketData[] = [
    {
        allow_forward_starting: 1,
        delay_amount: 0,
        display_name: 'Bear Market Index',
        exchange_is_open: 1,
        exchange_name: 'RANDOM',
        intraday_interval_minutes: 5,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.0001,
        quoted_currency_symbol: '',
        spot: 1017.2712,
        spot_age: '0',
        spot_time: '1664274662',
        submarket: 'random_daily',
        submarket_display_name: 'Daily Reset Indices',
        symbol: 'RDBEAR',
        symbol_type: 'stockindex',
        spot_percentage_change: -0.061,
    },
    {
        allow_forward_starting: 0,
        delay_amount: 0,
        display_name: 'Boom 500 Index',
        exchange_is_open: 1,
        exchange_name: 'RANDOM',
        intraday_interval_minutes: 5,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.001,
        quoted_currency_symbol: '',
        spot: 4201.671,
        spot_age: '0',
        spot_time: '1664274662',
        submarket: 'crash_index',
        submarket_display_name: 'Crash/Boom Indices',
        symbol: 'BOOM500',
        symbol_type: '',
        spot_percentage_change: 0.086,
    },
    {
        allow_forward_starting: 0,
        delay_amount: 0,
        display_name: 'Boom 1000 Index',
        exchange_is_open: 1,
        exchange_name: 'RANDOM',
        intraday_interval_minutes: 5,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.001,
        quoted_currency_symbol: '',
        spot: 12477.77,
        spot_age: '0',
        spot_time: '1664274662',
        submarket: 'crash_index',
        submarket_display_name: 'Crash/Boom Indices',
        symbol: 'BOOM1000',
        symbol_type: '',
        spot_percentage_change: -0.636,
    },
    {
        allow_forward_starting: 1,
        delay_amount: 0,
        display_name: 'Bull Market Index',
        exchange_is_open: 1,
        exchange_name: 'RANDOM',
        intraday_interval_minutes: 5,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.0001,
        quoted_currency_symbol: '',
        spot: 1008.2176,
        spot_age: '0',
        spot_time: '1664274662',
        submarket: 'random_daily',
        submarket_display_name: 'Daily Reset Indices',
        symbol: 'RDBULL',
        symbol_type: 'stockindex',
        spot_percentage_change: 0.123,
    },
    {
        allow_forward_starting: 0,
        delay_amount: 0,
        display_name: 'Crash 500 Index',
        exchange_is_open: 1,
        exchange_name: 'RANDOM',
        intraday_interval_minutes: 5,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.001,
        quoted_currency_symbol: '',
        spot: 7042.734,
        spot_age: '0',
        spot_time: '1664274662',
        submarket: 'crash_index',
        submarket_display_name: 'Crash/Boom Indices',
        symbol: 'CRASH500',
        symbol_type: '',
        spot_percentage_change: 0.304,
    },
    {
        allow_forward_starting: 0,
        delay_amount: 0,
        display_name: 'Crash 1000 Index',
        exchange_is_open: 1,
        exchange_name: 'RANDOM',
        intraday_interval_minutes: 5,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.001,
        quoted_currency_symbol: '',
        spot: 6766.234,
        spot_age: '0',
        spot_time: '1664274662',
        submarket: 'crash_index',
        submarket_display_name: 'Crash/Boom Indices',
        symbol: 'CRASH1000',
        symbol_type: '',
        spot_percentage_change: 0.333,
    },
    {
        allow_forward_starting: 1,
        delay_amount: 0,
        display_name: 'Jump 10 Index',
        exchange_is_open: 1,
        exchange_name: 'RANDOM',
        intraday_interval_minutes: 5,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.01,
        quoted_currency_symbol: '',
        spot: 91611.33,
        spot_age: '0',
        spot_time: '1664274662',
        submarket: 'jump_index',
        submarket_display_name: 'Jump Indices',
        symbol: 'JD10',
        symbol_type: 'stockindex',
        spot_percentage_change: 0.081,
    },
    {
        allow_forward_starting: 1,
        delay_amount: 0,
        display_name: 'Jump 25 Index',
        exchange_is_open: 1,
        exchange_name: 'RANDOM',
        intraday_interval_minutes: 5,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.01,
        quoted_currency_symbol: '',
        spot: 94996.41,
        spot_age: '0',
        spot_time: '1664274662',
        submarket: 'jump_index',
        submarket_display_name: 'Jump Indices',
        symbol: 'JD25',
        symbol_type: 'stockindex',
        spot_percentage_change: 0,
    },
    {
        allow_forward_starting: 1,
        delay_amount: 0,
        display_name: 'Jump 50 Index',
        exchange_is_open: 1,
        exchange_name: 'RANDOM',
        intraday_interval_minutes: 5,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.01,
        quoted_currency_symbol: '',
        spot: 20158.06,
        spot_age: '0',
        spot_time: '1664274662',
        submarket: 'jump_index',
        submarket_display_name: 'Jump Indices',
        symbol: 'JD50',
        symbol_type: 'stockindex',
        spot_percentage_change: 0.25,
    },
    {
        allow_forward_starting: 1,
        delay_amount: 0,
        display_name: 'Jump 75 Index',
        exchange_is_open: 1,
        exchange_name: 'RANDOM',
        intraday_interval_minutes: 5,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.01,
        quoted_currency_symbol: '',
        spot: 13714.05,
        spot_age: '0',
        spot_time: '1664274662',
        submarket: 'jump_index',
        submarket_display_name: 'Jump Indices',
        symbol: 'JD75',
        symbol_type: 'stockindex',
        spot_percentage_change: 0.192,
    },
    {
        allow_forward_starting: 1,
        delay_amount: 0,
        display_name: 'Jump 100 Index',
        exchange_is_open: 1,
        exchange_name: 'RANDOM',
        intraday_interval_minutes: 5,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.01,
        quoted_currency_symbol: '',
        spot: 9376.54,
        spot_age: '0',
        spot_time: '1664274662',
        submarket: 'jump_index',
        submarket_display_name: 'Jump Indices',
        symbol: 'JD100',
        symbol_type: 'stockindex',
        spot_percentage_change: -0.049,
    },
    {
        allow_forward_starting: 0,
        delay_amount: 0,
        display_name: 'Step Index',
        exchange_is_open: 1,
        exchange_name: 'RANDOM',
        intraday_interval_minutes: 5,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.1,
        quoted_currency_symbol: '',
        spot: 8582.5,
        spot_age: '0',
        spot_time: '1664274662',
        submarket: 'step_index',
        submarket_display_name: 'Step Indices',
        symbol: 'stpRNG',
        symbol_type: '',
        spot_percentage_change: 0.034,
    },
    {
        allow_forward_starting: 1,
        delay_amount: 0,
        display_name: 'Volatility 10 (1s) Index',
        exchange_is_open: 1,
        exchange_name: 'RANDOM',
        intraday_interval_minutes: 5,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.01,
        quoted_currency_symbol: '',
        spot: 8559.55,
        spot_age: '0',
        spot_time: '1664274662',
        submarket: 'random_index',
        submarket_display_name: 'Continuous Indices',
        symbol: '1HZ10V',
        symbol_type: 'stockindex',
        spot_percentage_change: -0.033,
    },
    {
        allow_forward_starting: 1,
        delay_amount: 0,
        display_name: 'Volatility 10 Index',
        exchange_is_open: 1,
        exchange_name: 'RANDOM',
        intraday_interval_minutes: 5,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.001,
        quoted_currency_symbol: '',
        spot: 6544.292,
        spot_age: '0',
        spot_time: '1664274662',
        submarket: 'random_index',
        submarket_display_name: 'Continuous Indices',
        symbol: 'R_10',
        symbol_type: 'stockindex',
        spot_percentage_change: 0.067,
    },
    {
        allow_forward_starting: 1,
        delay_amount: 0,
        display_name: 'Volatility 25 (1s) Index',
        exchange_is_open: 1,
        exchange_name: 'RANDOM',
        intraday_interval_minutes: 5,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.01,
        quoted_currency_symbol: '',
        spot: 364573.05,
        spot_age: '0',
        spot_time: '1664274662',
        submarket: 'random_index',
        submarket_display_name: 'Continuous Indices',
        symbol: '1HZ25V',
        symbol_type: 'stockindex',
        spot_percentage_change: -0.231,
    },
    {
        allow_forward_starting: 1,
        delay_amount: 0,
        display_name: 'Volatility 25 Index',
        exchange_is_open: 1,
        exchange_name: 'RANDOM',
        intraday_interval_minutes: 5,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.001,
        quoted_currency_symbol: '',
        spot: 1776.927,
        spot_age: '0',
        spot_time: '1664274662',
        submarket: 'random_index',
        submarket_display_name: 'Continuous Indices',
        symbol: 'R_25',
        symbol_type: 'stockindex',
        spot_percentage_change: 0.125,
    },
    {
        allow_forward_starting: 1,
        delay_amount: 0,
        display_name: 'Volatility 50 (1s) Index',
        exchange_is_open: 1,
        exchange_name: 'RANDOM',
        intraday_interval_minutes: 5,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.01,
        quoted_currency_symbol: '',
        spot: 547866.73,
        spot_age: '0',
        spot_time: '1664274662',
        submarket: 'random_index',
        submarket_display_name: 'Continuous Indices',
        symbol: '1HZ50V',
        symbol_type: 'stockindex',
        spot_percentage_change: 0.08,
    },
    {
        allow_forward_starting: 1,
        delay_amount: 0,
        display_name: 'Volatility 50 Index',
        exchange_is_open: 1,
        exchange_name: 'RANDOM',
        intraday_interval_minutes: 5,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.0001,
        quoted_currency_symbol: '',
        spot: 230.5573,
        spot_age: '0',
        spot_time: '1664274662',
        submarket: 'random_index',
        submarket_display_name: 'Continuous Indices',
        symbol: 'R_50',
        symbol_type: 'stockindex',
        spot_percentage_change: -0.043,
    },
    {
        allow_forward_starting: 1,
        delay_amount: 0,
        display_name: 'Volatility 75 (1s) Index',
        exchange_is_open: 1,
        exchange_name: 'RANDOM',
        intraday_interval_minutes: 5,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.01,
        quoted_currency_symbol: '',
        spot: 10838.96,
        spot_age: '0',
        spot_time: '1664274662',
        submarket: 'random_index',
        submarket_display_name: 'Continuous Indices',
        symbol: '1HZ75V',
        symbol_type: 'stockindex',
        spot_percentage_change: 0.125,
    },
    {
        allow_forward_starting: 1,
        delay_amount: 0,
        display_name: 'Volatility 75 Index',
        exchange_is_open: 1,
        exchange_name: 'RANDOM',
        intraday_interval_minutes: 5,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.0001,
        quoted_currency_symbol: '',
        spot: 499490.7929,
        spot_age: '0',
        spot_time: '1664274662',
        submarket: 'random_index',
        submarket_display_name: 'Continuous Indices',
        symbol: 'R_75',
        symbol_type: 'stockindex',
        spot_percentage_change: 0.097,
    },
    {
        allow_forward_starting: 1,
        delay_amount: 0,
        display_name: 'Volatility 100 (1s) Index',
        exchange_is_open: 1,
        exchange_name: 'RANDOM',
        intraday_interval_minutes: 5,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.01,
        quoted_currency_symbol: '',
        spot: 1265.89,
        spot_age: '0',
        spot_time: '1664274662',
        submarket: 'random_index',
        submarket_display_name: 'Continuous Indices',
        symbol: '1HZ100V',
        symbol_type: 'stockindex',
        spot_percentage_change: 0.037,
    },
    {
        allow_forward_starting: 1,
        delay_amount: 0,
        display_name: 'Volatility 100 Index',
        exchange_is_open: 1,
        exchange_name: 'RANDOM',
        intraday_interval_minutes: 5,
        is_trading_suspended: 0,
        market: 'synthetic_index',
        market_display_name: 'Synthetic Indices',
        pip: 0.01,
        quoted_currency_symbol: '',
        spot: 24682.66,
        spot_age: '0',
        spot_time: '1664274662',
        submarket: 'random_index',
        submarket_display_name: 'Continuous Indices',
        symbol: 'R_100',
        symbol_type: 'stockindex',
        spot_percentage_change: 0.133,
    },
]
