import { ArticlesDataType } from './_data-types'

const affiliate_programme_data: ArticlesDataType = {
    section: 'General',
    category: '_t_Affiliate programme_t_',
    articles: [
        {
            question: '_t_How do I sign up as an affiliate?_t_',
            category: 'Affiliate programme',
            sub_category: '_t_Partners_t_',
            label: 'affiliate-sign-up',
            answer: [
                {
                    translation_text:
                        "_t_Complete <0>this form</0>, and we'll get in touch with you in a couple of days.<br/>You'll need a real Deriv trading account, too. If you don't have one, sign up <1>here</1>._t_",
                    translation_components: [
                        { key: 0, type: 'link', to: 'https://login.deriv.com/signup.php?lang=0' },
                        { key: 1, type: 'link', to: '/signup/' },
                    ],
                },
            ],
        },
        {
            question: '_t_Why should I join your affiliate programme?_t_',
            category: 'Affiliate programme',
            sub_category: '_t_Partners_t_',
            label: 'why-affiliate',
            answer: [
                {
                    translation_text: '_t_When you join our affiliate programme,_t_',
                    list: {
                        list_style: 'disc',
                        padding_left: '5rem',
                        margin_top: '0.3rem',
                        items: [
                            {
                                translation_text:
                                    "_t_You'll have multiple income opportunities by joining other partnership programmes that we offer._t_",
                            },
                            {
                                translation_text:
                                    "_t_You'll have access to various marketing tools to help promote our products and services to your clients._t_",
                            },
                            {
                                translation_text:
                                    "_t_You'll be able to take advantage of our multilingual platforms and reach clients wherever they are._t_",
                            },
                            {
                                translation_text:
                                    "_t_You'll receive prompt monthly payouts via your preferred payment method._t_",
                            },
                            {
                                translation_text:
                                    "_t_You won't be charged any hidden fees. You'll be able to see exactly what your earnings are._t_",
                            },
                            {
                                translation_text:
                                    "_t_You'll have a dedicated account manager to help you._t_",
                            },
                        ],
                    },
                },
            ],
        },
        {
            question: '_t_What type of commission plans do you offer?_t_',
            category: 'Affiliate programme',
            sub_category: '_t_Partners_t_',
            label: 'commission-plans',
            answer: [
                { translation_text: '_t_We have 3 commission plans:_t_' },
                {
                    translation_text:
                        '_t_<0>Revenue share</0><br/>Earn commission of up to 45% based on the monthly net revenue generated by your clients. The higher their net revenue, the higher your commission payout._t_',
                    translation_components: [{ key: 0, type: 'strong' }],
                },
                {
                    translation_text:
                        '_t_<0>Turnover</0><br/>Earn up to 1.5% commission for each contract bought by your clients. The lower the probability of winning, the higher your commission payout._t_',
                    translation_components: [{ key: 0, type: 'strong' }],
                },
                {
                    translation_text: '_t_<0>Cost per acquisition</0> (For the EU only)_t_',
                    translation_components: [{ key: 0, type: 'strong' }],
                },
                {
                    translation_text:
                        '_t_Earn 100 USD in commission for each successful referral. Your referred client must open a real account using your tracking link and deposit 100 USD or more (one-time or accumulative)._t_',
                },
                {
                    translation_text:
                        '_t_Learn more about our commission plans on <0>our Affiliate and IB Programme page</0>._t_',
                    translation_components: [
                        { key: 0, type: 'link', to: 'https://deriv.com/partners/affiliate-ib/' },
                    ],
                },
            ],
        },
        {
            question: '_t_Who can apply as an affiliate?_t_',
            category: 'Affiliate programme',
            sub_category: '_t_Partners_t_',
            label: 'who-can-apply',
        },
        {
            question: '_t_Is it free to join your affiliate programme?_t_',
            category: 'Affiliate programme',
            sub_category: '_t_Partners_t_',
            label: 'is-it-free',
            answer: [
                {
                    translation_text: "_t_Yes, it's completely free of charge <0>to join</0>._t_",
                    translation_components: [
                        { key: 0, type: 'link', to: 'https://login.deriv.com/signup.php?lang=0' },
                    ],
                },
            ],
        },
        {
            question: '_t_What is a referred client?_t_',
            category: 'Affiliate programme',
            sub_category: '_t_Partners_t_',
            label: 'referred-client',
            answer: [
                {
                    translation_text:
                        '_t_A referred client is a client who signed up using your tracking link, made a deposit in their account, and started trading on our platforms. As an affiliate, you stand to earn commission from the trades performed by your referred clients._t_',
                },
            ],
        },
        {
            question: '_t_I forgot my affiliate password. What should I do?_t_',
            category: 'Affiliate programme',
            sub_category: '_t_Partners_t_',
            label: 'forgot-password',
        },
        {
            question: '_t_Where can I find my referral link?_t_',
            category: 'Affiliate programme',
            sub_category: '_t_Partners_t_',
            label: 'referral-link',
        },
        {
            question: '_t_How do I change my affiliate payment method?_t_',
            category: 'Affiliate programme',
            sub_category: '_t_Partners_t_',
            label: 'payment-method',
        },
        {
            question: '_t_How and when will I receive my commission payout?_t_',
            category: 'Affiliate programme',
            sub_category: '_t_Partners_t_',
            label: 'commission-payout',
        },
        {
            question: '_t_How do I see my earnings?_t_',
            category: 'Affiliate programme',
            sub_category: '_t_Partners_t_',
            label: 'see-earnings',
        },
        {
            question: '_t_What type of reports will I have access to?_t_',
            category: 'Affiliate programme',
            sub_category: '_t_Partners_t_',
            label: 'reports-access',
        },
    ],
}

export default affiliate_programme_data
