import { ArticlesDataType } from './_data-types'

const affiliate_programme: ArticlesDataType = {
    section: 'General',
    category: '_t_Affiliate programme_t_',
    articles: [
        {
            question: '_t_How do I sign up as an affiliate?_t_',
            category: 'Affiliate programme',
            sub_category: '_t_Partners_t_',
            label: 'affiliate-sign-up',
            answer: [
                {
                    translation_text:
                        "_t_Complete <0>this form</0>, and we'll get in touch with you in a couple of days.<br/>You'll need a real Deriv trading account, too. If you don't have one, sign up <1>here</1>._t_",
                    translation_components: [
                        { key: 0, type: 'link', to: 'https://login.deriv.com/signup.php?lang=0' },
                        { key: 1, type: 'link', to: '/signup/' },
                    ],
                },
            ],
        },
        {
            question: '_t_Why should I join your affiliate programme?_t_',
            category: 'Affiliate programme',
            sub_category: '_t_Partners_t_',
            label: 'why-affiliate',
            answer: [
                {
                    translation_text: '_t_When you join our affiliate programme,_t_',
                    list: {
                        list_style: 'disc',
                        padding_left: '5rem',
                        margin_top: '0.3rem',
                        items: [
                            {
                                translation_text:
                                    "_t_You'll have multiple income opportunities by joining other partnership programmes that we offer._t_",
                            },
                            {
                                translation_text:
                                    "_t_You'll have access to various marketing tools to help promote our products and services to your clients._t_",
                            },
                            {
                                translation_text:
                                    "_t_You'll be able to take advantage of our multilingual platforms and reach clients wherever they are._t_",
                            },
                            {
                                translation_text:
                                    "_t_You'll receive prompt monthly payouts via your preferred payment method._t_",
                            },
                            {
                                translation_text:
                                    "_t_You won't be charged any hidden fees. You'll be able to see exactly what your earnings are._t_",
                            },
                            {
                                translation_text:
                                    "_t_You'll have a dedicated account manager to help you._t_",
                            },
                        ],
                    },
                },
            ],
        },
        {
            question: '_t_What type of commission plans do you offer?_t_',
            category: 'Affiliate programme',
            sub_category: '_t_Partners_t_',
            label: 'commission-plans',
            answer: [
                { translation_text: '_t_We have 3 commission plans:_t_' },
                {
                    translation_text:
                        '_t_<0>Revenue share</0><br/>Earn commission of up to 45% based on the monthly net revenue generated by your clients. The higher their net revenue, the higher your commission payout._t_',
                    translation_components: [{ key: 0, type: 'strong' }],
                },
                {
                    translation_text:
                        '_t_<0>Turnover</0><br/>Earn up to 1.5% commission for each contract bought by your clients. The lower the probability of winning, the higher your commission payout._t_',
                    translation_components: [{ key: 0, type: 'strong' }],
                },
                {
                    translation_text: '_t_<0>Cost per acquisition</0> (For the EU only)_t_',
                    translation_components: [{ key: 0, type: 'strong' }],
                },
                {
                    translation_text:
                        '_t_Earn 100 USD in commission for each successful referral. Your referred client must open a real account using your tracking link and deposit 100 USD or more (one-time or accumulative)._t_',
                },
                {
                    translation_text:
                        '_t_Learn more about our commission plans on <0>our Affiliate and IB Programme page</0>._t_',
                    translation_components: [
                        { key: 0, type: 'link', to: 'https://deriv.com/partners/affiliate-ib/' },
                    ],
                },
            ],
        },
        {
            question: '_t_Who can apply as an affiliate?_t_',
            category: 'Affiliate programme',
            sub_category: '_t_Partners_t_',
            label: 'who-can-apply',
            answer: [
                {
                    translation_text: '_t_We encourage you to become our affiliate if you are:_t_',
                    list: {
                        list_style: 'disc',
                        padding_left: '5rem',
                        margin_top: '1rem',
                        items: [
                            {
                                translation_text:
                                    '_t_<0>A webmaster</0><br/>Do you have a trading-related website? Join our network of affiliates and turn your traffic into revenue by promoting our products and services._t_',
                                translation_components: [{ key: 0, type: 'strong' }],
                            },
                            {
                                translation_text:
                                    '_t_<0>A signal provider</0><br/>Do you provide trading data for others to follow? Grow your community of traders and earn commission when they sign up and trade on our platforms._t_',
                                translation_components: [{ key: 0, type: 'strong' }],
                            },
                            {
                                translation_text:
                                    '_t_<0>A trading mentor</0><br/>Do you mentor other traders? Help them become better traders and earn commission when they sign up and trade on our platforms._t_',
                                translation_components: [{ key: 0, type: 'strong' }],
                            },
                            {
                                translation_text:
                                    '_t_<0>A software developer</0><br/>Build your own trading platform using our API and earn commission when your clients sign up and trade._t_',
                                translation_components: [{ key: 0, type: 'strong' }],
                            },
                            {
                                translation_text:
                                    '_t_<0>A social media admin</0><br/>Promote our products and services on your social media pages, and earn commission when you convert your audience into traders._t_',
                                translation_components: [{ key: 0, type: 'strong' }],
                            },
                            {
                                translation_text:
                                    '_t_<0>A blogger/vlogger</0><br/>Promote our products and services and earn commission when you convert your audience into traders._t_',
                                translation_components: [{ key: 0, type: 'strong' }],
                            },
                        ],
                    },
                },
            ],
        },
        {
            question: '_t_Is it free to join your affiliate programme?_t_',
            category: 'Affiliate programme',
            sub_category: '_t_Partners_t_',
            label: 'is-it-free',
            answer: [
                {
                    translation_text: "_t_Yes, it's completely free of charge <0>to join</0>._t_",
                    translation_components: [
                        { key: 0, type: 'link', to: 'https://login.deriv.com/signup.php?lang=0' },
                    ],
                },
            ],
        },
        {
            question: '_t_What is a referred client?_t_',
            category: 'Affiliate programme',
            sub_category: '_t_Partners_t_',
            label: 'referred-client',
            answer: [
                {
                    translation_text:
                        '_t_A referred client is a client who signed up using your tracking link, made a deposit in their account, and started trading on our platforms. As an affiliate, you stand to earn commission from the trades performed by your referred clients._t_',
                },
            ],
        },
        {
            question: '_t_I forgot my affiliate password. What should I do?_t_',
            category: 'Affiliate programme',
            sub_category: '_t_Partners_t_',
            label: 'forgot-password',
            answer: [
                {
                    translation_text: '_t_You can reset your affiliate password <0>here</0>._t_',
                    translation_components: [
                        {
                            key: 0,
                            type: 'link',
                            to: 'https://login.deriv.com/password-reset.php?lang=0',
                        },
                    ],
                },
            ],
        },
        {
            question: '_t_Where can I find my referral link?_t_',
            category: 'Affiliate programme',
            sub_category: '_t_Partners_t_',
            label: 'referral-link',
            answer: [
                {
                    translation_text: '_t_Follow these steps to get your referral link:_t_',
                    list: {
                        list_style: 'decimal',
                        padding_left: '5rem',
                        margin_top: '1rem',
                        items: [
                            {
                                translation_text:
                                    '_t_<0>Log in</0> to your affiliate dashboard._t_',
                                translation_components: [
                                    {
                                        key: 0,
                                        type: 'link',
                                        to: 'https://login.deriv.com/signin.php?lang=0',
                                    },
                                ],
                            },
                            {
                                translation_text: '_t_Click the <0>Marketing<0/> tab._t_',
                                translation_components: [{ key: 0, type: 'strong' }],
                            },
                            {
                                translation_text:
                                    '_t_Go to the first item in the media gallery and click <0>Get media</0> code._t_',
                                translation_components: [{ key: 0, type: 'strong' }],
                            },
                            {
                                translation_text:
                                    '_t_Copy the link in the <0>Landing page URL</0> field. This is the referral link that you can share with your clients._t_',
                                translation_components: [{ key: 0, type: 'strong' }],
                            },
                        ],
                    },
                },
            ],
        },
        {
            question: '_t_How do I change my affiliate payment method?_t_',
            category: 'Affiliate programme',
            sub_category: '_t_Partners_t_',
            label: 'payment-method',
            answer: [
                {
                    translation_text: '_t_Follow these steps to change your payment method:_t_',
                    list: {
                        list_style: 'decimal',
                        padding_left: '5rem',
                        margin_top: '1rem',
                        items: [
                            {
                                translation_text: '_t_<0>Log in</0> to your dashboard._t_',
                                translation_components: [
                                    {
                                        key: 0,
                                        type: 'link',
                                        to: 'https://login.deriv.com/signin.php',
                                    },
                                ],
                            },
                            {
                                translation_text:
                                    '_t_Click the <0>Finances</0> tab and select <0>Payment instructions</0>._t_',
                                translation_components: [{ key: 0, type: 'strong' }],
                            },
                            {
                                translation_text:
                                    '_t_Select your preferred payment method, enter the necessary details, and click <0>Update</0>._t_',
                                translation_components: [{ key: 0, type: 'strong' }],
                            },
                        ],
                    },
                },
            ],
        },
        {
            question: '_t_How and when will I receive my commission payout?_t_',
            category: 'Affiliate programme',
            sub_category: '_t_Partners_t_',
            label: 'commission-payout',
            answer: [
                {
                    translation_text:
                        "_t_We'll credit your commission for the previous month into your trading account after the 15th of every month. As an affiliate, you’ll earn commission when your referred clients trade on options and multipliers. To earn from your clients' MT5 trades, you'll need to sign up as an introducing broker. (see <0>How do I sign up as an introducing broker (IB)?</0>)_t_",
                    translation_components: [
                        { key: 0, type: 'link', to: '/help-centre/ib-programme/#ib-sign-up' },
                    ],
                },
            ],
        },
        {
            question: '_t_How do I see my earnings?_t_',
            category: 'Affiliate programme',
            sub_category: '_t_Partners_t_',
            label: 'see-earnings',
            answer: [
                {
                    translation_text: '_t_Follow these steps to see your earnings:_t_',
                    list: {
                        list_style: 'decimal',
                        padding_left: '5rem',
                        margin_top: '1rem',
                        items: [
                            {
                                translation_text: '_t_<0>Log in</0> to your dashboard._t_',
                                translation_components: [
                                    {
                                        key: 0,
                                        type: 'link',
                                        to: 'https://login.deriv.com/signin.php',
                                    },
                                ],
                            },
                            {
                                translation_text:
                                    '_t_Go to <0>Reports</0>, and select <0>Detailed activity report</0>._t_',
                                translation_components: [{ key: 0, type: 'strong' }],
                            },
                            {
                                translation_text:
                                    '_t_Set the duration and filters and click <0>Display report</0> or <0>Download report</0>._t_',
                                translation_components: [{ key: 0, type: 'strong' }],
                            },
                        ],
                    },
                },
            ],
        },
        {
            question: '_t_What type of reports will I have access to?_t_',
            category: 'Affiliate programme',
            sub_category: '_t_Partners_t_',
            label: 'reports-access',
            answer: [
                {
                    translation_text:
                        "_t_You'll have access to reports that show your hits, impressions, click-through rates, clients' trading activity, and more._t_",
                },
            ],
        },
    ],
}

export default affiliate_programme
