import React from 'react'
import LazySymbol from 'components/elements/lazy-symbol'

export const optionItemDefault = {
    name: 'default',
    display_name: '',
    key: '14',
    icon: '',
    market: '',
}
export const optionLeverageDefault = {
    name: 'value',
    display_name: '',
    key: '14',
    icon: '',
    market: '',
}
export const leverageItemLists = [
    {
        name: 4000,
        display_name: 4000,
        key: '1',
        icon: '',
    },
    {
        name: 3500,
        display_name: 3500,
        key: '2',
        icon: '',
    },
    {
        name: 3000,
        display_name: 3000,
        key: '3',
        icon: '',
    },
    {
        name: 2500,
        display_name: 2500,
        key: '4',
        icon: '',
    },
    {
        name: 2000,
        display_name: 2000,
        key: '5',
        icon: '',
    },
    {
        name: 1500,
        display_name: 1500,
        key: '6',
        icon: '',
    },
    {
        name: 1000,
        display_name: 1000,
        key: '7',
        icon: '',
    },
    {
        name: 900,
        display_name: 900,
        key: '8',
        icon: '',
    },
    {
        name: 800,
        display_name: 800,
        key: '9',
        icon: '',
    },
    {
        name: 700,
        display_name: 700,
        key: '10',
        icon: '',
    },
    {
        name: 600,
        display_name: 600,
        key: '11',
        icon: '',
    },
    {
        name: 500,
        display_name: 500,
        key: '12',
        icon: '',
    },
    {
        name: 400,
        display_name: 400,
        key: '13',
        icon: '',
    },
    {
        name: 200,
        display_name: 200,
        key: '14',
        icon: '',
    },
    {
        name: 100,
        display_name: 100,
        key: '15',
        icon: '',
    },
    {
        name: 50,
        display_name: 50,
        key: '16',
        icon: '',
    },
    {
        name: 30,
        display_name: 30,
        key: '17',
        icon: '',
    },
    {
        name: 5,
        display_name: 5,
        key: '18',
        icon: '',
    },
]
export const syntheticItemLists = [
    {
        name: 'Boom 1000 Index',
        display_name: 'Boom 1000 Index',
        icon: <LazySymbol name="BOOM1000" alt="boom 100" />,
        market: 'synthetic_indices',
        symbol: 'BOOM1000',
    },
    {
        name: 'Boom 500 Index',
        display_name: 'Boom 500 Index',
        icon: <LazySymbol name="BOOM500" alt="boom 500" />,
        market: 'synthetic_indices',
        symbol: 'BOOM500',
    },
    {
        name: 'Boom 300 Index',
        display_name: 'Boom 300 Index',
        icon: <LazySymbol name="BOOM300EU" alt="boom 300" />,
        market: 'synthetic_indices',
        symbol: 'BOOM300N',
    },
    {
        name: 'Crash 1000 Index',
        display_name: 'Crash 1000 Index',
        icon: <LazySymbol name="CRASH1000" alt="crash 1000" />,
        market: 'synthetic_indices',
        symbol: 'CRASH1000',
    },
    {
        name: 'Crash 500 Index',
        display_name: 'Crash 500 Index',
        icon: <LazySymbol name="CRASH500" alt="crash 500" />,
        market: 'synthetic_indices',
        symbol: 'CRASH500',
    },
    {
        name: 'Crash 300 Index',
        display_name: 'Crash 300 Index',
        icon: <LazySymbol name="CRASH300EU" alt="crash 300" />,
        market: 'synthetic_indices',
        symbol: 'CRASH300N',
    },
    {
        name: 'Step Index',
        display_name: 'Step Index',
        icon: <LazySymbol name="STEPINDICES" alt="step index" />,
        market: 'synthetic_indices',
        symbol: 'stpRNG',
    },
    {
        name: 'Bear Market Index',
        display_name: 'Bear Market Index',
        icon: <LazySymbol name="MARKETBEARNEW" alt="bear market index" />,
        market: 'synthetic_indices',
        symbol: 'RDBEAR',
    },
    {
        name: 'Bull Market Index',
        display_name: 'Bull Market Index',
        icon: <LazySymbol name="MARKETBULLNEW" alt="bull market index" />,
        market: 'synthetic_indices',
        symbol: 'RDBULL',
    },
    {
        name: 'Volatility 10 (1s) Index',
        display_name: 'Volatility 10 (1s) Index',
        icon: <LazySymbol name="INDEX10S1" alt="vol 10 1s" />,
        market: 'synthetic_indices',
        symbol: '1HZ10V',
    },
    {
        name: 'Volatility 10 Index',
        display_name: 'Volatility 10 Index',
        icon: <LazySymbol name="INDEX10" alt="vol 10" />,
        market: 'synthetic_indices',
        symbol: 'R_10',
    },
    {
        name: 'Volatility 25 (1s) Index',
        display_name: 'Volatility 25 (1s) Index',
        icon: <LazySymbol name="INDEX25S1" alt="vol 25 1s" />,
        market: 'synthetic_indices',
        symbol: '1HZ25V',
    },
    {
        name: 'Volatility 25 Index',
        display_name: 'Volatility 25 Index',
        icon: <LazySymbol name="INDEX25" alt="Volatility 25" />,
        market: 'synthetic_indices',
        symbol: 'R_25',
    },
    {
        name: 'Volatility 50 (1s) Index',
        display_name: 'Volatility 50 (1s) Index',
        icon: <LazySymbol name="INDEX50S1" alt="vol 50 1s" />,
        market: 'synthetic_indices',
        symbol: '1HZ50V',
    },
    {
        name: 'Volatility 50 Index',
        display_name: 'Volatility 50 Index',
        icon: <LazySymbol name="INDEX50" alt="vol 50" />,
        market: 'synthetic_indices',
        symbol: 'R_50',
    },
    {
        name: 'Volatility 75 (1s) Index',
        display_name: 'Volatility 75 (1s) Index',
        icon: <LazySymbol name="INDEX75S1" alt="vol 75 1s" />,
        market: 'synthetic_indices',
        symbol: '1HZ75V',
    },
    {
        name: 'Volatility 75 Index',
        display_name: 'Volatility 75 Index',
        icon: <LazySymbol name="INDEX75" alt="vol 75" />,
        market: 'synthetic_indices',
        symbol: 'R_75',
    },
    {
        name: 'Volatility 100 (1s) Index',
        display_name: 'Volatility 100 (1s) Index',
        icon: <LazySymbol name="INDEX100S1" alt="vol 100 1s" />,
        market: 'synthetic_indices',
        symbol: '1HZ100V',
    },
    {
        name: 'Volatility 100 Index',
        display_name: 'Volatility 100 Index',
        icon: <LazySymbol name="INDEX100" alt="vol 100" />,
        market: 'synthetic_indices',
        symbol: 'R_100',
    },
    {
        name: 'Volatility 200 (1s) Index',
        display_name: 'Volatility 200 (1s) Index',
        icon: <LazySymbol name="VINDEXIC200" alt="vol 200 1s" />,
        market: 'synthetic_indices',
        symbol: '1HZ200V',
    },
    {
        name: 'Volatility 300 (1s) Index',
        display_name: 'Volatility 300 (1s) Index',
        icon: <LazySymbol name="VINDEXIC300" alt="vol 300 1s" />,
        market: 'synthetic_indices',
        symbol: '1HZ300V',
    },
    {
        name: 'Jump 10 Index',
        display_name: 'Jump 10 Index',
        icon: <LazySymbol name="JUMP10NEW" alt="jump 10" />,
        market: 'synthetic_indices',
        symbol: 'JD10',
    },
    {
        name: 'Jump 25 Index',
        display_name: 'Jump 25 Index',
        icon: <LazySymbol name="JUMP25NEW" alt="jump 25" />,
        market: 'synthetic_indices',
        symbol: 'JD25',
    },
    {
        name: 'Jump 50 Index',
        display_name: 'Jump 50 Index',
        icon: <LazySymbol name="JUMP50NEW" alt="jump 50" />,
        market: 'synthetic_indices',
        symbol: 'JD50',
    },
    {
        name: 'Jump 75 Index',
        display_name: 'Jump 75 Index',
        icon: <LazySymbol name="JUMP75NEW" alt="jump 75" />,
        market: 'synthetic_indices',
        symbol: 'JD75',
    },
    {
        name: 'Jump 100 Index',
        display_name: 'Jump 100 Index',
        icon: <LazySymbol name="JUMP100NEW" alt="jump 100" />,
        market: 'synthetic_indices',
        symbol: 'JD100',
    },
]
export const financialItemLists = [
    {
        name: 'AUS200',
        display_name: 'Australian Index',
        icon: <LazySymbol name="AUS200" alt="australia 200" />,
        market: 'other',
        symbol: 'OTC_AS51',
    },
    {
        name: 'HK50',
        display_name: 'Hong Kong Index',
        icon: <LazySymbol name="STOCKSHONGKONG50" alt="hong kong 50" />,
        market: 'other',
        symbol: 'OTC_HSI',
    },
    {
        name: 'JP225',
        display_name: 'Japanese Index',
        icon: <LazySymbol name="JP225" alt="japan 225" />,
        market: 'other',
        symbol: 'OTC_N225',
    },
    {
        name: 'EUR50',
        display_name: 'Euro 50 Index',
        icon: <LazySymbol name="EUR50" alt="europe 50" />,
        market: 'other',
        symbol: 'OTC_SX5E',
    },
    {
        name: 'FRA40',
        display_name: 'French Index',
        icon: <LazySymbol name="FRA40" alt="france 40" />,
        market: 'other',
        symbol: 'OTC_FCHI',
    },
    {
        name: 'GER30',
        display_name: 'German Index',
        icon: <LazySymbol name="STOCKSGERMANY30" alt="german 30" />,
        market: 'other',
        symbol: 'OTC_GDAXI',
    },
    {
        name: 'SWISS20',
        display_name: 'Swiss Index',
        icon: <LazySymbol name="STOCKSSWISS20" alt="swiss 20" />,
        market: 'other',
        symbol: 'OTC_SSMI',
    },
    {
        name: 'UK100',
        display_name: 'UK Index',
        icon: <LazySymbol name="UK100" alt="uk 100" />,
        market: 'other',
        symbol: 'OTC_FTSE',
    },
    {
        name: 'USINDEX',
        display_name: 'US Index',
        icon: <LazySymbol name="STOCKSUS500" alt="us 500" />,
        market: 'other',
        symbol: 'OTC_SPC',
    },
    {
        name: 'USTECHINDEX',
        display_name: 'US Tech Index',
        icon: <LazySymbol name="STOCKSUSTECH100" alt="us tech 100" />,
        market: 'other',
        symbol: 'OTC_NDX',
    },
    {
        name: 'STOCKSWALLSTREET30',
        display_name: 'Wall Street 30 Index',
        icon: <LazySymbol name="STOCKSWALLSTREET30" alt="wall street 30" />,
        market: 'other',
        symbol: 'OTC_DJI',
    },
    {
        name: 'BTCUSD',
        display_name: 'BTC/USD',
        icon: <LazySymbol name="BTCUSD" alt="btc usd" />,
        market: 'crypto',
        symbol: 'cryBTCUSD',
    },
    {
        name: 'ETHUSD',
        display_name: 'ETH/USD',
        icon: <LazySymbol name="ETHUSD" alt="eth usd" />,
        market: 'crypto',
        symbol: 'cryETHUSD',
    },
    {
        name: 'AUDJPY',
        display_name: 'AUD/JPY',
        icon: <LazySymbol name="AUDJPY" alt="aud jpy" />,
        market: 'forex',
        symbol: 'frxAUDJPY',
    },
    {
        name: 'AUDCAD',
        display_name: 'AUD/CAD',
        icon: <LazySymbol name="AUDCAD" alt="aud cad" />,
        market: 'forex',
        symbol: 'frxAUDCAD',
    },
    {
        name: 'AUDCHF',
        display_name: 'AUD/CHF',
        icon: <LazySymbol name="AUDCHF" alt="aud chf" />,
        market: 'forex',
        symbol: 'frxAUDCHF',
    },
    {
        name: 'AUDNZD',
        display_name: 'AUD/NZD',
        icon: <LazySymbol name="AUDNZD" alt="aud nzd" />,
        market: 'forex',
        symbol: 'frxAUDNZD',
    },
    {
        name: 'AUDUSD',
        display_name: 'AUD/USD',
        icon: <LazySymbol name="AUDUSD" alt="aud usd" />,
        market: 'forex',
        symbol: 'frxAUDUSD',
    },
    {
        name: 'EURAUD',
        display_name: 'EUR/AUD',
        icon: <LazySymbol name="EURAUD" alt="eur aud" />,
        market: 'forex',
        symbol: 'frxEURAUD',
    },
    {
        name: 'EURCAD',
        display_name: 'EUR/CAD',
        icon: <LazySymbol name="EURCAD" alt="eur cad" />,
        market: 'forex',
        symbol: 'frxEURCAD',
    },
    {
        name: 'EURCHF',
        display_name: 'EUR/CHF',
        icon: <LazySymbol name="EURCHF" alt="eur chf" />,
        market: 'forex',
        symbol: 'frxEURCHF',
    },
    {
        name: 'EURGBP',
        display_name: 'EUR/GBP',
        icon: <LazySymbol name="EURGBP" alt="eur gbp" />,
        market: 'forex',
        symbol: 'frxEURGBP',
    },
    {
        name: 'EURJPY',
        display_name: 'EUR/JPY',
        icon: <LazySymbol name="EURJPY" alt="eur jpy" />,
        market: 'forex',
        symbol: 'frxEURJPY',
    },
    {
        name: 'EURNZD',
        display_name: 'EUR/NZD',
        icon: <LazySymbol name="EURNZD" alt="eur nzd" />,
        market: 'forex',
        symbol: 'frxEURNZD',
    },
    {
        name: 'EURUSD',
        display_name: 'EUR/USD',
        icon: <LazySymbol name="EURUSD" alt="eur usd" />,
        market: 'forex',
        symbol: 'frxEURUSD',
    },
    {
        name: 'GBPCHF',
        display_name: 'GBP/CHF',
        icon: <LazySymbol name="GBPCHF" alt="gbp chf" />,
        market: 'forex',
        symbol: 'frxGBPCHF',
    },
    {
        name: 'GBPJPY',
        display_name: 'GBP/JPY',
        icon: <LazySymbol name="GBPJPY" alt="gbp jpy" />,
        market: 'forex',
        symbol: 'frxGBPJPY',
    },
    {
        name: 'GBPUSD',
        display_name: 'GBP/USD',
        icon: <LazySymbol name="GBPUSD" alt="gbp usd" />,
        market: 'forex',
        symbol: 'frxGBPUSD',
    },
    {
        name: 'NZDUSD',
        display_name: 'NZD/USD',
        icon: <LazySymbol name="NZDUSD" alt="nzd usd" />,
        market: 'forex',
        symbol: 'frxNZDUSD',
    },
    {
        name: 'USDCAD',
        display_name: 'USD/CAD',
        icon: <LazySymbol name="USDCAD" alt="usd cad" />,
        market: 'forex',
        symbol: 'frxUSDCAD',
    },
    {
        name: 'USDCHF',
        display_name: 'USD/CHF',
        icon: <LazySymbol name="USDCHF" alt="usd chf" />,
        market: 'forex',
        symbol: 'frxUSDCHF',
    },
    {
        name: 'USDJPY',
        display_name: 'USD/JPY',
        icon: <LazySymbol name="USDJPY" alt="usd jpy" />,
        market: 'forex',
        symbol: 'frxUSDJPY',
    },
    {
        name: 'USDMXN',
        display_name: 'USD/MXN',
        icon: <LazySymbol name="USDMXN" alt="usd mxn" />,
        market: 'forex',
        symbol: 'frxUSDMXN',
    },
    {
        name: 'USDNOK',
        display_name: 'USD/NOK',
        icon: <LazySymbol name="USDNOK" alt="usd nok" />,
        market: 'forex',
        symbol: 'frxUSDNOK',
    },
    {
        name: 'USDPLN',
        display_name: 'USD/PLN',
        icon: <LazySymbol name="USDPLN" alt="usd pln" />,
        market: 'forex',
        symbol: 'frxUSDPLN',
    },
    {
        name: 'USDSEK',
        display_name: 'USD/SEK',
        icon: <LazySymbol name="USDSEK" alt="usd sek" />,
        market: 'forex',
        symbol: 'frxUSDSEK',
    },
    {
        name: 'GBPAUD',
        display_name: 'GBP/AUD',
        icon: <LazySymbol name="GBPAUD" alt="gbp aud" />,
        market: 'forex',
        symbol: 'frxGBPAUD',
    },
    {
        name: 'GBPCAD',
        display_name: 'GBP/CAD',
        icon: <LazySymbol name="GBPCAD" alt="gbp cad" />,
        market: 'forex',
        symbol: 'frxGBPCAD',
    },
    {
        name: 'GBPNZD',
        display_name: 'GBP/NZD',
        icon: <LazySymbol name="GBPNZD" alt="gbp nzd" />,
        market: 'forex',
        symbol: 'frxGBPNZD',
    },
    {
        name: 'NZDJPY',
        display_name: 'NZD/JPY',
        icon: <LazySymbol name="NZDJPY" alt="nzd jpy" />,
        market: 'forex',
        symbol: 'frxNZDJPY',
    },
    {
        name: 'XAUUSD',
        display_name: 'Gold/USD',
        icon: <LazySymbol name="GOLDUSD" alt="gold usd" />,
        market: 'commodities',
        symbol: 'OTC_HSI',
    },
    {
        name: 'XAGUSD',
        display_name: 'Silver/USD',
        icon: <LazySymbol name="SILVERUSD" alt="silver usd" />,
        market: 'commodities',
        symbol: 'frxXAGUSD',
    },
    {
        name: 'XPDUSD',
        display_name: 'Palladium/USD',
        icon: <LazySymbol name="PALLADIUMUSD" alt="palladium usd" />,
        market: 'commodities',
        symbol: 'frxXPDUSD',
    },
    {
        name: 'XPTUSD',
        display_name: 'Platinum/USD',
        icon: <LazySymbol name="PLATINUMUSD" alt="platinum usd" />,
        market: 'commodities',
        symbol: 'frxXPTUSD',
    },
    {
        name: 'AUDBASKET',
        display_name: 'AUD Basket',
        icon: <LazySymbol name="AUDBASKET" alt="aud basket" />,
        market: 'basket_indices',
        symbol: 'WLDAUD',
    },
    {
        name: 'GBPBASKET',
        display_name: 'GBP Basket',
        icon: <LazySymbol name="GBPBASKET" alt="gbp basket" />,
        market: 'basket_indices',
        symbol: 'WLDGBP',
    },
    {
        name: 'EURBASKET',
        display_name: 'EUR Basket',
        icon: <LazySymbol name="EURBASKET" alt="eur basket" />,
        market: 'basket_indices',
        symbol: 'WLDEUR',
    },
    {
        name: 'USDBASKET',
        display_name: 'USD Basket',
        icon: <LazySymbol name="USDBASKET" alt="usd basket" />,
        market: 'basket_indices',
        symbol: 'WLDUSD',
    },
    {
        name: 'GOLDBASKET',
        display_name: 'Gold Basket',
        icon: <LazySymbol name="GOLDBASKET" alt="gold basket" />,
        market: 'basket_indices',
        symbol: 'WLDXAU',
    },
]
