export const optionItemDefault = {
    name: 'default',
    display_name: '',
    key: '14',
    icon: '',
    market: '',
}

export const optionLeverageDefault = {
    name: 'value',
    display_name: '',
    key: '14',
    icon: '',
    market: '',
}

export const leverageItemLists = [
    { name: 4000, display_name: 4000, key: '1', icon: '' },
    { name: 3500, display_name: 3500, key: '2', icon: '' },
    { name: 3000, display_name: 3000, key: '3', icon: '' },
    { name: 2500, display_name: 2500, key: '4', icon: '' },
    { name: 2000, display_name: 2000, key: '5', icon: '' },
    { name: 1500, display_name: 1500, key: '6', icon: '' },
    { name: 1000, display_name: 1000, key: '7', icon: '' },
    { name: 900, display_name: 900, key: '8', icon: '' },
    { name: 800, display_name: 800, key: '9', icon: '' },
    { name: 700, display_name: 700, key: '10', icon: '' },
    { name: 600, display_name: 600, key: '11', icon: '' },
    { name: 500, display_name: 500, key: '12', icon: '' },
    { name: 400, display_name: 400, key: '13', icon: '' },
    { name: 200, display_name: 200, key: '14', icon: '' },
    { name: 100, display_name: 100, key: '15', icon: '' },
    { name: 50, display_name: 50, key: '16', icon: '' },
    { name: 30, display_name: 30, key: '17', icon: '' },
    { name: 5, display_name: 5, key: '18', icon: '' },
]

export const syntheticItemLists = [
    {
        name: 'Boom 1000 Index',
        display_name: 'Boom 1000 Index',
        market: 'synthetic_indices',
        symbol: 'BOOM1000',
    },
    {
        name: 'Boom 500 Index',
        display_name: 'Boom 500 Index',
        market: 'synthetic_indices',
        symbol: 'BOOM500',
    },
    {
        name: 'Boom 300 Index',
        display_name: 'Boom 300 Index',
        market: 'synthetic_indices',
        symbol: 'BOOM300N',
    },
    {
        name: 'Crash 1000 Index',
        display_name: 'Crash 1000 Index',
        market: 'synthetic_indices',
        symbol: 'CRASH1000',
    },
    {
        name: 'Crash 500 Index',
        display_name: 'Crash 500 Index',
        market: 'synthetic_indices',
        symbol: 'CRASH500',
    },
    {
        name: 'Crash 300 Index',
        display_name: 'Crash 300 Index',
        market: 'synthetic_indices',
        symbol: 'CRASH300N',
    },
    {
        name: 'Step Index',
        display_name: 'Step Index',
        market: 'synthetic_indices',
        symbol: 'stpRNG',
    },
    {
        name: 'Bear Market Index',
        display_name: 'Bear Market Index',
        market: 'synthetic_indices',
        symbol: 'RDBEAR',
    },
    {
        name: 'Bull Market Index',
        display_name: 'Bull Market Index',
        market: 'synthetic_indices',
        symbol: 'RDBULL',
    },
    {
        name: 'Volatility 10 (1s) Index',
        display_name: 'Volatility 10 (1s) Index',
        market: 'synthetic_indices',
        symbol: '1HZ10V',
    },
    {
        name: 'Volatility 10 Index',
        display_name: 'Volatility 10 Index',
        market: 'synthetic_indices',
        symbol: 'R_10',
    },
    {
        name: 'Volatility 25 (1s) Index',
        display_name: 'Volatility 25 (1s) Index',
        market: 'synthetic_indices',
        symbol: '1HZ25V',
    },
    {
        name: 'Volatility 25 Index',
        display_name: 'Volatility 25 Index',
        market: 'synthetic_indices',
        symbol: 'R_25',
    },
    {
        name: 'Volatility 50 (1s) Index',
        display_name: 'Volatility 50 (1s) Index',
        market: 'synthetic_indices',
        symbol: '1HZ50V',
    },
    {
        name: 'Volatility 50 Index',
        display_name: 'Volatility 50 Index',
        market: 'synthetic_indices',
        symbol: 'R_50',
    },
    {
        name: 'Volatility 75 (1s) Index',
        display_name: 'Volatility 75 (1s) Index',
        market: 'synthetic_indices',
        symbol: '1HZ75V',
    },
    {
        name: 'Volatility 75 Index',
        display_name: 'Volatility 75 Index',
        market: 'synthetic_indices',
        symbol: 'R_75',
    },
    {
        name: 'Volatility 100 (1s) Index',
        display_name: 'Volatility 100 (1s) Index',
        market: 'synthetic_indices',
        symbol: '1HZ100V',
    },
    {
        name: 'Volatility 100 Index',
        display_name: 'Volatility 100 Index',
        market: 'synthetic_indices',
        symbol: 'R_100',
    },
    {
        name: 'Volatility 200 (1s) Index',
        display_name: 'Volatility 200 (1s) Index',
        market: 'synthetic_indices',
        symbol: '1HZ200V',
    },
    {
        name: 'Volatility 300 (1s) Index',
        display_name: 'Volatility 300 (1s) Index',
        market: 'synthetic_indices',
        symbol: '1HZ300V',
    },
    {
        name: 'Jump 10 Index',
        display_name: 'Jump 10 Index',
        market: 'synthetic_indices',
        symbol: 'JD10',
    },
    {
        name: 'Jump 25 Index',
        display_name: 'Jump 25 Index',
        market: 'synthetic_indices',
        symbol: 'JD25',
    },
    {
        name: 'Jump 50 Index',
        display_name: 'Jump 50 Index',
        market: 'synthetic_indices',
        symbol: 'JD50',
    },
    {
        name: 'Jump 75 Index',
        display_name: 'Jump 75 Index',
        market: 'synthetic_indices',
        symbol: 'JD75',
    },
    {
        name: 'Jump 100 Index',
        display_name: 'Jump 100 Index',
        market: 'synthetic_indices',
        symbol: 'JD100',
    },
]

export const financialItemLists = [
    {
        name: 'AUS200',
        display_name: 'Australian Index',
        market: 'other',
        symbol: 'OTC_AS51',
    },
    {
        name: 'HK50',
        display_name: 'Hong Kong Index',
        market: 'other',
        symbol: 'OTC_HSI',
    },
    {
        name: 'JP225',
        display_name: 'Japanese Index',
        market: 'other',
        symbol: 'OTC_N225',
    },
    {
        name: 'EUR50',
        display_name: 'Euro 50 Index',
        market: 'other',
        symbol: 'OTC_SX5E',
    },
    {
        name: 'FRA40',
        display_name: 'French Index',
        market: 'other',
        symbol: 'OTC_FCHI',
    },
    {
        name: 'GER30',
        display_name: 'German Index',
        market: 'other',
        symbol: 'OTC_GDAXI',
    },
    {
        name: 'SWISS20',
        display_name: 'Swiss Index',
        market: 'other',
        symbol: 'OTC_SSMI',
    },
    {
        name: 'UK100',
        display_name: 'UK Index',
        market: 'other',
        symbol: 'OTC_FTSE',
    },
    {
        name: 'USINDEX',
        display_name: 'US Index',
        market: 'other',
        symbol: 'OTC_SPC',
    },
    {
        name: 'USTECHINDEX',
        display_name: 'US Tech Index',
        market: 'other',
        symbol: 'OTC_NDX',
    },
    {
        name: 'STOCKSWALLSTREET30',
        display_name: 'Wall Street 30 Index',
        market: 'other',
        symbol: 'OTC_DJI',
    },
    {
        name: 'BTCUSD',
        display_name: 'BTC/USD',
        market: 'crypto',
        symbol: 'cryBTCUSD',
    },
    {
        name: 'ETHUSD',
        display_name: 'ETH/USD',
        market: 'crypto',
        symbol: 'cryETHUSD',
    },
    {
        name: 'AUDJPY',
        display_name: 'AUD/JPY',
        market: 'forex',
        symbol: 'frxAUDJPY',
    },
    {
        name: 'AUDCAD',
        display_name: 'AUD/CAD',
        market: 'forex',
        symbol: 'frxAUDCAD',
    },
    {
        name: 'AUDCHF',
        display_name: 'AUD/CHF',
        market: 'forex',
        symbol: 'frxAUDCHF',
    },
    {
        name: 'AUDNZD',
        display_name: 'AUD/NZD',
        market: 'forex',
        symbol: 'frxAUDNZD',
    },
    {
        name: 'AUDUSD',
        display_name: 'AUD/USD',
        market: 'forex',
        symbol: 'frxAUDUSD',
    },
    {
        name: 'EURAUD',
        display_name: 'EUR/AUD',
        market: 'forex',
        symbol: 'frxEURAUD',
    },
    {
        name: 'EURCAD',
        display_name: 'EUR/CAD',
        market: 'forex',
        symbol: 'frxEURCAD',
    },
    {
        name: 'EURCHF',
        display_name: 'EUR/CHF',
        market: 'forex',
        symbol: 'frxEURCHF',
    },
    {
        name: 'EURGBP',
        display_name: 'EUR/GBP',
        market: 'forex',
        symbol: 'frxEURGBP',
    },
    {
        name: 'EURJPY',
        display_name: 'EUR/JPY',
        market: 'forex',
        symbol: 'frxEURJPY',
    },
    {
        name: 'EURNZD',
        display_name: 'EUR/NZD',
        market: 'forex',
        symbol: 'frxEURNZD',
    },
    {
        name: 'EURUSD',
        display_name: 'EUR/USD',
        market: 'forex',
        symbol: 'frxEURUSD',
    },
    {
        name: 'GBPCHF',
        display_name: 'GBP/CHF',
        market: 'forex',
        symbol: 'frxGBPCHF',
    },
    {
        name: 'GBPJPY',
        display_name: 'GBP/JPY',
        market: 'forex',
        symbol: 'frxGBPJPY',
    },
    {
        name: 'GBPUSD',
        display_name: 'GBP/USD',
        market: 'forex',
        symbol: 'frxGBPUSD',
    },
    {
        name: 'NZDUSD',
        display_name: 'NZD/USD',
        market: 'forex',
        symbol: 'frxNZDUSD',
    },
    {
        name: 'USDCAD',
        display_name: 'USD/CAD',
        market: 'forex',
        symbol: 'frxUSDCAD',
    },
    {
        name: 'USDCHF',
        display_name: 'USD/CHF',
        market: 'forex',
        symbol: 'frxUSDCHF',
    },
    {
        name: 'USDJPY',
        display_name: 'USD/JPY',
        market: 'forex',
        symbol: 'frxUSDJPY',
    },
    {
        name: 'USDMXN',
        display_name: 'USD/MXN',
        market: 'forex',
        symbol: 'frxUSDMXN',
    },
    {
        name: 'USDNOK',
        display_name: 'USD/NOK',
        market: 'forex',
        symbol: 'frxUSDNOK',
    },
    {
        name: 'USDPLN',
        display_name: 'USD/PLN',
        market: 'forex',
        symbol: 'frxUSDPLN',
    },
    {
        name: 'USDSEK',
        display_name: 'USD/SEK',
        market: 'forex',
        symbol: 'frxUSDSEK',
    },
    {
        name: 'GBPAUD',
        display_name: 'GBP/AUD',
        market: 'forex',
        symbol: 'frxGBPAUD',
    },
    {
        name: 'GBPCAD',
        display_name: 'GBP/CAD',
        market: 'forex',
        symbol: 'frxGBPCAD',
    },
    {
        name: 'GBPNZD',
        display_name: 'GBP/NZD',
        market: 'forex',
        symbol: 'frxGBPNZD',
    },
    {
        name: 'NZDJPY',
        display_name: 'NZD/JPY',
        market: 'forex',
        symbol: 'frxNZDJPY',
    },
    {
        name: 'XAUUSD',
        display_name: 'Gold/USD',
        market: 'commodities',
        symbol: 'OTC_HSI',
    },
    {
        name: 'XAGUSD',
        display_name: 'Silver/USD',
        market: 'commodities',
        symbol: 'frxXAGUSD',
    },
    {
        name: 'XPDUSD',
        display_name: 'Palladium/USD',
        market: 'commodities',
        symbol: 'frxXPDUSD',
    },
    {
        name: 'XPTUSD',
        display_name: 'Platinum/USD',
        market: 'commodities',
        symbol: 'frxXPTUSD',
    },
    {
        name: 'AUDBASKET',
        display_name: 'AUD Basket',
        market: 'basket_indices',
        symbol: 'WLDAUD',
    },
    {
        name: 'GBPBASKET',
        display_name: 'GBP Basket',
        market: 'basket_indices',
        symbol: 'WLDGBP',
    },
    {
        name: 'EURBASKET',
        display_name: 'EUR Basket',
        market: 'basket_indices',
        symbol: 'WLDEUR',
    },
    {
        name: 'USDBASKET',
        display_name: 'USD Basket',
        market: 'basket_indices',
        symbol: 'WLDUSD',
    },
    {
        name: 'GOLDBASKET',
        display_name: 'Gold Basket',
        market: 'basket_indices',
        symbol: 'WLDXAU',
    },
]
