const residence_list = [
    { name: 'Afghanistan', display_name: 'Afghanistan', value: 'af', prefix: '93' },
    { name: 'Aland Islands', display_name: 'Aland Islands', value: 'ax', prefix: '35818' },
    { name: 'Albania', display_name: 'Albania', value: 'al', prefix: '355' },
    { name: 'Algeria', display_name: 'Algeria', value: 'dz', prefix: '213' },
    { name: 'American Samoa', display_name: 'American Samoa', value: 'as', prefix: '684' },
    { name: 'Andorra', display_name: 'Andorra', value: 'ad', prefix: '376' },
    { name: 'Angola', display_name: 'Angola', value: 'ao', prefix: '244' },
    { name: 'Anguilla', display_name: 'Anguilla', value: 'ai', prefix: '1264' },
    { name: 'Antarctica', display_name: 'Antarctica', value: 'aq', prefix: '672' },
    {
        name: 'Antigua and Barbuda',
        display_name: 'Antigua and Barbuda',
        value: 'ag',
        prefix: '1268',
    },
    { name: 'Argentina', display_name: 'Argentina', value: 'ar', prefix: '54' },
    { name: 'Armenia', display_name: 'Armenia', value: 'am', prefix: '374' },
    { name: 'Aruba', display_name: 'Aruba', value: 'aw', prefix: '297' },
    { name: 'Australia', display_name: 'Australia', value: 'au', prefix: '61' },
    { name: 'Austria', display_name: 'Austria', value: 'at', prefix: '43' },
    { name: 'Azerbaijan', display_name: 'Azerbaijan', value: 'az', prefix: '994' },
    { name: 'Bahamas', display_name: 'Bahamas', value: 'bs', prefix: '1242' },
    { name: 'Bahrain', display_name: 'Bahrain', value: 'bh', prefix: '973' },
    { name: 'Bangladesh', display_name: 'Bangladesh', value: 'bd', prefix: '880' },
    { name: 'Barbados', display_name: 'Barbados', value: 'bb', prefix: '1246' },
    { name: 'Belarus', display_name: 'Belarus', value: 'by', prefix: '375' },
    { name: 'Belgium', display_name: 'Belgium', value: 'be', prefix: '32' },
    { name: 'Belize', display_name: 'Belize', value: 'bz', prefix: '501' },
    { name: 'Benin', display_name: 'Benin', value: 'bj', prefix: '229' },
    { name: 'Bermuda', display_name: 'Bermuda', value: 'bm', prefix: '1441' },
    { name: 'Bhutan', display_name: 'Bhutan', value: 'bt', prefix: '975' },
    { name: 'Bolivia', display_name: 'Bolivia', value: 'bo', prefix: '591' },
    {
        name: 'Bosnia and Herzegovina',
        display_name: 'Bosnia and Herzegovina',
        value: 'ba',
        prefix: '387',
    },
    { name: 'Botswana', display_name: 'Botswana', value: 'bw', prefix: '267' },
    { name: 'Bouvet Island', display_name: 'Bouvet Island', value: 'bv' },
    { name: 'Brazil', display_name: 'Brazil', value: 'br', prefix: '55' },
    {
        name: 'British Indian Ocean Territory',
        display_name: 'British Indian Ocean Territory',
        value: 'io',
        prefix: '246',
    },
    {
        name: 'British Virgin Islands',
        display_name: 'British Virgin Islands',
        value: 'vg',
        prefix: '1284',
    },
    { name: 'Brunei', display_name: 'Brunei', value: 'bn', prefix: '673' },
    { name: 'Bulgaria', display_name: 'Bulgaria', value: 'bg', prefix: '359' },
    { name: 'Burkina Faso', display_name: 'Burkina Faso', value: 'bf', prefix: '226' },
    { name: 'Burundi', display_name: 'Burundi', value: 'bi', prefix: '257' },
    { name: 'Cambodia', display_name: 'Cambodia', value: 'kh', prefix: '855' },
    { name: 'Cameroon', display_name: 'Cameroon', value: 'cm', prefix: '237' },
    { name: 'Canada', display_name: 'Canada', value: 'ca', prefix: '1' },
    { name: 'Cape Verde', display_name: 'Cape Verde', value: 'cv', prefix: '238' },
    {
        name: 'Caribbean Netherlands',
        display_name: 'Caribbean Netherlands',
        value: 'bq',
        prefix: '599',
    },
    { name: 'Cayman Islands', display_name: 'Cayman Islands', value: 'ky', prefix: '1345' },
    {
        name: 'Central African Republic',
        display_name: 'Central African Republic',
        value: 'cf',
        prefix: '236',
    },
    { name: 'Chad', display_name: 'Chad', value: 'td', prefix: '235' },
    { name: 'Chile', display_name: 'Chile', value: 'cl', prefix: '56' },
    { name: 'China', display_name: 'China', value: 'cn', prefix: '86' },
    { name: 'Christmas Island', display_name: 'Christmas Island', value: 'cx', prefix: '618' },
    {
        name: 'Cocos (Keeling) Islands',
        display_name: 'Cocos (Keeling) Islands',
        value: 'cc',
        prefix: '6189162',
    },
    { name: 'Colombia', display_name: 'Colombia', value: 'co', prefix: '57' },
    { name: 'Comoros', display_name: 'Comoros', value: 'km', prefix: '269' },
    {
        name: 'Congo - Brazzaville',
        display_name: 'Congo - Brazzaville',
        value: 'cg',
        prefix: '242',
    },
    { name: 'Congo - Kinshasa', display_name: 'Congo - Kinshasa', value: 'cd', prefix: '243' },
    { name: 'Cook Islands', display_name: 'Cook Islands', value: 'ck', prefix: '682' },
    { name: 'Costa Rica', display_name: 'Costa Rica', value: 'cr', prefix: '506' },
    { name: "Cote d'Ivoire", display_name: "Cote d'Ivoire", value: 'ci', prefix: '225' },
    { name: 'Croatia', display_name: 'Croatia', value: 'hr', prefix: '385' },
    { name: 'Cuba', display_name: 'Cuba', value: 'cu', prefix: '53' },
    { name: 'Curacao', display_name: 'Curacao', value: 'cw', prefix: '5999' },
    { name: 'Cyprus', display_name: 'Cyprus', value: 'cy', prefix: '357' },
    { name: 'Czech Republic', display_name: 'Czech Republic', value: 'cz', prefix: '420' },
    { name: 'Denmark', display_name: 'Denmark', value: 'dk', prefix: '45' },
    { name: 'Djibouti', display_name: 'Djibouti', value: 'dj', prefix: '253' },
    { name: 'Dominica', display_name: 'Dominica', value: 'dm', prefix: '1767' },
    { name: 'Dominican Republic', display_name: 'Dominican Republic', value: 'do', prefix: '1809' },
    { name: 'Ecuador', display_name: 'Ecuador', value: 'ec', prefix: '593' },
    { name: 'Egypt', display_name: 'Egypt', value: 'eg', prefix: '20' },
    { name: 'El Salvador', display_name: 'El Salvador', value: 'sv', prefix: '503' },
    { name: 'Equatorial Guinea', display_name: 'Equatorial Guinea', value: 'gq', prefix: '240' },
    { name: 'Eritrea', display_name: 'Eritrea', value: 'er', prefix: '291' },
    { name: 'Estonia', display_name: 'Estonia', value: 'ee', prefix: '372' },
    { name: 'Ethiopia', display_name: 'Ethiopia', value: 'et', prefix: '251' },
    { name: 'Falkland Islands', display_name: 'Falkland Islands', value: 'fk', prefix: '500' },
    { name: 'Faroe Islands', display_name: 'Faroe Islands', value: 'fo', prefix: '298' },
    { name: 'Fiji', display_name: 'Fiji', value: 'fj', prefix: '679' },
    { name: 'Finland', display_name: 'Finland', value: 'fi', prefix: '358' },
    { name: 'France', display_name: 'France', value: 'fr', prefix: '33' },
    { name: 'French Guiana', display_name: 'French Guiana', value: 'gf', prefix: '594' },
    { name: 'French Polynesia', display_name: 'French Polynesia', value: 'pf', prefix: '689' },
    {
        name: 'French Southern Territories',
        display_name: 'French Southern Territories',
        value: 'tf',
    },
    { name: 'Gabon', display_name: 'Gabon', value: 'ga', prefix: '241' },
    { name: 'Gambia', display_name: 'Gambia', value: 'gm', prefix: '220' },
    { name: 'Georgia', display_name: 'Georgia', value: 'ge', prefix: '995' },
    { name: 'Germany', display_name: 'Germany', value: 'de', prefix: '49' },
    { name: 'Ghana', display_name: 'Ghana', value: 'gh', prefix: '233' },
    { name: 'Gibraltar', display_name: 'Gibraltar', value: 'gi', prefix: '350' },
    { name: 'Greece', display_name: 'Greece', value: 'gr', prefix: '30' },
    { name: 'Greenland', display_name: 'Greenland', value: 'gl', prefix: '299' },
    { name: 'Grenada', display_name: 'Grenada', value: 'gd', prefix: '1473' },
    { name: 'Guadeloupe', display_name: 'Guadeloupe', value: 'gp', prefix: '590' },
    { name: 'Guam', display_name: 'Guam', value: 'gu', prefix: '671' },
    { name: 'Guatemala', display_name: 'Guatemala', value: 'gt', prefix: '502' },
    { name: 'Guernsey', display_name: 'Guernsey', value: 'gg', prefix: '441481' },
    { name: 'Guinea', display_name: 'Guinea', value: 'gn', prefix: '224' },
    { name: 'Guinea-Bissau', display_name: 'Guinea-Bissau', value: 'gw', prefix: '245' },
    { name: 'Guyana', display_name: 'Guyana', value: 'gy', prefix: '592' },
    { name: 'Haiti', display_name: 'Haiti', value: 'ht', prefix: '509' },
    { name: 'Heard & McDonald Islands', display_name: 'Heard & McDonald Islands', value: 'hm' },
    { name: 'Honduras', display_name: 'Honduras', value: 'hn', prefix: '504' },
    {
        name: 'Hong Kong SAR China',
        display_name: 'Hong Kong SAR China',
        value: 'hk',
        prefix: '852',
    },
    { name: 'Hungary', display_name: 'Hungary', value: 'hu', prefix: '36' },
    { name: 'Iceland', display_name: 'Iceland', value: 'is', prefix: '354' },
    { name: 'India', display_name: 'India', value: 'in', prefix: '91' },
    { name: 'Indonesia', display_name: 'Indonesia', value: 'id', prefix: '62' },
    { name: 'Iran', display_name: 'Iran', value: 'ir', prefix: '98' },
    { name: 'Iraq', display_name: 'Iraq', value: 'iq', prefix: '964' },
    { name: 'Ireland', display_name: 'Ireland', value: 'ie', prefix: '353' },
    { name: 'Isle of Man', display_name: 'Isle of Man', value: 'im', prefix: '44' },
    { name: 'Israel', display_name: 'Israel', value: 'il', prefix: '972' },
    { name: 'Italy', display_name: 'Italy', value: 'it', prefix: '39' },
    { name: 'Jamaica', display_name: 'Jamaica', value: 'jm', prefix: '1876' },
    { name: 'Japan', display_name: 'Japan', value: 'jp', prefix: '81' },
    { name: 'Jersey', display_name: 'Jersey', value: 'je', prefix: '441534' },
    { name: 'Jordan', display_name: 'Jordan', value: 'jo', prefix: '962' },
    { name: 'Kazakhstan', display_name: 'Kazakhstan', value: 'kz', prefix: '7' },
    { name: 'Kenya', display_name: 'Kenya', value: 'ke', prefix: '254' },
    { name: 'Kiribati', display_name: 'Kiribati', value: 'ki', prefix: '686' },
    { name: 'Kuwait', display_name: 'Kuwait', value: 'kw', prefix: '965' },
    { name: 'Kyrgyzstan', display_name: 'Kyrgyzstan', value: 'kg', prefix: '996' },
    { name: 'Laos', display_name: 'Laos', value: 'la', prefix: '856' },
    { name: 'Latvia', display_name: 'Latvia', value: 'lv', prefix: '371' },
    { name: 'Lebanon', display_name: 'Lebanon', value: 'lb', prefix: '961' },
    { name: 'Lesotho', display_name: 'Lesotho', value: 'ls', prefix: '266' },
    { name: 'Liberia', display_name: 'Liberia', value: 'lr', prefix: '231' },
    { name: 'Libya', display_name: 'Libya', value: 'ly', prefix: '218' },
    { name: 'Liechtenstein', display_name: 'Liechtenstein', value: 'li', prefix: '417' },
    { name: 'Lithuania', display_name: 'Lithuania', value: 'lt', prefix: '370' },
    { name: 'Luxembourg', display_name: 'Luxembourg', value: 'lu', prefix: '352' },
    { name: 'Macau SAR China', display_name: 'Macau SAR China', value: 'mo', prefix: '853' },
    { name: 'Macedonia', display_name: 'Macedonia', value: 'mk', prefix: '389' },
    { name: 'Madagascar', display_name: 'Madagascar', value: 'mg', prefix: '261' },
    { name: 'Malawi', display_name: 'Malawi', value: 'mw', prefix: '265' },
    { name: 'Malaysia', display_name: 'Malaysia', value: 'my', prefix: '60' },
    { name: 'Maldives', display_name: 'Maldives', value: 'mv', prefix: '960' },
    { name: 'Mali', display_name: 'Mali', value: 'ml', prefix: '223' },
    { name: 'Malta', display_name: 'Malta', value: 'mt', prefix: '356' },
    { name: 'Marshall Islands', display_name: 'Marshall Islands', value: 'mh', prefix: '692' },
    { name: 'Martinique', display_name: 'Martinique', value: 'mq', prefix: '596' },
    { name: 'Mauritania', display_name: 'Mauritania', value: 'mr', prefix: '222' },
    { name: 'Mauritius', display_name: 'Mauritius', value: 'mu', prefix: '230' },
    { name: 'Mayotte', display_name: 'Mayotte', value: 'yt', prefix: '262269' },
    { name: 'Mexico', display_name: 'Mexico', value: 'mx', prefix: '52' },
    { name: 'Micronesia', display_name: 'Micronesia', value: 'fm', prefix: '691' },
    { name: 'Moldova', display_name: 'Moldova', value: 'md', prefix: '373' },
    { name: 'Monaco', display_name: 'Monaco', value: 'mc', prefix: '377' },
    { name: 'Mongolia', display_name: 'Mongolia', value: 'mn', prefix: '976' },
    { name: 'Montenegro', display_name: 'Montenegro', value: 'me', prefix: '382' },
    { name: 'Montserrat', display_name: 'Montserrat', value: 'ms', prefix: '1664' },
    { name: 'Morocco', display_name: 'Morocco', value: 'ma', prefix: '212' },
    { name: 'Mozambique', display_name: 'Mozambique', value: 'mz', prefix: '258' },
    { name: 'Myanmar (Burma)', display_name: 'Myanmar (Burma)', value: 'mm', prefix: '95' },
    { name: 'Namibia', display_name: 'Namibia', value: 'na', prefix: '264' },
    { name: 'Nauru', display_name: 'Nauru', value: 'nr', prefix: '674' },
    { name: 'Nepal', display_name: 'Nepal', value: 'np', prefix: '977' },
    { name: 'Netherlands', display_name: 'Netherlands', value: 'nl', prefix: '31' },
    { name: 'New Caledonia', display_name: 'New Caledonia', value: 'nc', prefix: '687' },
    { name: 'New Zealand', display_name: 'New Zealand', value: 'nz', prefix: '64' },
    { name: 'Nicaragua', display_name: 'Nicaragua', value: 'ni', prefix: '505' },
    { name: 'Niger', display_name: 'Niger', value: 'ne', prefix: '227' },
    { name: 'Nigeria', display_name: 'Nigeria', value: 'ng', prefix: '234' },
    { name: 'Niue', display_name: 'Niue', value: 'nu', prefix: '683' },
    { name: 'Norfolk Island', display_name: 'Norfolk Island', value: 'nf', prefix: '6723' },
    { name: 'North Korea', display_name: 'North Korea', value: 'kp', prefix: '850' },
    {
        name: 'Northern Mariana Islands',
        display_name: 'Northern Mariana Islands',
        value: 'mp',
        prefix: '1670',
    },
    { name: 'Norway', display_name: 'Norway', value: 'no', prefix: '47' },
    { name: 'Oman', display_name: 'Oman', value: 'om', prefix: '968' },
    { name: 'Pakistan', display_name: 'Pakistan', value: 'pk', prefix: '92' },
    { name: 'Palau', display_name: 'Palau', value: 'pw', prefix: '680' },
    {
        name: 'Palestinian Territories',
        display_name: 'Palestinian Territories',
        value: 'ps',
        prefix: '970',
    },
    { name: 'Panama', display_name: 'Panama', value: 'pa', prefix: '507' },
    { name: 'Papua New Guinea', display_name: 'Papua New Guinea', value: 'pg', prefix: '675' },
    { name: 'Paraguay', display_name: 'Paraguay', value: 'py', prefix: '595' },
    { name: 'Peru', display_name: 'Peru', value: 'pe', prefix: '51' },
    { name: 'Philippines', display_name: 'Philippines', value: 'ph', prefix: '63' },
    { name: 'Pitcairn Islands', display_name: 'Pitcairn Islands', value: 'pn', prefix: '649' },
    { name: 'Poland', display_name: 'Poland', value: 'pl', prefix: '48' },
    { name: 'Portugal', display_name: 'Portugal', value: 'pt', prefix: '351' },
    { name: 'Puerto Rico', display_name: 'Puerto Rico', value: 'pr', prefix: '1787' },
    { name: 'Qatar', display_name: 'Qatar', value: 'qa', prefix: '974' },
    { name: 'Reunion', display_name: 'Reunion', value: 're', prefix: '262' },
    { name: 'Romania', display_name: 'Romania', value: 'ro', prefix: '40' },
    { name: 'Russia', display_name: 'Russia', value: 'ru', prefix: '7' },
    { name: 'Rwanda', display_name: 'Rwanda', value: 'rw', prefix: '250' },
    { name: 'Saint Barthelemy', display_name: 'Saint Barthelemy', value: 'bl', prefix: '590' },
    { name: 'Saint Helena', display_name: 'Saint Helena', value: 'sh', prefix: '290' },
    {
        name: 'Saint Kitts and Nevis',
        display_name: 'Saint Kitts and Nevis',
        value: 'kn',
        prefix: '1869',
    },
    { name: 'Saint Lucia', display_name: 'Saint Lucia', value: 'lc', prefix: '1758' },
    { name: 'Saint Martin', display_name: 'Saint Martin', value: 'mf', prefix: '590' },
    {
        name: 'Saint Pierre and Miquelon',
        display_name: 'Saint Pierre and Miquelon',
        value: 'pm',
        prefix: '508',
    },
    { name: 'Samoa', display_name: 'Samoa', value: 'ws', prefix: '685' },
    { name: 'San Marino', display_name: 'San Marino', value: 'sm', prefix: '378' },
    {
        name: 'Sao Tome and Principe',
        display_name: 'Sao Tome and Principe',
        value: 'st',
        prefix: '239',
    },
    { name: 'Saudi Arabia', display_name: 'Saudi Arabia', value: 'sa', prefix: '966' },
    { name: 'Senegal', display_name: 'Senegal', value: 'sn', prefix: '221' },
    { name: 'Serbia', display_name: 'Serbia', value: 'rs', prefix: '381' },
    { name: 'Seychelles', display_name: 'Seychelles', value: 'sc', prefix: '248' },
    { name: 'Sierra Leone', display_name: 'Sierra Leone', value: 'sl', prefix: '232' },
    { name: 'Singapore', display_name: 'Singapore', value: 'sg', prefix: '65' },
    { name: 'Sint Maarten', display_name: 'Sint Maarten', value: 'sx', prefix: '1721' },
    { name: 'Slovakia', display_name: 'Slovakia', value: 'sk', prefix: '421' },
    { name: 'Slovenia', display_name: 'Slovenia', value: 'si', prefix: '386' },
    { name: 'Solomon Islands', display_name: 'Solomon Islands', value: 'sb', prefix: '677' },
    { name: 'Somalia', display_name: 'Somalia', value: 'so', prefix: '252' },
    { name: 'South Africa', display_name: 'South Africa', value: 'za', prefix: '27' },
    {
        name: 'South Georgia & South Sandwich Islands',
        display_name: 'South Georgia & South Sandwich Islands',
        value: 'gs',
        prefix: '500',
    },
    { name: 'South Korea', display_name: 'South Korea', value: 'kr', prefix: '82' },
    { name: 'South Sudan', display_name: 'South Sudan', value: 'ss', prefix: '211' },
    { name: 'Spain', display_name: 'Spain', value: 'es', prefix: '34' },
    { name: 'Sri Lanka', display_name: 'Sri Lanka', value: 'lk', prefix: '94' },
    {
        name: 'St. Vincent & Grenadines',
        display_name: 'St. Vincent & Grenadines',
        value: 'vc',
        prefix: '1784',
    },
    { name: 'Sudan', display_name: 'Sudan', value: 'sd', prefix: '249' },
    { name: 'Suriname', display_name: 'Suriname', value: 'sr', prefix: '597' },
    {
        name: 'Svalbard and Jan Mayen',
        display_name: 'Svalbard and Jan Mayen',
        value: 'sj',
        prefix: '4779',
    },
    { name: 'Swaziland', display_name: 'Swaziland', value: 'sz', prefix: '268' },
    { name: 'Sweden', display_name: 'Sweden', value: 'se', prefix: '46' },
    { name: 'Switzerland', display_name: 'Switzerland', value: 'ch', prefix: '41' },
    { name: 'Syria', display_name: 'Syria', value: 'sy', prefix: '963' },
    { name: 'Taiwan', display_name: 'Taiwan', value: 'tw', prefix: '886' },
    { name: 'Tajikistan', display_name: 'Tajikistan', value: 'tj', prefix: '992' },
    { name: 'Tanzania', display_name: 'Tanzania', value: 'tz', prefix: '255' },
    { name: 'Thailand', display_name: 'Thailand', value: 'th', prefix: '66' },
    { name: 'Timor-Leste', display_name: 'Timor-Leste', value: 'tl', prefix: '670' },
    { name: 'Togo', display_name: 'Togo', value: 'tg', prefix: '228' },
    { name: 'Tokelau', display_name: 'Tokelau', value: 'tk', prefix: '690' },
    { name: 'Tonga', display_name: 'Tonga', value: 'to', prefix: '676' },
    {
        name: 'Trinidad and Tobago',
        display_name: 'Trinidad and Tobago',
        value: 'tt',
        prefix: '1868',
    },
    { name: 'Tunisia', display_name: 'Tunisia', value: 'tn', prefix: '216' },
    { name: 'Turkey', display_name: 'Turkey', value: 'tr', prefix: '90' },
    { name: 'Turkmenistan', display_name: 'Turkmenistan', value: 'tm', prefix: '993' },
    {
        name: 'Turks and Caicos Islands',
        display_name: 'Turks and Caicos Islands',
        value: 'tc',
        prefix: '1649',
    },
    { name: 'Tuvalu', display_name: 'Tuvalu', value: 'tv', prefix: '688' },
    { name: 'U.S. Outlying Islands', display_name: 'U.S. Outlying Islands', value: 'um' },
    {
        name: 'U.S. Virgin Islands',
        display_name: 'U.S. Virgin Islands',
        value: 'vi',
        prefix: '1340',
    },
    { name: 'Uganda', display_name: 'Uganda', value: 'ug', prefix: '256' },
    { name: 'Ukraine', display_name: 'Ukraine', value: 'ua', prefix: '380' },
    {
        name: 'United Arab Emirates',
        display_name: 'United Arab Emirates',
        value: 'ae',
        prefix: '971',
    },
    { name: 'United Kingdom', display_name: 'United Kingdom', value: 'gb', prefix: '44' },
    { name: 'United States', display_name: 'United States', value: 'us', prefix: '1' },
    { name: 'Uruguay', display_name: 'Uruguay', value: 'uy', prefix: '598' },
    { name: 'Uzbekistan', display_name: 'Uzbekistan', value: 'uz', prefix: '998' },
    { name: 'Vanuatu', display_name: 'Vanuatu', value: 'vu', prefix: '678' },
    { name: 'Vatican City', display_name: 'Vatican City', value: 'va', prefix: '379' },
    { name: 'Venezuela', display_name: 'Venezuela', value: 've', prefix: '58' },
    { name: 'Vietnam', display_name: 'Vietnam', value: 'vn', prefix: '84' },
    { name: 'Wallis and Futuna', display_name: 'Wallis and Futuna', value: 'wf', prefix: '681' },
    { name: 'Western Sahara', display_name: 'Western Sahara', value: 'eh', prefix: '21' },
    { name: 'Yemen', display_name: 'Yemen', value: 'ye', prefix: '967' },
    { name: 'Zambia', display_name: 'Zambia', value: 'zm', prefix: '260' },
    { name: 'Zimbabwe', display_name: 'Zimbabwe', value: 'zw', prefix: '263' },
]

export default residence_list
