export const percentToDecimal = (percentStr) => {
    return parseFloat(percentStr) / 100
}

interface SwiperOption {
    spaceBetween: number
    slidesPerView: number | 'auto'
    reverseDirection: true
    freeMode: true
}

export const swiperOption: SwiperOption = {
    spaceBetween: 16,
    slidesPerView: 'auto',
    reverseDirection: true,
    freeMode: true,
}

export const initialLiveMarketData = {
    com: {
        WTI_OIL: {
            ask: 71.945,
            bid: 71.909,
            chng: '0%',
            code: 'WTI_OIL',
            mid: 71.927,
            mkt: 'commodities',
            ord: 5,
            reg: 'row',
            sprd: 0.035,
            sym: 'West Texas Intermediate',
        },
        XAGUSD: {
            ask: 23.04,
            bid: 23.019,
            chng: '0%',
            code: 'XAGUSD',
            mid: 23.029,
            mkt: 'commodities',
            ord: 2,
            reg: 'row',
            sprd: 0.022,
            sym: 'Silver/USD',
        },
        XAUUSD: {
            ask: 1998.97,
            bid: 1998.68,
            chng: '0%',
            code: 'XAUUSD',
            mid: 1998.82,
            mkt: 'commodities',
            ord: 1,
            reg: 'row',
            sprd: 0.3,
            sym: 'Gold/USD',
        },
        XCUUSD: {
            ask: 8418.15,
            bid: 8411.34,
            chng: '0%',
            code: 'XCUUSD',
            mid: 8414.74,
            mkt: 'commodities',
            ord: 4,
            reg: 'row',
            sprd: 6.81,
            sym: 'Copper/USD',
        },
        XPDUSD: {
            ask: 945.05,
            bid: 939.25,
            chng: '0%',
            code: 'XPDUSD',
            mid: 942.15,
            mkt: 'commodities',
            ord: 3,
            reg: 'row',
            sprd: 5.8,
            sym: 'Palladium/USD',
        },
    },
    cry: {
        ADAUSD: {
            ask: 0.55553,
            bid: 0.55458,
            chng: '-6.7%',
            code: 'ADAUSD',
            mid: 0.55505,
            mkt: 'cryptocurrency',
            ord: 5,
            reg: 'row',
            sprd: 0.00094,
            sym: 'ADA/USD',
        },
        BTCUSD: {
            ask: 42033.801,
            bid: 41998.558,
            chng: '-4.1%',
            code: 'BTCUSD',
            mid: 42016.179,
            mkt: 'cryptocurrency',
            ord: 1,
            reg: 'row',
            sprd: 35.243,
            sym: 'BTC/USD',
        },
        DOGUSD: {
            ask: 0.09884,
            bid: 0.09865,
            chng: '-3.17%',
            code: 'DOGUSD',
            mid: 0.09874,
            mkt: 'cryptocurrency',
            ord: 4,
            reg: 'row',
            sprd: 0.0002,
            sym: 'DOG/USD',
        },
        DSHUSD: {
            ask: 32.974,
            bid: 32.919,
            chng: '0%',
            code: 'DSHUSD',
            mid: 32.946,
            mkt: 'cryptocurrency',
            ord: 3,
            reg: 'row',
            sprd: 0.055,
            sym: 'DSH/USD',
        },
        ETHUSD: {
            ask: 2249.0848,
            bid: 2246.8532,
            chng: '0%',
            code: 'ETHUSD',
            mid: 2247.969,
            mkt: 'cryptocurrency',
            ord: 2,
            reg: 'row',
            sprd: 2.23159,
            sym: 'ETH/USD',
        },
    },
    der: {
        Crash_1000_Index: {
            ask: 6348.5825,
            bid: 6348.2005,
            chng: '-0.39%',
            code: 'Crash_1000_Index',
            mid: 6348.3915,
            mkt: 'derived',
            ord: 2,
            reg: 'row',
            sprd: 0.3821,
            sym: 'Crash 1000 Index',
        },
        EURUSD_DFX_10_Index: {
            ask: 74282.21,
            bid: 74273.12,
            chng: '+0.07%',
            code: 'EURUSD_DFX_10_Index',
            mid: 74277.66,
            mkt: 'derived',
            ord: 3,
            reg: 'row',
            sprd: 9.09,
            sym: 'EUR/USD DFX 10 Index',
        },
        Jump_50_Index: {
            ask: 31954.63,
            bid: 31945.86,
            chng: '+0.08%',
            code: 'Jump_50_Index',
            mid: 31950.24,
            mkt: 'derived',
            ord: 4,
            reg: 'row',
            sprd: 8.78,
            sym: 'Jump 50 Index',
        },
        Range_Break_200_Index: {
            ask: 105475.5,
            bid: 105473.5,
            chng: '+0.5%',
            code: 'Range_Break_200_Index',
            mid: 105474.5,
            mkt: 'derived',
            ord: 5,
            reg: 'row',
            sprd: 2.1,
            sym: 'Range Break 200 Index',
        },
        Volatility_75_Index: {
            ask: 374905.45,
            bid: 374005.45,
            chng: '+3.82%',
            code: 'Volatility_75_Index',
            mid: 374455.45,
            mkt: 'derived',
            ord: 1,
            reg: 'row',
            sprd: 900.01,
            sym: 'Volatility 75 Index',
        },
    },
    etfs: {
        EEM_US: {
            ask: 39.07,
            bid: 38.96,
            chng: '0%',
            code: 'EEM_US',
            mid: 39.01,
            mkt: 'etfs',
            ord: 3,
            reg: 'row',
            sprd: 0.12,
            sym: 'MSCI Emerging Markets (EEM)',
        },
        GDX_US: {
            ask: 29.73,
            bid: 29.62,
            chng: '0%',
            code: 'GDX_US',
            mid: 29.67,
            mkt: 'etfs',
            ord: 2,
            reg: 'row',
            sprd: 0.11,
            sym: 'Gold Miners (GDX)',
        },
        SPY_US: {
            ask: 460.5,
            bid: 460.25,
            chng: '0%',
            code: 'SPY_US',
            mid: 460.37,
            mkt: 'etfs',
            ord: 1,
            reg: 'row',
            sprd: 0.25,
            sym: 'SPDR S&P 500 (SPY)',
        },
        UNG_US: {
            ask: 5.11,
            bid: 5,
            chng: '0%',
            code: 'UNG_US',
            mid: 5.05,
            mkt: 'etfs',
            ord: 4,
            reg: 'row',
            sprd: 0.11,
            sym: 'US Natural Gas (UNG)',
        },
        XLK_US: {
            ask: 186.78,
            bid: 186.63,
            chng: '0%',
            code: 'XLK_US',
            mid: 186.7,
            mkt: 'etfs',
            ord: 5,
            reg: 'row',
            sprd: 0.15,
            sym: 'Tech Select Sector SPDR (XLK)',
        },
    },
    fx: {
        AUDUSD: {
            ask: 0.65586,
            bid: 0.65581,
            chng: '-0.32%',
            code: 'AUDUSD',
            mid: 0.65583,
            mkt: 'forex',
            ord: 4,
            reg: 'row',
            sprd: 0.00004,
            sym: 'AUD/USD',
        },
        EURUSD: {
            ask: 1.07669,
            bid: 1.07664,
            chng: '0%',
            code: 'EURUSD',
            mid: 1.07666,
            mkt: 'forex',
            ord: 1,
            reg: 'row',
            sprd: 0.00005,
            sym: 'EUR/USD',
        },
        GBPJPY: {
            ask: 182.582,
            bid: 182.565,
            chng: '0%',
            code: 'GBPJPY',
            mid: 182.573,
            mkt: 'forex',
            ord: 3,
            reg: 'row',
            sprd: 0.016,
            sym: 'GBP/JPY',
        },
        GBPUSD: {
            ask: 1.25414,
            bid: 1.25409,
            chng: '0%',
            code: 'GBPUSD',
            mid: 1.25411,
            mkt: 'forex',
            ord: 2,
            reg: 'row',
            sprd: 0.00005,
            sym: 'GBP/USD',
        },
        USDCAD: {
            ask: 1.35975,
            bid: 1.35963,
            chng: '0%',
            code: 'USDCAD',
            mid: 1.35969,
            mkt: 'forex',
            ord: 5,
            reg: 'row',
            sprd: 0.00012,
            sym: 'USD/CAD',
        },
    },
    ind: {
        US_100: {
            ask: 16050.23,
            bid: 16048.77,
            chng: '0%',
            code: 'US_100',
            mid: 16049.5,
            mkt: 'indices',
            ord: 5,
            reg: 'row',
            sprd: 1.46,
            sym: 'US Tech 100',
        },
        US_30: {
            ask: 36302.65,
            bid: 36299.15,
            chng: '0%',
            code: 'US_30',
            mid: 36300.9,
            mkt: 'indices',
            ord: 4,
            reg: 'row',
            sprd: 3.5,
            sym: 'Wall Street 30',
        },
    },
    stk: {
        AAPL: {
            ask: 196.13,
            bid: 195.54,
            chng: '+0.86%',
            code: 'AAPL',
            mid: 195.83,
            mkt: 'stocks',
            ord: 1,
            reg: 'row',
            sprd: 0.59,
            sym: 'Apple (APPL)',
        },
        DIS: {
            ask: 93.14,
            bid: 92.51,
            chng: '+0.56%',
            code: 'DIS',
            mid: 92.82,
            mkt: 'stocks',
            ord: 2,
            reg: 'row',
            sprd: 0.64,
            sym: 'Walt Disney Co (DIS)',
        },
        TSLA: {
            ask: 244.25,
            bid: 243.13,
            chng: '0%',
            code: 'TSLA',
            mid: 243.69,
            mkt: 'stocks',
            ord: 3,
            reg: 'row',
            sprd: 1.13,
            sym: 'Tesla (TSLA)',
        },
    },
}
