const residence_list = [
    { name: 'Afghanistan', display_name: 'Afghanistan', value: 'af' },
    { name: 'Aland Islands', display_name: 'Aland Islands', value: 'ax' },
    { name: 'Albania', display_name: 'Albania', value: 'al' },
    { name: 'Algeria', display_name: 'Algeria', value: 'dz' },
    { name: 'American Samoa', display_name: 'American Samoa', value: 'as' },
    { name: 'Andorra', display_name: 'Andorra', value: 'ad' },
    { name: 'Angola', display_name: 'Angola', value: 'ao' },
    { name: 'Anguilla', display_name: 'Anguilla', value: 'ai' },
    { name: 'Antarctica', display_name: 'Antarctica', value: 'aq' },
    { name: 'Antigua and Barbuda', display_name: 'Antigua and Barbuda', value: 'ag' },
    { name: 'Argentina', display_name: 'Argentina', value: 'ar' },
    { name: 'Armenia', display_name: 'Armenia', value: 'am' },
    { name: 'Aruba', display_name: 'Aruba', value: 'aw' },
    { name: 'Australia', display_name: 'Australia', value: 'au' },
    { name: 'Austria', display_name: 'Austria', value: 'at' },
    { name: 'Azerbaijan', display_name: 'Azerbaijan', value: 'az' },
    { name: 'Bahamas', display_name: 'Bahamas', value: 'bs' },
    { name: 'Bahrain', display_name: 'Bahrain', value: 'bh' },
    { name: 'Bangladesh', display_name: 'Bangladesh', value: 'bd' },
    { name: 'Barbados', display_name: 'Barbados', value: 'bb' },
    { name: 'Belarus', display_name: 'Belarus', value: 'by' },
    { name: 'Belgium', display_name: 'Belgium', value: 'be' },
    { name: 'Belize', display_name: 'Belize', value: 'bz' },
    { name: 'Benin', display_name: 'Benin', value: 'bj' },
    { name: 'Bermuda', display_name: 'Bermuda', value: 'bm' },
    { name: 'Bhutan', display_name: 'Bhutan', value: 'bt' },
    { name: 'Bolivia', display_name: 'Bolivia', value: 'bo' },
    { name: 'Bosnia and Herzegovina', display_name: 'Bosnia and Herzegovina', value: 'ba' },
    { name: 'Botswana', display_name: 'Botswana', value: 'bw' },
    { name: 'Bouvet Island', display_name: 'Bouvet Island', value: 'bv' },
    { name: 'Brazil', display_name: 'Brazil', value: 'br' },
    {
        name: 'British Indian Ocean Territory',
        display_name: 'British Indian Ocean Territory',
        value: 'io',
    },
    { name: 'British Virgin Islands', display_name: 'British Virgin Islands', value: 'vg' },
    { name: 'Brunei', display_name: 'Brunei', value: 'bn' },
    { name: 'Bulgaria', display_name: 'Bulgaria', value: 'bg' },
    { name: 'Burkina Faso', display_name: 'Burkina Faso', value: 'bf' },
    { name: 'Burundi', display_name: 'Burundi', value: 'bi' },
    { name: 'Cambodia', display_name: 'Cambodia', value: 'kh' },
    { name: 'Cameroon', display_name: 'Cameroon', value: 'cm' },
    { name: 'Canada', display_name: 'Canada', value: 'ca' },
    { name: 'Cape Verde', display_name: 'Cape Verde', value: 'cv' },
    { name: 'Caribbean Netherlands', display_name: 'Caribbean Netherlands', value: 'bq' },
    { name: 'Cayman Islands', display_name: 'Cayman Islands', value: 'ky' },
    { name: 'Central African Republic', display_name: 'Central African Republic', value: 'cf' },
    { name: 'Chad', display_name: 'Chad', value: 'td' },
    { name: 'Chile', display_name: 'Chile', value: 'cl' },
    { name: 'China', display_name: 'China', value: 'cn' },
    { name: 'Christmas Island', display_name: 'Christmas Island', value: 'cx' },
    { name: 'Cocos (Keeling) Islands', display_name: 'Cocos (Keeling) Islands', value: 'cc' },
    { name: 'Colombia', display_name: 'Colombia', value: 'co' },
    { name: 'Comoros', display_name: 'Comoros', value: 'km' },
    { name: 'Congo - Brazzaville', display_name: 'Congo - Brazzaville', value: 'cg' },
    { name: 'Congo - Kinshasa', display_name: 'Congo - Kinshasa', value: 'cd' },
    { name: 'Cook Islands', display_name: 'Cook Islands', value: 'ck' },
    { name: 'Costa Rica', display_name: 'Costa Rica', value: 'cr' },
    { name: "Cote d'Ivoire", display_name: "Cote d'Ivoire", value: 'ci' },
    { name: 'Croatia', display_name: 'Croatia', value: 'hr' },
    { name: 'Cuba', display_name: 'Cuba', value: 'cu' },
    { name: 'Curacao', display_name: 'Curacao', value: 'cw' },
    { name: 'Cyprus', display_name: 'Cyprus', value: 'cy' },
    { name: 'Czech Republic', display_name: 'Czech Republic', value: 'cz' },
    { name: 'Denmark', display_name: 'Denmark', value: 'dk' },
    { name: 'Djibouti', display_name: 'Djibouti', value: 'dj' },
    { name: 'Dominica', display_name: 'Dominica', value: 'dm' },
    { name: 'Dominican Republic', display_name: 'Dominican Republic', value: 'do' },
    { name: 'Ecuador', display_name: 'Ecuador', value: 'ec' },
    { name: 'Egypt', display_name: 'Egypt', value: 'eg' },
    { name: 'El Salvador', display_name: 'El Salvador', value: 'sv' },
    { name: 'Equatorial Guinea', display_name: 'Equatorial Guinea', value: 'gq' },
    { name: 'Eritrea', display_name: 'Eritrea', value: 'er' },
    { name: 'Estonia', display_name: 'Estonia', value: 'ee' },
    { name: 'Ethiopia', display_name: 'Ethiopia', value: 'et' },
    { name: 'Falkland Islands', display_name: 'Falkland Islands', value: 'fk' },
    { name: 'Faroe Islands', display_name: 'Faroe Islands', value: 'fo' },
    { name: 'Fiji', display_name: 'Fiji', value: 'fj' },
    { name: 'Finland', display_name: 'Finland', value: 'fi' },
    { name: 'France', display_name: 'France', value: 'fr' },
    { name: 'French Guiana', display_name: 'French Guiana', value: 'gf' },
    { name: 'French Polynesia', display_name: 'French Polynesia', value: 'pf' },
    {
        name: 'French Southern Territories',
        display_name: 'French Southern Territories',
        value: 'tf',
    },
    { name: 'Gabon', display_name: 'Gabon', value: 'ga' },
    { name: 'Gambia', display_name: 'Gambia', value: 'gm' },
    { name: 'Georgia', display_name: 'Georgia', value: 'ge' },
    { name: 'Germany', display_name: 'Germany', value: 'de' },
    { name: 'Ghana', display_name: 'Ghana', value: 'gh' },
    { name: 'Gibraltar', display_name: 'Gibraltar', value: 'gi' },
    { name: 'Greece', display_name: 'Greece', value: 'gr' },
    { name: 'Greenland', display_name: 'Greenland', value: 'gl' },
    { name: 'Grenada', display_name: 'Grenada', value: 'gd' },
    { name: 'Guadeloupe', display_name: 'Guadeloupe', value: 'gp' },
    { name: 'Guam', display_name: 'Guam', value: 'gu' },
    { name: 'Guatemala', display_name: 'Guatemala', value: 'gt' },
    { name: 'Guernsey', display_name: 'Guernsey', value: 'gg' },
    { name: 'Guinea', display_name: 'Guinea', value: 'gn' },
    { name: 'Guinea-Bissau', display_name: 'Guinea-Bissau', value: 'gw' },
    { name: 'Guyana', display_name: 'Guyana', value: 'gy' },
    { name: 'Haiti', display_name: 'Haiti', value: 'ht' },
    { name: 'Heard & McDonald Islands', display_name: 'Heard & McDonald Islands', value: 'hm' },
    { name: 'Honduras', display_name: 'Honduras', value: 'hn' },
    { name: 'Hong Kong SAR China', display_name: 'Hong Kong SAR China', value: 'hk' },
    { name: 'Hungary', display_name: 'Hungary', value: 'hu' },
    { name: 'Iceland', display_name: 'Iceland', value: 'is' },
    { name: 'India', display_name: 'India', value: 'in' },
    { name: 'Indonesia', display_name: 'Indonesia', value: 'id' },
    { name: 'Iran', display_name: 'Iran', value: 'ir' },
    { name: 'Iraq', display_name: 'Iraq', value: 'iq' },
    { name: 'Ireland', display_name: 'Ireland', value: 'ie' },
    { name: 'Isle of Man', display_name: 'Isle of Man', value: 'im' },
    { name: 'Israel', display_name: 'Israel', value: 'il' },
    { name: 'Italy', display_name: 'Italy', value: 'it' },
    { name: 'Jamaica', display_name: 'Jamaica', value: 'jm' },
    { name: 'Japan', display_name: 'Japan', value: 'jp' },
    { name: 'Jersey', display_name: 'Jersey', value: 'je' },
    { name: 'Jordan', display_name: 'Jordan', value: 'jo' },
    { name: 'Kazakhstan', display_name: 'Kazakhstan', value: 'kz' },
    { name: 'Kenya', display_name: 'Kenya', value: 'ke' },
    { name: 'Kiribati', display_name: 'Kiribati', value: 'ki' },
    { name: 'Kuwait', display_name: 'Kuwait', value: 'kw' },
    { name: 'Kyrgyzstan', display_name: 'Kyrgyzstan', value: 'kg' },
    { name: 'Laos', display_name: 'Laos', value: 'la' },
    { name: 'Latvia', display_name: 'Latvia', value: 'lv' },
    { name: 'Lebanon', display_name: 'Lebanon', value: 'lb' },
    { name: 'Lesotho', display_name: 'Lesotho', value: 'ls' },
    { name: 'Liberia', display_name: 'Liberia', value: 'lr' },
    { name: 'Libya', display_name: 'Libya', value: 'ly' },
    { name: 'Liechtenstein', display_name: 'Liechtenstein', value: 'li' },
    { name: 'Lithuania', display_name: 'Lithuania', value: 'lt' },
    { name: 'Luxembourg', display_name: 'Luxembourg', value: 'lu' },
    { name: 'Macau SAR China', display_name: 'Macau SAR China', value: 'mo' },
    { name: 'Macedonia', display_name: 'Macedonia', value: 'mk' },
    { name: 'Madagascar', display_name: 'Madagascar', value: 'mg' },
    { name: 'Malawi', display_name: 'Malawi', value: 'mw' },
    { name: 'Malaysia', display_name: 'Malaysia', value: 'my' },
    { name: 'Maldives', display_name: 'Maldives', value: 'mv' },
    { name: 'Mali', display_name: 'Mali', value: 'ml' },
    { name: 'Malta', display_name: 'Malta', value: 'mt' },
    { name: 'Marshall Islands', display_name: 'Marshall Islands', value: 'mh' },
    { name: 'Martinique', display_name: 'Martinique', value: 'mq' },
    { name: 'Mauritania', display_name: 'Mauritania', value: 'mr' },
    { name: 'Mauritius', display_name: 'Mauritius', value: 'mu' },
    { name: 'Mayotte', display_name: 'Mayotte', value: 'yt' },
    { name: 'Mexico', display_name: 'Mexico', value: 'mx' },
    { name: 'Micronesia', display_name: 'Micronesia', value: 'fm' },
    { name: 'Moldova', display_name: 'Moldova', value: 'md' },
    { name: 'Monaco', display_name: 'Monaco', value: 'mc' },
    { name: 'Mongolia', display_name: 'Mongolia', value: 'mn' },
    { name: 'Montenegro', display_name: 'Montenegro', value: 'me' },
    { name: 'Montserrat', display_name: 'Montserrat', value: 'ms' },
    { name: 'Morocco', display_name: 'Morocco', value: 'ma' },
    { name: 'Mozambique', display_name: 'Mozambique', value: 'mz' },
    { name: 'Myanmar (Burma)', display_name: 'Myanmar (Burma)', value: 'mm' },
    { name: 'Namibia', display_name: 'Namibia', value: 'na' },
    { name: 'Nauru', display_name: 'Nauru', value: 'nr' },
    { name: 'Nepal', display_name: 'Nepal', value: 'np' },
    { name: 'Netherlands', display_name: 'Netherlands', value: 'nl' },
    { name: 'New Caledonia', display_name: 'New Caledonia', value: 'nc' },
    { name: 'New Zealand', display_name: 'New Zealand', value: 'nz' },
    { name: 'Nicaragua', display_name: 'Nicaragua', value: 'ni' },
    { name: 'Niger', display_name: 'Niger', value: 'ne' },
    { name: 'Nigeria', display_name: 'Nigeria', value: 'ng' },
    { name: 'Niue', display_name: 'Niue', value: 'nu' },
    { name: 'Norfolk Island', display_name: 'Norfolk Island', value: 'nf' },
    { name: 'North Korea', display_name: 'North Korea', value: 'kp' },
    { name: 'Northern Mariana Islands', display_name: 'Northern Mariana Islands', value: 'mp' },
    { name: 'Norway', display_name: 'Norway', value: 'no' },
    { name: 'Oman', display_name: 'Oman', value: 'om' },
    { name: 'Pakistan', display_name: 'Pakistan', value: 'pk' },
    { name: 'Palau', display_name: 'Palau', value: 'pw' },
    { name: 'Palestinian Territories', display_name: 'Palestinian Territories', value: 'ps' },
    { name: 'Panama', display_name: 'Panama', value: 'pa' },
    { name: 'Papua New Guinea', display_name: 'Papua New Guinea', value: 'pg' },
    { name: 'Paraguay', display_name: 'Paraguay', value: 'py' },
    { name: 'Peru', display_name: 'Peru', value: 'pe' },
    { name: 'Philippines', display_name: 'Philippines', value: 'ph' },
    { name: 'Pitcairn Islands', display_name: 'Pitcairn Islands', value: 'pn' },
    { name: 'Poland', display_name: 'Poland', value: 'pl' },
    { name: 'Portugal', display_name: 'Portugal', value: 'pt' },
    { name: 'Puerto Rico', display_name: 'Puerto Rico', value: 'pr' },
    { name: 'Qatar', display_name: 'Qatar', value: 'qa' },
    { name: 'Reunion', display_name: 'Reunion', value: 're' },
    { name: 'Romania', display_name: 'Romania', value: 'ro' },
    { name: 'Russia', display_name: 'Russia', value: 'ru' },
    { name: 'Rwanda', display_name: 'Rwanda', value: 'rw' },
    { name: 'Saint Barthelemy', display_name: 'Saint Barthelemy', value: 'bl' },
    { name: 'Saint Helena', display_name: 'Saint Helena', value: 'sh' },
    { name: 'Saint Kitts and Nevis', display_name: 'Saint Kitts and Nevis', value: 'kn' },
    { name: 'Saint Lucia', display_name: 'Saint Lucia', value: 'lc' },
    { name: 'Saint Martin', display_name: 'Saint Martin', value: 'mf' },
    { name: 'Saint Pierre and Miquelon', display_name: 'Saint Pierre and Miquelon', value: 'pm' },
    { name: 'Samoa', display_name: 'Samoa', value: 'ws' },
    { name: 'San Marino', display_name: 'San Marino', value: 'sm' },
    { name: 'Sao Tome and Principe', display_name: 'Sao Tome and Principe', value: 'st' },
    { name: 'Saudi Arabia', display_name: 'Saudi Arabia', value: 'sa' },
    { name: 'Senegal', display_name: 'Senegal', value: 'sn' },
    { name: 'Serbia', display_name: 'Serbia', value: 'rs' },
    { name: 'Seychelles', display_name: 'Seychelles', value: 'sc' },
    { name: 'Sierra Leone', display_name: 'Sierra Leone', value: 'sl' },
    { name: 'Singapore', display_name: 'Singapore', value: 'sg' },
    { name: 'Sint Maarten', display_name: 'Sint Maarten', value: 'sx' },
    { name: 'Slovakia', display_name: 'Slovakia', value: 'sk' },
    { name: 'Slovenia', display_name: 'Slovenia', value: 'si' },
    { name: 'Solomon Islands', display_name: 'Solomon Islands', value: 'sb' },
    { name: 'Somalia', display_name: 'Somalia', value: 'so' },
    { name: 'South Africa', display_name: 'South Africa', value: 'za' },
    {
        name: 'South Georgia & South Sandwich Islands',
        display_name: 'South Georgia & South Sandwich Islands',
        value: 'gs',
    },
    { name: 'South Korea', display_name: 'South Korea', value: 'kr' },
    { name: 'South Sudan', display_name: 'South Sudan', value: 'ss' },
    { name: 'Spain', display_name: 'Spain', value: 'es' },
    { name: 'Sri Lanka', display_name: 'Sri Lanka', value: 'lk' },
    { name: 'St. Vincent & Grenadines', display_name: 'St. Vincent & Grenadines', value: 'vc' },
    { name: 'Sudan', display_name: 'Sudan', value: 'sd' },
    { name: 'Suriname', display_name: 'Suriname', value: 'sr' },
    { name: 'Svalbard and Jan Mayen', display_name: 'Svalbard and Jan Mayen', value: 'sj' },
    { name: 'Swaziland', display_name: 'Swaziland', value: 'sz' },
    { name: 'Sweden', display_name: 'Sweden', value: 'se' },
    { name: 'Switzerland', display_name: 'Switzerland', value: 'ch' },
    { name: 'Syria', display_name: 'Syria', value: 'sy' },
    { name: 'Taiwan', display_name: 'Taiwan', value: 'tw' },
    { name: 'Tajikistan', display_name: 'Tajikistan', value: 'tj' },
    { name: 'Tanzania', display_name: 'Tanzania', value: 'tz' },
    { name: 'Thailand', display_name: 'Thailand', value: 'th' },
    { name: 'Timor-Leste', display_name: 'Timor-Leste', value: 'tl' },
    { name: 'Togo', display_name: 'Togo', value: 'tg' },
    { name: 'Tokelau', display_name: 'Tokelau', value: 'tk' },
    { name: 'Tonga', display_name: 'Tonga', value: 'to' },
    { name: 'Trinidad and Tobago', display_name: 'Trinidad and Tobago', value: 'tt' },
    { name: 'Tunisia', display_name: 'Tunisia', value: 'tn' },
    { name: 'Turkey', display_name: 'Turkey', value: 'tr' },
    { name: 'Turkmenistan', display_name: 'Turkmenistan', value: 'tm' },
    { name: 'Turks and Caicos Islands', display_name: 'Turks and Caicos Islands', value: 'tc' },
    { name: 'Tuvalu', display_name: 'Tuvalu', value: 'tv' },
    { name: 'U.S. Outlying Islands', display_name: 'U.S. Outlying Islands', value: 'um' },
    { name: 'U.S. Virgin Islands', display_name: 'U.S. Virgin Islands', value: 'vi' },
    { name: 'Uganda', display_name: 'Uganda', value: 'ug' },
    { name: 'Ukraine', display_name: 'Ukraine', value: 'ua' },
    { name: 'United Arab Emirates', display_name: 'United Arab Emirates', value: 'ae' },
    { name: 'United Kingdom', display_name: 'United Kingdom', value: 'gb' },
    { name: 'United States', display_name: 'United States', value: 'us' },
    { name: 'Uruguay', display_name: 'Uruguay', value: 'uy' },
    { name: 'Uzbekistan', display_name: 'Uzbekistan', value: 'uz' },
    { name: 'Vanuatu', display_name: 'Vanuatu', value: 'vu' },
    { name: 'Vatican City', display_name: 'Vatican City', value: 'va' },
    { name: 'Venezuela', display_name: 'Venezuela', value: 've' },
    { name: 'Vietnam', display_name: 'Vietnam', value: 'vn' },
    { name: 'Wallis and Futuna', display_name: 'Wallis and Futuna', value: 'wf' },
    { name: 'Western Sahara', display_name: 'Western Sahara', value: 'eh' },
    { name: 'Yemen', display_name: 'Yemen', value: 'ye' },
    { name: 'Zambia', display_name: 'Zambia', value: 'zm' },
    { name: 'Zimbabwe', display_name: 'Zimbabwe', value: 'zw' },
]

export default residence_list
