import React from 'react'
import { CardContent } from '@deriv-com/components'
import {
    DerivProductDerivP2pBrandLightWordmarkHorizontalIcon,
    PaymentMethod10CoinsBrandIcon,
    PaymentMethodAdvcashBrandIcon,
    PaymentMethodAirtmBrandIcon,
    PaymentMethodAstropayBrandIcon,
    PaymentMethodBanxaBrandIcon,
    PaymentMethodBitcoinBrandIcon,
    PaymentMethodBitcoinCashBrandIcon,
    PaymentMethodBnbBrandIcon,
    PaymentMethodCardanoBrandIcon,
    PaymentMethodDogecoinBrandIcon,
    PaymentMethodEpsBrandIcon,
    PaymentMethodEthereumBrandIcon,
    PaymentMethodGiropayBrandIcon,
    PaymentMethodHelp2payBrandIcon,
    PaymentMethodIdealBrandIcon,
    PaymentMethodJetonBrandIcon,
    PaymentMethodLitecoinBrandIcon,
    PaymentMethodMaestroBrandIcon,
    PaymentMethodMastercardBrandIcon,
    PaymentMethodMifinityBrandIcon,
    PaymentMethodMpesaBrandIcon,
    PaymentMethodMtnBrandIcon,
    PaymentMethodNetellerBrandIcon,
    PaymentMethodOxxoBrandIcon,
    PaymentMethodOzowBrandIcon,
    PaymentMethodPagoEfectivoBrandIcon,
    PaymentMethodPayLivreBrandIcon,
    PaymentMethodPaysafecardBrandIcon,
    PaymentMethodPerfectMoneyBrandIcon,
    PaymentMethodPixBrandIcon,
    PaymentMethodPrzelewy24BrandIcon,
    PaymentMethodPseBrandIcon,
    PaymentMethodRapidTransferBrandIcon,
    PaymentMethodSkrill1TapBrandIcon,
    PaymentMethodSkrillBrandIcon,
    PaymentMethodSpeiBrandIcon,
    PaymentMethodSticpayBrandIcon,
    PaymentMethodTronBrandIcon,
    PaymentMethodUsdCoinBrandIcon,
    PaymentMethodVisaBrandIcon,
    PaymentMethodVisaElectronBrandIcon,
    PaymentMethodVodafoneBrandIcon,
    PaymentMethodZingpayBrandIcon,
} from '@deriv/quill-icons'

export const RowPaymentMethods: CardContent[] = [
    {
        id: 1,
        icon: <PaymentMethodMastercardBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 2,
        icon: <PaymentMethodMaestroBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 3,
        icon: <PaymentMethodVisaBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 4,
        icon: <PaymentMethodVisaElectronBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 5,
        icon: <PaymentMethodPixBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 6,
        icon: <PaymentMethodHelp2payBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 7,
        icon: <PaymentMethodZingpayBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 8,
        icon: <PaymentMethodMpesaBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 9,
        icon: <PaymentMethodMtnBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 10,
        icon: <PaymentMethodVodafoneBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 11,
        icon: <PaymentMethodAdvcashBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 12,
        icon: <PaymentMethodAirtmBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 13,
        icon: <PaymentMethodAstropayBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 14,
        icon: <PaymentMethodJetonBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 15,
        icon: <PaymentMethodMifinityBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 16,
        icon: <PaymentMethodNetellerBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 17,
        icon: <PaymentMethodPayLivreBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 18,
        icon: <PaymentMethodPerfectMoneyBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 19,
        icon: <PaymentMethodSkrillBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 20,
        icon: <PaymentMethodSkrill1TapBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 21,
        icon: <PaymentMethodSticpayBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 22,
        icon: <PaymentMethodBitcoinBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 23,
        icon: <PaymentMethodEthereumBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 24,
        icon: <PaymentMethodLitecoinBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },

    {
        id: 25,
        icon: <PaymentMethodUsdCoinBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },

    {
        id: 26,
        icon: <PaymentMethod10CoinsBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 27,
        icon: <PaymentMethodBitcoinCashBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 28,
        icon: <PaymentMethodDogecoinBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 29,
        icon: <PaymentMethodTronBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 30,
        icon: <PaymentMethodCardanoBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 31,
        icon: <PaymentMethodBnbBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 32,
        icon: <PaymentMethodBanxaBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 33,
        icon: <PaymentMethodOxxoBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 34,
        icon: <PaymentMethodPagoEfectivoBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 35,
        icon: <PaymentMethodSpeiBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 36,
        icon: <PaymentMethodPaysafecardBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 37,
        icon: <DerivProductDerivP2pBrandLightWordmarkHorizontalIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 38,
        icon: <PaymentMethodOzowBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 39,
        icon: <PaymentMethodPseBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
]

export const EUPaymentMethods: CardContent[] = [
    {
        id: 1,
        icon: <PaymentMethodMastercardBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 2,
        icon: <PaymentMethodMaestroBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 3,
        icon: <PaymentMethodVisaBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 4,
        icon: <PaymentMethodVisaElectronBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 5,
        icon: <PaymentMethodSkrillBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 6,
        icon: <PaymentMethodNetellerBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 7,
        icon: <PaymentMethodJetonBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 8,
        icon: <PaymentMethodEpsBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 9,
        icon: <PaymentMethodGiropayBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 10,
        icon: <PaymentMethodPrzelewy24BrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 11,
        icon: <PaymentMethodRapidTransferBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        id: 12,
        icon: <PaymentMethodIdealBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
]
