import React from 'react'
import { CardContent } from '@deriv-com/components'
import {
    DerivProductDerivP2pBrandLightWordmarkHorizontalIcon,
    PaymentMethod10CoinsBrandIcon,
    PaymentMethodAdvcashBrandIcon,
    PaymentMethodAirtmBrandIcon,
    PaymentMethodAstropayBrandIcon,
    PaymentMethodBanxaBrandIcon,
    PaymentMethodBitcoinBrandIcon,
    PaymentMethodBitcoinCashBrandIcon,
    PaymentMethodEpsBrandIcon,
    PaymentMethodEthereumBrandIcon,
    PaymentMethodGiropayBrandIcon,
    PaymentMethodHelp2payBrandIcon,
    PaymentMethodIdealBrandIcon,
    PaymentMethodJetonBrandIcon,
    PaymentMethodLitecoinBrandIcon,
    PaymentMethodMaestroBrandIcon,
    PaymentMethodMastercardBrandIcon,
    PaymentMethodMifinityBrandIcon,
    PaymentMethodMpesaBrandIcon,
    PaymentMethodMtnBrandIcon,
    PaymentMethodNetellerBrandIcon,
    PaymentMethodOxxoBrandIcon,
    PaymentMethodOzowBrandIcon,
    PaymentMethodPagoEfectivoBrandIcon,
    PaymentMethodPayLivreBrandIcon,
    PaymentMethodPaysafecardBrandIcon,
    PaymentMethodPerfectMoneyBrandIcon,
    PaymentMethodPixBrandIcon,
    PaymentMethodPrzelewy24BrandIcon,
    PaymentMethodPseBrandIcon,
    PaymentMethodRapidTransferBrandIcon,
    PaymentMethodSkrill1TapBrandIcon,
    PaymentMethodSkrillBrandIcon,
    PaymentMethodSpeiBrandIcon,
    PaymentMethodSticpayBrandIcon,
    PaymentMethodTronBrandIcon,
    PaymentMethodUsdCoinBrandIcon,
    PaymentMethodVisaBrandIcon,
    PaymentMethodVisaElectronBrandIcon,
    PaymentMethodVodafoneBrandIcon,
    PaymentMethodZingpayBrandIcon,
} from '@deriv/quill-icons'

export const RowPaymentMethods: CardContent[] = [
    {
        icon: <PaymentMethodSkrillBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodMastercardBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodMaestroBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodVisaBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodVisaElectronBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodPixBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodHelp2payBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodZingpayBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodMpesaBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodMtnBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodVodafoneBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodAdvcashBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodAirtmBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodAstropayBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodJetonBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodMifinityBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodNetellerBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodPayLivreBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodPerfectMoneyBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodSkrillBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodSkrill1TapBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodSticpayBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodBitcoinBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodEthereumBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodLitecoinBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodUsdCoinBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethod10CoinsBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodBitcoinCashBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodTronBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodBanxaBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodOxxoBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodPagoEfectivoBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodSpeiBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodPaysafecardBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <DerivProductDerivP2pBrandLightWordmarkHorizontalIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodOzowBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodPseBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
]

export const EUPaymentMethods: CardContent[] = [
    {
        icon: <PaymentMethodMastercardBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodMaestroBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodVisaBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodVisaElectronBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodSkrillBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodNetellerBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodJetonBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodEpsBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodGiropayBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodPrzelewy24BrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodRapidTransferBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
    {
        icon: <PaymentMethodIdealBrandIcon height="80px" width="128px" />,
        color: 'gray',
        size: 'xs',
        align: 'center',
    },
]
