import React from 'react'
import {
    INDEX10,
    INDEX25,
    INDEX50,
    INDEX75,
    INDEX100,
    INDEX10S1,
    INDEX100S1,
    INDEX25S1,
    INDEX50S1,
    INDEX75S1,
    RANGEBREAK100,
    RANGEBREAK200,
    STEPINDICES,
    AUDCAD,
    AUDCHF,
    AUDNZD,
    AUDJPY,
    AUDUSD,
    BCHUSD,
    BTCUSD,
    CADCHF,
    CADJPY,
    CLBRENT,
    DAX30,
    DSHUSD,
    EOSUSD,
    EURNZD,
    GBPCAD,
    GBPCHF,
    GBPNZD,
    HFVOL10,
    HFVOL50,
    HFVOL100,
    LTCUSD,
    NZDCAD,
    USDZAR,
    NZDJPY,
    GOLDUSD,
    PALLADIUMUSD,
    PLATINUMUSD,
    SILVERUSD,
    OILUSD,
    EURCAD,
    EURCHF,
    EURGBP,
    EURJPY,
    EURUSD,
    GBPAUD,
    GBPJPY,
    GBPUSD,
    USDCAD,
    USDCHF,
    USDJPY,
    BOOM500,
    BOOM1000,
    CRASH500,
    CRASH1000,
    CHFJPY,
    NZDUSD,
    XRPUSD,
} from 'components/elements/symbols.js'
import { localize } from 'components/localization'

export const optionItemDefault = {
    name: 'default',
    display_name: '',
    key: '14',
    icon: '',
    market: '',
}

export const optionLeverageDefault = {
    name: 'value',
    display_name: '',
    key: '14',
    icon: '',
    market: '',
}

export const leverageItemLists = [
    { name: 1000, display_name: 1000, key: '1', icon: '' },
    { name: 900, display_name: 900, key: '2', icon: '' },
    { name: 800, display_name: 800, key: '3', icon: '' },
    { name: 700, display_name: 700, key: '4', icon: '' },
    { name: 600, display_name: 600, key: '5', icon: '' },
    { name: 500, display_name: 500, key: '6', icon: '' },
    { name: 400, display_name: 400, key: '8', icon: '' },
    { name: 200, display_name: 200, key: '9', icon: '' },
    { name: 100, display_name: 100, key: '10', icon: '' },
    { name: 50, display_name: 50, key: '11', icon: '' },
    { name: 30, display_name: 30, key: '12', icon: '' },
    { name: 5, display_name: 5, key: '13', icon: '' },
]

export const syntheticItemLists = [
    {
        name: 'Boom 1000 Index',
        display_name: localize('Boom 1000 Index'),
        icon: <BOOM1000 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Boom 500 Index',
        display_name: localize('Boom 500 Index'),
        icon: <BOOM500 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Crash 1000 Index',
        display_name: localize('Crash 1000 Index'),
        icon: <CRASH1000 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Crash 500 Index',
        display_name: localize('Crash 500 Index'),
        icon: <CRASH500 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Range Break 100 Index',
        display_name: localize('Range Break 100 Index'),
        icon: <RANGEBREAK100 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Range Break 200 Index',
        display_name: localize('Range Break 200 Index'),
        icon: <RANGEBREAK200 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Step Index',
        display_name: localize('Step Index'),
        icon: <STEPINDICES />,
        market: 'synthetic_indices',
    },
    {
        name: 'HF Volatility 10 Index',
        display_name: localize('HF Volatility 10 Index'),
        icon: <HFVOL10 />,
        market: 'synthetic_indices',
    },
    {
        name: 'HF Volatility 50 Index',
        display_name: localize('HF Volatility 50 Index'),
        icon: <HFVOL50 />,
        market: 'synthetic_indices',
    },
    {
        name: 'HF Volatility 100 Index',
        display_name: localize('HF Volatility 100 Index'),
        icon: <HFVOL100 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Volatility 10 (1s) Index',
        display_name: localize('Volatility 10 (1s) Index'),
        icon: <INDEX10S1 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Volatility 10 Index',
        display_name: localize('Volatility 10 Index'),
        icon: <INDEX10 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Volatility 25 (1s) Index',
        display_name: localize('Volatility 25 (1s) Index'),
        icon: <INDEX25S1 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Volatility 25 Index',
        display_name: localize('Volatility 25 Index'),
        icon: <INDEX25 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Volatility 50 (1s) Index',
        display_name: localize('Volatility 50 (1s) Index'),
        icon: <INDEX50S1 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Volatility 50 Index',
        display_name: localize('Volatility 50 Index'),
        icon: <INDEX50 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Volatility 75 (1s) Index',
        display_name: localize('Volatility 75 (1s) Index'),
        icon: <INDEX75S1 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Volatility 75 Index',
        display_name: localize('Volatility 75 Index'),
        icon: <INDEX75 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Volatility 100 (1s) Index',
        display_name: localize('Volatility 100 (1s) Index'),
        icon: <INDEX100S1 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Volatility 100 Index',
        display_name: localize('Volatility 100 Index'),
        icon: <INDEX100 />,
        market: 'synthetic_indices',
    },
]

export const financialItemLists = [
    {
        name: 'DAX_30',
        display_name: localize('DAX_30'),
        icon: <DAX30 />,
        market: 'other',
    },
    {
        name: 'CL_BRENT',
        display_name: localize('CL_BRENT'),
        icon: <CLBRENT />,
        market: 'other',
    },
    {
        name: 'BCHUSD',
        display_name: localize('BCH/USD'),
        icon: <BCHUSD />,
        market: 'forex',
    },
    {
        name: 'BTCUSD',
        display_name: localize('BTC/USD'),
        icon: <BTCUSD />,
        market: 'forex',
    },
    {
        name: 'DSHUSD',
        display_name: localize('DSH/USD'),
        icon: <DSHUSD />,
        market: 'forex',
    },
    {
        name: 'EOSUSD',
        display_name: localize('EOS/USD'),
        icon: <EOSUSD />,
        market: 'forex',
    },
    {
        name: 'LTCUSD',
        display_name: localize('LTC/USD'),
        icon: <LTCUSD />,
        market: 'forex',
    },
    {
        name: 'XRPUSD',
        display_name: localize('XRP/USD'),
        icon: <XRPUSD />,
        market: 'forex',
    },
    {
        name: 'AUDCAD',
        display_name: localize('AUD/CAD'),
        icon: <AUDCAD />,
        market: 'forex',
    },
    {
        name: 'AUDCHF',
        display_name: localize('AUD/CHF'),
        icon: <AUDCHF />,
        market: 'forex',
    },
    {
        name: 'AUDJPY',
        display_name: localize('AUD/JPY'),
        icon: <AUDJPY />,
        market: 'forex',
    },
    {
        name: 'AUDNZD',
        display_name: localize('AUD/NZD'),
        icon: <AUDNZD />,
        market: 'forex',
    },
    {
        name: 'AUDUSD',
        display_name: localize('AUD/USD'),
        icon: <AUDUSD />,
        market: 'forex',
    },
    {
        name: 'EURCAD',
        display_name: localize('EUR/CAD'),
        icon: <EURCAD />,
        market: 'forex',
    },
    {
        name: 'EURCHF',
        display_name: localize('EUR/CHF'),
        icon: <EURCHF />,
        market: 'forex',
    },
    {
        name: 'EURGBP',
        display_name: localize('EUR/GBP'),
        icon: <EURGBP />,
        market: 'forex',
    },
    {
        name: 'EURJPY',
        display_name: localize('EUR/JPY'),
        icon: <EURJPY />,
        market: 'forex',
    },
    {
        name: 'EURNZD',
        display_name: localize('EUR/NZD'),
        icon: <EURNZD />,
        market: 'forex',
    },
    {
        name: 'EURUSD',
        display_name: localize('EUR/USD'),
        icon: <EURUSD />,
        market: 'forex',
    },
    {
        name: 'GBPCHF',
        display_name: localize('GBP/CHF'),
        icon: <GBPCHF />,
        market: 'forex',
    },
    {
        name: 'GBPJPY',
        display_name: localize('GBP/JPY'),
        icon: <GBPJPY />,
        market: 'forex',
    },
    {
        name: 'GBPUSD',
        display_name: localize('GBP/USD'),
        icon: <GBPUSD />,
        market: 'forex',
    },
    {
        name: 'NZDUSD',
        display_name: localize('NZD/USD'),
        icon: <NZDUSD />,
        market: 'forex',
    },
    {
        name: 'USDCAD',
        display_name: localize('USD/CAD'),
        icon: <USDCAD />,
        market: 'forex',
    },
    {
        name: 'USDCHF',
        display_name: localize('USD/CHF'),
        icon: <USDCHF />,
        market: 'forex',
    },
    {
        name: 'USDJPY',
        display_name: localize('USD/JPY'),
        icon: <USDJPY />,
        market: 'forex',
    },
    {
        name: 'CADCHF',
        display_name: localize('CAD/CHF'),
        icon: <CADCHF />,
        market: 'forex',
    },
    {
        name: 'CADJPY',
        display_name: localize('CAD/JPY'),
        icon: <CADJPY />,
        market: 'forex',
    },
    {
        name: 'GBPAUD',
        display_name: localize('GBP/AUD'),
        icon: <GBPAUD />,
        market: 'forex',
    },
    {
        name: 'GBPCAD',
        display_name: localize('GBP/CAD'),
        icon: <GBPCAD />,
        market: 'forex',
    },
    {
        name: 'GBPNZD',
        display_name: localize('GBP/NZD'),
        icon: <GBPNZD />,
        market: 'forex',
    },
    {
        name: 'NZDCAD',
        display_name: localize('NZD/CAD'),
        icon: <NZDCAD />,
        market: 'forex',
    },
    {
        name: 'NZDJPY',
        display_name: localize('NZD/JPY'),
        icon: <NZDJPY />,
        market: 'forex',
    },
    {
        name: 'USDZAR',
        display_name: localize('USD/ZAR'),
        icon: <USDZAR />,
        market: 'forex',
    },
    {
        name: 'CHFJPY',
        display_name: localize('CHF/JPY'),
        icon: <CHFJPY />,
        market: 'forex',
    },
    {
        name: 'WTI_OIL',
        display_name: localize('Oil/USD'),
        icon: <OILUSD />,
        market: 'commodities',
    },
    {
        name: 'XAUUSD',
        display_name: localize('Gold/USD'),
        icon: <GOLDUSD />,
        market: 'commodities',
    },
    {
        name: 'XAGUSD',
        display_name: localize('Silver/USD'),
        icon: <SILVERUSD />,
        market: 'commodities',
    },
    {
        name: 'XPDUSD',
        display_name: localize('Palladium/USD'),
        icon: <PALLADIUMUSD />,
        market: 'commodities',
    },
    {
        name: 'XPTUSD',
        display_name: localize('Platinum/USD'),
        icon: <PLATINUMUSD />,
        market: 'commodities',
    },
]
