import React from 'react'
import {
    INDEX10,
    INDEX25,
    INDEX50,
    INDEX75,
    INDEX100,
    INDEX10S1,
    INDEX100S1,
    INDEX25S1,
    INDEX50S1,
    INDEX75S1,
    RANGEBREAK100,
    RANGEBREAK200,
    STEPINDICES,
    AUDCAD,
    AUDCHF,
    AUDNZD,
    EURNZD,
    GBPCAD,
    GBPCHF,
    GBPNZD,
    NZDJPY,
    GOLDUSD,
    PALLADIUMUSD,
    PLATINUMUSD,
    SILVERUSD,
    OILUSD,
    AUDJPY,
    AUDUSD,
    EURCAD,
    EURCHF,
    EURJPY,
    EURUSD,
    GBPAUD,
    GBPJPY,
    GBPUSD,
    USDCAD,
    USDCHF,
    USDJPY,
    BOOM500,
    BOOM1000,
    CRASH500,
    CRASH1000,
    CHFJPY,
    NZDUSD,
} from 'components/elements/symbols.js'

export const optionItemDefault = {
    name: 'value',
    displayName: 'Please select a value',
    key: '14',
    icon: '',
    market: '',
}

export const optionLeverageDefault = {
    name: 'value',
    displayName: 'Please select a value',
    key: '14',
    icon: '',
    market: '',
}

export const leverageItemLists = [
    { name: 1000, displayName: 1000, key: '1', icon: '' },
    { name: 900, displayName: 900, key: '2', icon: '' },
    { name: 800, displayName: 800, key: '3', icon: '' },
    { name: 700, displayName: 700, key: '4', icon: '' },
    { name: 600, displayName: 600, key: '5', icon: '' },
    { name: 500, displayName: 500, key: '6', icon: '' },
    { name: 400, displayName: 400, key: '8', icon: '' },
    { name: 200, displayName: 200, key: '9', icon: '' },
    { name: 100, displayName: 100, key: '10', icon: '' },
    { name: 50, displayName: 50, key: '11', icon: '' },
    { name: 30, displayName: 30, key: '12', icon: '' },
    { name: 5, displayName: 5, key: '13', icon: '' },
]

export const syntheticItemLists = [
    {
        name: 'Boom 1000 Index',
        displayName: 'Boom 1000 Index',
        icon: <BOOM1000 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Boom 500 Index',
        displayName: 'Boom 500 Index',
        icon: <BOOM500 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Crash 1000 Index',
        displayName: 'Crash 1000 Index',
        icon: <CRASH1000 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Crash 500 Index',
        displayName: 'Crash 500 Index',
        icon: <CRASH500 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Range Break 100 Index',
        displayName: 'Range Break 100 Index',
        icon: <RANGEBREAK100 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Range Break 200 Index',
        displayName: 'Range Break 200 Index',
        icon: <RANGEBREAK200 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Step Index',
        displayName: 'Step Index',
        icon: <STEPINDICES />,
        market: 'synthetic_indices',
    },
    {
        name: 'HF Volatility 10 Index',
        displayName: 'HF Volatility 10 Index',
        icon: <INDEX10 />,
        market: 'synthetic_indices',
    },
    {
        name: 'HF Volatility 50 Index',
        displayName: 'HF Volatility 50 Index',
        icon: <INDEX50 />,
        market: 'synthetic_indices',
    },
    {
        name: 'HF Volatility 100 Index',
        displayName: 'HF Volatility 100 Index',
        icon: <INDEX100 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Volatility 10 (1s) Index',
        displayName: 'Volatility 10 (1s) Index',
        icon: <INDEX10S1 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Volatility 10 Index',
        displayName: 'Volatility 10 Index',
        icon: <INDEX10 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Volatility 25 (1s) Index',
        displayName: 'Volatility 25 (1s) Index',
        icon: <INDEX25S1 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Volatility 25 Index',
        displayName: 'Volatility 25 Index',
        icon: <INDEX25 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Volatility 50 (1s) Index',
        displayName: 'Volatility 50 (1s) Index',
        icon: <INDEX50S1 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Volatility 50 Index',
        displayName: 'Volatility 50 Index',
        icon: <INDEX50 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Volatility 75 (1s) Index',
        displayName: 'Volatility 75 (1s) Index',
        icon: <INDEX75S1 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Volatility 75 Index',
        displayName: 'Volatility 75 Index',
        icon: <INDEX75 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Volatility 100 (1s) Index',
        displayName: 'Volatility 100 (1s) Index',
        icon: <INDEX100S1 />,
        market: 'synthetic_indices',
    },
    {
        name: 'Volatility 100 Index',
        displayName: 'Volatility 100 Index',
        icon: <INDEX100 />,
        market: 'synthetic_indices',
    },
]

export const financialItemLists = [
    {
        name: 'DAX_30',
        displayName: 'DAX_30',
        icon: '',
        market: 'other',
    },
    {
        name: 'CL_BRENT',
        displayName: 'CL_BRENT',
        icon: '',
        market: 'other',
    },
    {
        name: 'BCHUSD',
        displayName: 'BCH/USD',
        icon: '',
        market: 'forex',
    },
    {
        name: 'BTCUSD',
        displayName: 'BTC/USD',
        icon: '',
        market: 'forex',
    },
    {
        name: 'DSHUSD',
        displayName: 'DSH/USD',
        icon: '',
        market: 'forex',
    },
    {
        name: 'EOSUSD',
        displayName: 'EOS/USD',
        icon: '',
        market: 'forex',
    },
    {
        name: 'LTCUSD',
        displayName: 'LTC/USD',
        icon: '',
        market: 'forex',
    },
    {
        name: 'XPRUSD',
        displayName: 'XPR/USD',
        icon: '',
        market: 'forex',
    },
    {
        name: 'AUDCAD',
        displayName: 'AUD/CAD',
        icon: <AUDCAD />,
        market: 'forex',
    },
    {
        name: 'AUDCHF',
        displayName: 'AUD/CHF',
        icon: <AUDCHF />,
        market: 'forex',
    },
    {
        name: 'AUDJPY',
        displayName: 'AUD/JPY',
        icon: <AUDJPY />,
        market: 'forex',
    },
    {
        name: 'AUDNZD',
        displayName: 'AUD/NZD',
        icon: <AUDNZD />,
        market: 'forex',
    },
    {
        name: 'AUDUSD',
        displayName: 'AUD/USD',
        icon: <AUDUSD />,
        market: 'forex',
    },
    {
        name: 'EURCAD',
        displayName: 'EUR/CAD',
        icon: <EURCAD />,
        market: 'forex',
    },
    {
        name: 'EURCHF',
        displayName: 'EUR/CHF',
        icon: <EURCHF />,
        market: 'forex',
    },
    {
        name: 'EURGBP',
        displayName: 'EUR/GBP',
        icon: '',
        market: 'forex',
    },
    {
        name: 'EURJPY',
        displayName: 'EUR/JPY',
        icon: <EURJPY />,
        market: 'forex',
    },
    {
        name: 'EURNZD',
        displayName: 'EUR/NZD',
        icon: <EURNZD />,
        market: 'forex',
    },
    {
        name: 'EURUSD',
        displayName: 'EUR/USD',
        icon: <EURUSD />,
        market: 'forex',
    },
    {
        name: 'GBPCHF',
        displayName: 'GBP/CHF',
        icon: <GBPCHF />,
        market: 'forex',
    },
    {
        name: 'GBPJPY',
        displayName: 'GBP/JPY',
        icon: <GBPJPY />,
        market: 'forex',
    },
    {
        name: 'GBPUSD',
        displayName: 'GBP/USD',
        icon: <GBPUSD />,
        market: 'forex',
    },
    {
        name: 'NZDUSD',
        displayName: 'NZD/USD',
        icon: <NZDUSD />,
        market: 'forex',
    },
    {
        name: 'USDCAD',
        displayName: 'USD/CAD',
        icon: <USDCAD />,
        market: 'forex',
    },
    {
        name: 'USDCHF',
        displayName: 'USD/CHF',
        icon: <USDCHF />,
        market: 'forex',
    },
    {
        name: 'USDJPY',
        displayName: 'USD/JPY',
        icon: <USDJPY />,
        market: 'forex',
    },
    {
        name: 'CADCHF',
        displayName: 'CAD/CHF',
        icon: '',
        market: 'forex',
    },
    {
        name: 'CADJPY',
        displayName: 'CAD/JPY',
        icon: '',
        market: 'forex',
    },
    {
        name: 'GBPAUD',
        displayName: 'GBP/AUD',
        icon: <GBPAUD />,
        market: 'forex',
    },
    {
        name: 'GBPCAD',
        displayName: 'GBP/CAD',
        icon: <GBPCAD />,
        market: 'forex',
    },
    {
        name: 'GBPNZD',
        displayName: 'GBP/NZD',
        icon: <GBPNZD />,
        market: 'forex',
    },
    {
        name: 'NZDCAD',
        displayName: 'NZD/CAD',
        icon: '',
        market: 'forex',
    },
    {
        name: 'NZDJPY',
        displayName: 'NZD/JPY',
        icon: <NZDJPY />,
        market: 'forex',
    },
    {
        name: 'USDZAR',
        displayName: 'USD/ZAR',
        icon: '',
        market: 'forex',
    },
    {
        name: 'CHFJPY',
        displayName: 'CHF/JPY',
        icon: <CHFJPY />,
        market: 'forex',
    },
    {
        name: 'WTI_OIL',
        displayName: 'Oil/USD',
        icon: <OILUSD />,
        market: 'commodities',
    },
    {
        name: 'XAUUSD',
        displayName: 'Gold/USD',
        icon: <GOLDUSD />,
        market: 'commodities',
    },
    {
        name: 'XAGUSD',
        displayName: 'Silver/USD',
        icon: <SILVERUSD />,
        market: 'commodities',
    },
    {
        name: 'XPDUSD',
        displayName: 'Palladium/USD',
        icon: <PALLADIUMUSD />,
        market: 'commodities',
    },
    {
        name: 'XPTUSD',
        displayName: 'Platinum/USD',
        icon: <PLATINUMUSD />,
        market: 'commodities',
    },
]
