import React from 'react'
import styled from 'styled-components'
import { Article, ArticleProps } from './_article'
import { ArticleWrapper, StyledHeader, ExternalLink } from './_help-centre-style'
import { usePageLoaded } from 'components/hooks/use-page-loaded'
import { Text } from 'components/elements'
import { localize, Localize, WithIntl } from 'components/localization'

const StyledList = styled.ul<{ listStyle: string; paddingLeft: string }>`
    list-style: ${(props) => props.listStyle};
    padding-left: ${(props) => props.paddingLeft};
`

const StyledListItem = styled.li<{ marginTop: string }>`
    color: var(--color-black-3);
    margin-top: ${(props) => props.marginTop};
`

const SignUp = ({ text }: ArticleProps) => (
    <ArticleWrapper>
        <StyledHeader as="h4">{text}</StyledHeader>
        <Text>
            <Localize
                translate_text="Complete <0>this form</0>, and we'll get in touch with you in a couple of days.<br/>You'll need a real Deriv trading account, too. If you don't have one, sign up <1>here</1>."
                components={[
                    <ExternalLink
                        to={'https://login.deriv.com/signup.php?lang=0'}
                        target="_blank"
                        external
                        weight="bold"
                        rel="noopener noreferrer"
                        key={0}
                    />,
                    <ExternalLink
                        to={'/signup/'}
                        external
                        target="_blank"
                        rel="noopener noreferrer"
                        key={1}
                    />,
                ]}
            />
        </Text>
    </ArticleWrapper>
)

const WhyAffiliate = ({ text }: ArticleProps) => (
    <ArticleWrapper>
        <StyledHeader as="h4">{text}</StyledHeader>
        <Text>{localize('When you join our affiliate programme,')}</Text>
        <StyledList listStyle="disc" paddingLeft="5rem">
            <StyledListItem marginTop="0.3rem">
                <Text>
                    {
                        <Localize translate_text="You'll have multiple income opportunities by joining other partnership programmes that we offer." />
                    }
                </Text>
            </StyledListItem>
            <StyledListItem marginTop="0.3rem">
                <Text>
                    {localize(
                        `You'll have access to various marketing tools to help promote our products and services to your clients.`,
                    )}
                </Text>
            </StyledListItem>
            <StyledListItem marginTop="0.3rem">
                <Text>
                    {localize(
                        "You'll be able to take advantage of our multilingual platforms and reach clients wherever they are.",
                    )}
                </Text>
            </StyledListItem>
            <StyledListItem marginTop="0.3rem">
                <Text>
                    {localize(
                        "You'll receive prompt monthly payouts via your preferred payment method.",
                    )}
                </Text>
            </StyledListItem>
            <StyledListItem marginTop="0.3rem">
                <Text>
                    {localize(
                        "You won't be charged any hidden fees. You'll be able to see exactly what your earnings are.",
                    )}
                </Text>
            </StyledListItem>
            <StyledListItem marginTop="0.3rem">
                <Text>{localize("You'll have a dedicated account manager to help you.")}</Text>
            </StyledListItem>
        </StyledList>
    </ArticleWrapper>
)

const CommissionPlans = ({ text }: ArticleProps) => (
    <ArticleWrapper>
        <StyledHeader as="h4">{text}</StyledHeader>
        <Text>{localize('We have 3 commission plans:')}</Text>

        <Text>
            <Localize
                translate_text="<0>Revenue share</0><br/>Earn commission of up to 45% based on the monthly net revenue generated by your clients. The higher their net revenue, the higher your commission payout."
                components={[<strong key={0} />]}
            />
        </Text>
        <Text>
            <Localize
                translate_text="<0>Turnover</0><br/>Earn up to 1.5% commission for each contract bought by your clients. The lower the probability of winning, the higher your commission payout."
                components={[<strong key={0} />]}
            />
        </Text>
        <Text>
            <Localize
                translate_text="<0>Cost per acquisition</0> (For the EU only)"
                components={[<strong key={0} />]}
            />
        </Text>
        <Text>
            <Localize translate_text="Earn 100 USD in commission for each successful referral. Your referred client must open a real account using your tracking link and deposit 100 USD or more (one-time or accumulative)." />
        </Text>
        <Text>
            <Localize
                translate_text="Learn more about our commission plans on <0>our Affiliate and IB Programme page</0>."
                components={[
                    <ExternalLink
                        to={'https://deriv.com/partners/affiliate-ib/'}
                        target="_blank"
                        external
                        weight="bold"
                        rel="noopener noreferrer"
                        key={0}
                    />,
                ]}
            />
        </Text>
    </ArticleWrapper>
)

const WhoCanApply = ({ text }: ArticleProps) => (
    <ArticleWrapper>
        <StyledHeader as="h4">{text}</StyledHeader>
        <Text>{localize('We encourage you to become our affiliate if you are:')}</Text>
        <StyledList listStyle="disc" paddingLeft="5rem">
            <StyledListItem marginTop="1rem">
                <Text>
                    <Localize
                        translate_text="<0>A webmaster</0><br/>Do you have a trading-related website? Join our network of affiliates and turn your traffic into revenue by promoting our products and services."
                        components={[<strong key={0} />]}
                    />
                </Text>
            </StyledListItem>
            <StyledListItem marginTop="1rem">
                <Text>
                    <Localize
                        translate_text="<0>A signal provider</0><br/>Do you provide trading data for others to follow? Grow your community of traders and earn commission when they sign up and trade on our platforms."
                        components={[<strong key={0} />]}
                    />
                </Text>
            </StyledListItem>
            <StyledListItem marginTop="1rem">
                <Text>
                    <Localize
                        translate_text="<0>A trading mentor</0><br/>Do you mentor other traders? Help them become better traders and earn commission when they sign up and trade on our platforms."
                        components={[<strong key={0} />]}
                    />
                </Text>
            </StyledListItem>
            <StyledListItem marginTop="1rem">
                <Text>
                    <Localize
                        translate_text="<0>A software developer</0><br/>Build your own trading platform using our API and earn commission when your clients sign up and trade."
                        components={[<strong key={0} />]}
                    />
                </Text>
            </StyledListItem>
            <StyledListItem marginTop="1rem">
                <Text>
                    <Localize
                        translate_text="<0>A social media admin</0><br/>Promote our products and services on your social media pages, and earn commission when you convert your audience into traders."
                        components={[<strong key={0} />]}
                    />
                </Text>
            </StyledListItem>
            <StyledListItem marginTop="1rem">
                <Text>
                    <Localize
                        translate_text="<0>A blogger/vlogger</0><br/>Promote our products and services and earn commission when you convert your audience into traders."
                        components={[<strong key={0} />]}
                    />
                </Text>
            </StyledListItem>
        </StyledList>
    </ArticleWrapper>
)

const IsItFree = ({ text }: ArticleProps) => (
    <ArticleWrapper>
        <StyledHeader as="h4">{text}</StyledHeader>
        <Text>
            <Localize
                translate_text="Yes, it's completely free of charge <0>to join</0>."
                components={[
                    <ExternalLink
                        to={'https://login.deriv.com/signup.php?lang=0'}
                        target="_blank"
                        external
                        weight="bold"
                        rel="noopener noreferrer"
                        key={0}
                    />,
                ]}
            />
        </Text>
    </ArticleWrapper>
)

const ReferredClient = ({ text }: ArticleProps) => (
    <ArticleWrapper>
        <StyledHeader as="h4">{text}</StyledHeader>
        <Text>
            {localize(
                'A referred client is a client who signed up using your tracking link, made a deposit in their account, and started trading on our platforms. As an affiliate, you stand to earn commission from the trades performed by your referred clients.',
            )}
        </Text>
    </ArticleWrapper>
)

const ForgotPassword = ({ text }: ArticleProps) => (
    <ArticleWrapper>
        <StyledHeader as="h4">{text}</StyledHeader>
        <Text>
            <Localize
                translate_text="You can reset your affiliate password <0>here</0>."
                components={[
                    <ExternalLink
                        to={'https://login.deriv.com/password-reset.php?lang=0'}
                        target="_blank"
                        external
                        weight="bold"
                        rel="noopener noreferrer"
                        key={0}
                    />,
                ]}
            />
        </Text>
    </ArticleWrapper>
)

const ReferralLink = ({ text }: ArticleProps) => (
    <ArticleWrapper>
        <StyledHeader as="h4">{text}</StyledHeader>
        <Text>{localize('Follow these steps to get your referral link:')}</Text>
        <StyledList listStyle="decimal" paddingLeft="5rem">
            <StyledListItem marginTop="1rem">
                <Text>
                    <Localize
                        translate_text="<0>Log in</0> to your affiliate dashboard."
                        components={[
                            <ExternalLink
                                to={'https://login.deriv.com/signin.php?lang=0'}
                                target="_blank"
                                external
                                weight="bold"
                                rel="noopener noreferrer"
                                key={0}
                            />,
                        ]}
                    />
                </Text>
            </StyledListItem>
            <StyledListItem marginTop="1rem">
                <Text>
                    <Localize
                        translate_text="Click the <0>Marketing<0/> tab."
                        components={[<strong key={0} />]}
                    />
                </Text>
            </StyledListItem>
            <StyledListItem marginTop="1rem">
                <Text>
                    <Localize
                        translate_text="Go to the first item in the media gallery and click <0>Get media</0> code."
                        components={[<strong key={0} />]}
                    />
                </Text>
            </StyledListItem>

            <StyledListItem marginTop="1rem">
                <Text>
                    <Localize
                        translate_text="Copy the link in the <0>Landing page URL</0> field. This is the referral link that you can share with your clients."
                        components={[<strong key={0} />]}
                    />
                </Text>
            </StyledListItem>
        </StyledList>
    </ArticleWrapper>
)

const PaymentMethod = ({ text }: ArticleProps) => (
    <ArticleWrapper>
        <StyledHeader as="h4">{text}</StyledHeader>
        <Text>{localize('Follow these steps to change your payment method:')}</Text>
        <StyledList listStyle="decimal" paddingLeft="5rem">
            <StyledListItem marginTop="1rem">
                <Text>
                    <Localize
                        translate_text="<0>Log in</0> to your dashboard."
                        components={[
                            <ExternalLink
                                to={'https://login.deriv.com/signin.php'}
                                target="_blank"
                                external
                                weight="bold"
                                rel="noopener noreferrer"
                                key={0}
                            />,
                        ]}
                    />
                </Text>
            </StyledListItem>
            <StyledListItem marginTop="1rem">
                <Text>
                    <Localize
                        translate_text="Click the <0>Finances</0> tab and select <0>Payment instructions</0>."
                        components={[<strong key={0} />]}
                    />
                </Text>
            </StyledListItem>
            <StyledListItem marginTop="1rem">
                <Text>
                    <Localize
                        translate_text="Select your preferred payment method, enter the necessary details, and click <0>Update</0>."
                        components={[<strong key={0} />]}
                    />
                </Text>
            </StyledListItem>
        </StyledList>
    </ArticleWrapper>
)

const CommissionPayout = ({ text }: ArticleProps) => (
    <ArticleWrapper>
        <StyledHeader as="h4">{text}</StyledHeader>
        <Text>
            <Localize
                translate_text="We'll credit your commission for the previous month into your trading account after the 15th of every month. As an affiliate, you’ll earn commission when your referred clients trade on options and multipliers. To earn from your clients' MT5 trades, you'll need to sign up as an introducing broker. (see <0>How do I sign up as an introducing broker (IB)?</0>)"
                components={[
                    <ExternalLink
                        to={'/help-centre/ib-programme/#ib-sign-up'}
                        target="_blank"
                        external
                        weight="bold"
                        rel="noopener noreferrer"
                        key={0}
                    />,
                    <strong key={0} />,
                ]}
            />
        </Text>
    </ArticleWrapper>
)

const SeeEarnings = ({ text }: ArticleProps) => (
    <ArticleWrapper>
        <StyledHeader as="h4">{text}</StyledHeader>
        <Text>{localize('Follow these steps to see your earnings:')}</Text>
        <StyledList listStyle="decimal" paddingLeft="5rem">
            <StyledListItem marginTop="1rem">
                <Text>
                    <Localize
                        translate_text="<0>Log in</0> to your dashboard."
                        components={[
                            <ExternalLink
                                to={'https://login.deriv.com/signin.php'}
                                target="_blank"
                                external
                                weight="bold"
                                rel="noopener noreferrer"
                                key={0}
                            />,
                        ]}
                    />
                </Text>
            </StyledListItem>
            <StyledListItem marginTop="1rem">
                <Text>
                    <Localize
                        translate_text="Go to <0>Reports</0>, and select <0>Detailed activity report</0>."
                        components={[<strong key={0} />]}
                    />
                </Text>
            </StyledListItem>
            <StyledListItem marginTop="1rem">
                <Text>
                    <Localize
                        translate_text="Set the duration and filters and click <0>Display report</0> or <0>Download report</0>."
                        components={[<strong key={0} />]}
                    />
                </Text>
            </StyledListItem>
        </StyledList>
    </ArticleWrapper>
)

const ReportsAccess = ({ text }: ArticleProps) => (
    <ArticleWrapper>
        <StyledHeader as="h4">{text}</StyledHeader>
        <Text>
            {localize(
                "You'll have access to reports that show your hits, impressions, click-through rates, clients' trading activity, and more.",
            )}
        </Text>
    </ArticleWrapper>
)

const AffiliateProgrammeArticle = () => {
    const [is_mounted] = usePageLoaded(false) // needed to fix tab highlighting not being rerendered during first load

    return (
        <div>
            <Article
                header={localize('Affiliate programme')}
                title={localize(
                    'Help centre | Frequently asked questions | Affiliate programme | Deriv',
                )}
                description={localize('Frequently asked questions - Affiliate programme')}
            >
                <SignUp
                    text={localize('How do I sign up as an affiliate?')}
                    label="affiliate-sign-up"
                    is_mounted={is_mounted}
                />
                <WhyAffiliate
                    text={localize('Why should I join your affiliate programme?')}
                    label="why-affiliate"
                    is_mounted={is_mounted}
                />
                <CommissionPlans
                    text={localize('What type of commission plans do you offer?')}
                    label="commission-plans"
                    is_mounted={is_mounted}
                />
                <WhoCanApply
                    text={localize('Who can apply as an affiliate?')}
                    label="who-can-apply"
                    is_mounted={is_mounted}
                />
                <IsItFree
                    text={localize('Is it free to join your affiliate programme?')}
                    label="is-it-free"
                    is_mounted={is_mounted}
                />
                <ReferredClient
                    text={localize('What is a referred client?')}
                    label="referred-client"
                    is_mounted={is_mounted}
                />
                <ForgotPassword
                    text={localize('I forgot my affiliate password. What should I do?')}
                    label="forgot-password"
                    is_mounted={is_mounted}
                />
                <ReferralLink
                    text={localize('Where can I find my referral link?')}
                    label="referral-link"
                    is_mounted={is_mounted}
                />
                <PaymentMethod
                    text={localize('How do I change my affiliate payment method?')}
                    label="payment-method"
                    is_mounted={is_mounted}
                />
                <CommissionPayout
                    text={localize('How and when will I receive my commission payout?')}
                    label="commission-payout"
                    is_mounted={is_mounted}
                />
                <SeeEarnings
                    text={localize('How do I see my earnings?')}
                    label="see-earnings"
                    is_mounted={is_mounted}
                />
                <ReportsAccess
                    text={localize('What type of reports will I have access to?')}
                    label="reports-access"
                    is_mounted={is_mounted}
                />
            </Article>
        </div>
    )
}

export default WithIntl()(AffiliateProgrammeArticle)
