import React, { ReactElement } from 'react'
import * as icons from 'components/elements/symbols'
import { Localize } from 'components/localization'

export type MarketSymbol = {
    src?: string
    text?: ReactElement
    eu?: boolean
    path?: ReactElement
    raw_spread?: number
    has_icon?: boolean
    markup?: number
    full_spread?: number
    standard_deviation?: number
    minimum_spread?: number
    maximum_spread?: number
    swap_type?: string
    swaps_long?: number
    swaps_short?: number
    three_day?: string
}
export const americas: MarketSymbol[] = [
    {
        src: icons.STOCKSUS500,
        text: <Localize translate_text="US 500" />,
    },
    {
        src: icons.STOCKSUSTECH100,
        text: <Localize translate_text="US Tech 100" />,
    },
    {
        src: icons.STOCKSWALLSTREET30,
        text: <Localize translate_text="Wall Street 30" />,
    },
]

export const asia_oceania: MarketSymbol[] = [
    {
        src: icons.STOCKSAUS200,
        text: <Localize translate_text="Australia 200" />,
    },
    {
        src: icons.STOCKSHONGKONG50,
        text: <Localize translate_text="Hong Kong 50" />,
    },
    {
        src: icons.STOCKSJAPAN225,
        text: <Localize translate_text="Japan 225" />,
    },
]

export const continuous_indices: MarketSymbol[] = [
    {
        src: icons.INDEX10S1NEW,
        text: <Localize translate_text="Volatility 10 (1s) Index" />,
    },
    {
        src: icons.INDEX25S1NEW,
        text: <Localize translate_text="Volatility 25 (1s) Index" />,
    },
    {
        src: icons.INDEX50S1NEW,
        text: <Localize translate_text="Volatility 50 (1s) Index" />,
    },
    {
        src: icons.INDEX75S1NEW,
        text: <Localize translate_text="Volatility 75 (1s) Index" />,
    },
    {
        src: icons.INDEX100S1NEW,
        text: <Localize translate_text="Volatility 100 (1s) Index" />,
    },
    {
        src: icons.INDEX10NEW,
        text: <Localize translate_text="Volatility 10 Index" />,
    },
    {
        src: icons.INDEX25NEW,
        text: <Localize translate_text="Volatility 25 Index" />,
    },
    {
        src: icons.INDEX50NEW,
        text: <Localize translate_text="Volatility 50 Index" />,
    },
    {
        src: icons.INDEX75NEW,
        text: <Localize translate_text="Volatility 75 Index" />,
    },
    {
        src: icons.INDEX100NEW,
        text: <Localize translate_text="Volatility 100 Index" />,
    },
]

// export const volatility_indices: MarketSymbol[] = continuous_indices

export const volatility_indices: MarketSymbol[] = [
    {
        src: icons.INDEX10S1NEW,
        text: <Localize translate_text="Volatility 10 (1s) Index" />,
    },
    {
        src: icons.INDEX25S1NEW,
        text: <Localize translate_text="Volatility 25 (1s) Index" />,
    },
    {
        src: icons.INDEX50S1NEW,
        text: <Localize translate_text="Volatility 50 (1s) Index" />,
    },
    {
        src: icons.INDEX75S1NEW,
        text: <Localize translate_text="Volatility 75 (1s) Index" />,
    },
    {
        src: icons.INDEX100S1NEW,
        text: <Localize translate_text="Volatility 100 (1s) Index" />,
    },
    {
        src: icons.VINDEX2001S,
        text: <Localize translate_text="Volatility 200 (1s) Index" />,
    },
    {
        src: icons.VINDEX3001S,
        text: <Localize translate_text="Volatility 300 (1s) Index" />,
    },
    {
        src: icons.INDEX10NEW,
        text: <Localize translate_text="Volatility 10 Index" />,
    },
    {
        src: icons.INDEX25NEW,
        text: <Localize translate_text="Volatility 25 Index" />,
    },
    {
        src: icons.INDEX50NEW,
        text: <Localize translate_text="Volatility 50 Index" />,
    },
    {
        src: icons.INDEX75NEW,
        text: <Localize translate_text="Volatility 75 Index" />,
    },
    {
        src: icons.INDEX100NEW,
        text: <Localize translate_text="Volatility 100 Index" />,
    },
]

export const volatility_indices_eu: MarketSymbol[] = [
    {
        src: icons.VINDEX2001S,
        text: <Localize translate_text="Volatility 200 (1s) Index" />,
    },
    {
        src: icons.VINDEX3001S,
        text: <Localize translate_text="Volatility 300 (1s) Index" />,
    },
]

export const crash_boom: MarketSymbol[] = [
    {
        src: icons.BOOM1000NEW,
        text: <Localize translate_text="Boom 1000 Index" />,
    },
    {
        src: icons.BOOM500NEW,
        text: <Localize translate_text="Boom 500 Index" />,
    },
    {
        src: icons.VBOOMIC300,
        text: <Localize translate_text="Boom 300 Index " />,
    },
    {
        src: icons.CRASH1000NEW,
        text: <Localize translate_text="Crash 1000 Index" />,
    },
    {
        src: icons.CRASH500NEW,
        text: <Localize translate_text="Crash 500 Index" />,
    },
    {
        src: icons.VCRASHIC300,
        text: <Localize translate_text="Crash 300 Index" />,
    },
]
export const crash_boom_multipliers: MarketSymbol[] = [
    {
        src: icons.BOOM1000NEW,
        text: <Localize translate_text="Boom 1000 Index" />,
    },
    {
        src: icons.BOOM500NEW,
        text: <Localize translate_text="Boom 500 Index" />,
    },
    {
        src: icons.CRASH1000NEW,
        text: <Localize translate_text="Crash 1000 Index" />,
    },
    {
        src: icons.CRASH500NEW,
        text: <Localize translate_text="Crash 500 Index" />,
    },
]

export const crash_boom_eu: MarketSymbol[] = [
    {
        src: icons.VCRASHIC300,
        text: <Localize translate_text="Crash 300 Index" />,
    },
    {
        src: icons.VBOOMIC300,
        text: <Localize translate_text="Boom 300 Index" />,
    },
]

export const daily_reset_indices: MarketSymbol[] = [
    {
        src: icons.MARKETBEARNEW,
        text: <Localize translate_text="Bear Market Index" />,
    },
    {
        src: icons.MARKETBULLNEW,
        text: <Localize translate_text="Bull Market Index" />,
    },
]

export const europe: MarketSymbol[] = [
    {
        src: icons.STOCKSNETHERLANDS25,
        text: <Localize translate_text="Netherlands 25" />,
    },
    {
        src: icons.STOCKSEUROPE50,
        text: <Localize translate_text="Europe 50" />,
    },
    {
        src: icons.STOCKSFRANCE40,
        text: <Localize translate_text="France 40" />,
    },
    {
        src: icons.STOCKSGERMANY40,
        text: <Localize translate_text="Germany 40" />,
    },
    {
        src: icons.STOCKSSWISS20,
        text: <Localize translate_text="Swiss 20" />,
    },
    {
        src: icons.STOCKSUK100,
        text: <Localize translate_text="UK 100" />,
    },
]

export const exotic_pairs: MarketSymbol[] = [
    {
        src: icons.AUDSGD,
        text: <Localize translate_text="AUD/SGD" />,
    },
    {
        src: icons.EURHKD,
        text: <Localize translate_text="EUR/HKD" />,
    },
    {
        src: icons.EURILS,
        text: <Localize translate_text="EUR/ILS" />,
    },
    {
        src: icons.EURMXN,
        text: <Localize translate_text="EUR/MXN" />,
    },
    {
        src: icons.EURSGD,
        text: <Localize translate_text="EUR/SGD" />,
    },
    {
        src: icons.EURZAR,
        text: <Localize translate_text="EUR/ZAR" />,
    },
    // {
    //     src: icons.EURTRY,
    //     text: <Localize translate_text="EUR/TRY" />,
    // },

    {
        src: icons.GBPSGD,
        text: <Localize translate_text="GBP/SGD" />,
    },
    {
        src: icons.HKDJPY,
        text: <Localize translate_text="HKD/JPY" />,
    },
    {
        src: icons.NZDCHF,
        text: <Localize translate_text="NZD/CHF" />,
    },
    // {
    //     src: icons.GBPTRY,
    //     text: <Localize translate_text="GBP/TRY" />,
    // },
    {
        src: icons.NZDSGD,
        text: <Localize translate_text="NZD/SGD" />,
    },
    {
        src: icons.SGDJPY,
        text: <Localize translate_text="SGD/JPY" />,
    },
    {
        src: icons.USDHKD,
        text: <Localize translate_text="USD/HKD" />,
    },
    {
        src: icons.USDILS,
        text: <Localize translate_text="USD/ILS" />,
    },
    {
        src: icons.USDRUB,
        text: <Localize translate_text="USD/RUB" />,
    },
    {
        src: icons.USDSGD,
        text: <Localize translate_text="USD/SGD" />,
    },
    {
        src: icons.USDTHB,
        text: <Localize translate_text="USD/THB" />,
    },
    // {
    //     src: icons.USDTRY,
    //     text: <Localize translate_text="USD/TRY" />,
    // },
]

export const major_pairs: MarketSymbol[] = [
    {
        src: icons.AUDJPY,
        text: <Localize translate_text="AUD/JPY" />,
        path: <Localize translate_text="_t_Forex Major_t_" />,
        raw_spread: 0.007,
        markup: 0.01,
        full_spread: 0.015,
        standard_deviation: 0.012,
        minimum_spread: 0,
        maximum_spread: 0.249,
        swap_type: 'Points',
        swaps_long: 5.665,
        swaps_short: -9.583,
        three_day: 'Wednesday',
    },
    {
        src: icons.AUDUSD,
        text: <Localize translate_text="AUD/USD" />,
        path: <Localize translate_text="_t_Forex Major_t_" />,
        raw_spread: 0.00002,
        markup: 0.00006,
        full_spread: 0.00009,
        standard_deviation: 0.00006,
        minimum_spread: 0,
        maximum_spread: 0.00215,
        swap_type: 'Points',
        swaps_long: -3.267,
        swaps_short: 0.933,
        three_day: 'Wednesday',
    },
    {
        src: icons.EURAUD,
        text: <Localize translate_text="EUR/AUD" />,
        path: <Localize translate_text="_t_Forex Major_t_" />,
        raw_spread: 0.00011,
        markup: 0.0001,
        full_spread: 0.00023,
        standard_deviation: 0.00016,
        minimum_spread: 0,
        maximum_spread: 0.0035,
        swap_type: 'Points',
        swaps_long: -8.433,
        swaps_short: 2.533,
        three_day: 'Wednesday',
    },
    {
        src: icons.EURCAD,
        text: <Localize translate_text="EUR/CAD" />,
        path: <Localize translate_text="_t_Forex Major_t_" />,
        raw_spread: 0.00012,
        markup: 0.0001,
        full_spread: 0.00022,
        standard_deviation: 0.00011,
        minimum_spread: 0.00001,
        maximum_spread: 0.00288,
        swap_type: 'Points',
        swaps_long: -11.63,
        swaps_short: 6.05,
        three_day: 'Wednesday',
    },
    {
        src: icons.EURCHF,
        text: <Localize translate_text="EUR/CHF" />,
        path: <Localize translate_text="_t_Forex Major_t_" />,
        raw_spread: 0.00008,
        markup: 0.0001,
        full_spread: 0.00022,
        standard_deviation: 0.00015,
        minimum_spread: 0,
        maximum_spread: 0.00281,
        swap_type: 'Points',
        swaps_long: 1.9,
        swaps_short: -5.533,
        three_day: 'Wednesday',
    },
    {
        src: icons.EURGBP,
        text: <Localize translate_text="EUR/GBP" />,
        path: <Localize translate_text="_t_Forex Major_t_" />,
        raw_spread: 0.00008,
        markup: 0.00008,
        full_spread: 0.00015,
        standard_deviation: 0.00013,
        minimum_spread: 0,
        maximum_spread: 0.00245,
        swap_type: 'Points',
        swaps_long: -5.2,
        swaps_short: 2.233,
        three_day: 'Wednesday',
    },
    {
        src: icons.EURJPY,
        text: <Localize translate_text="EUR/JPY" />,
        path: <Localize translate_text="_t_Forex Major_t_" />,
        raw_spread: 0.009,
        markup: 0.016,
        full_spread: 0.023,
        standard_deviation: 0.012,
        minimum_spread: 0.001,
        maximum_spread: 0.186,
        swap_type: 'Points',
        swaps_long: 6.57,
        swaps_short: -15.68,
        three_day: 'Wednesday',
    },
    {
        src: icons.EURUSD,
        text: <Localize translate_text="EUR/USD" />,
        path: <Localize translate_text="_t_Forex Major_t_" />,
        raw_spread: 0.00002,
        markup: 0.00006,
        full_spread: 0.00009,
        standard_deviation: 0.00005,
        minimum_spread: 0,
        maximum_spread: 0.00247,
        swap_type: 'Points',
        swaps_long: -9.233,
        swaps_short: 4.867,
        three_day: 'Wednesday',
    },
    {
        src: icons.GBPAUD,
        text: <Localize translate_text="GBP/AUD" />,
        path: <Localize translate_text="_t_Forex Major_t_" />,
        raw_spread: 0.00023,
        markup: 0.00012,
        full_spread: 0.00038,
        standard_deviation: 0.0001,
        minimum_spread: 0,
        maximum_spread: 0.00551,
        swap_type: 'Points',
        swaps_long: -1.7,
        swaps_short: -3.433,
        three_day: 'Wednesday',
    },
    {
        src: icons.GBPJPY,
        text: <Localize translate_text="GBP/JPY" />,
        path: <Localize translate_text="_t_Forex Major_t_" />,
        raw_spread: 0.016,
        markup: 0.008,
        full_spread: 0.02,
        standard_deviation: 0.034,
        minimum_spread: 0.001,
        maximum_spread: 0.609,
        swap_type: 'Points',
        swaps_long: 9.919,
        swaps_short: -18.825,
        three_day: 'Wednesday',
    },
    {
        src: icons.GBPUSD,
        text: <Localize translate_text="GBP/USD" />,
        path: <Localize translate_text="_t_Forex Major_t_" />,
        raw_spread: 0.00014,
        markup: 0.00007,
        full_spread: 0.00015,
        standard_deviation: 0.00025,
        minimum_spread: 0,
        maximum_spread: 0.00248,
        swap_type: 'Points',
        swaps_long: -5.033,
        swaps_short: 1.133,
        three_day: 'Wednesday',
    },
    {
        src: icons.USDCAD,
        text: <Localize translate_text="USD/CAD" />,
        path: <Localize translate_text="_t_Forex Major_t_" />,
        raw_spread: 0.00005,
        markup: 0.00008,
        full_spread: 0.00015,
        standard_deviation: 0.00007,
        minimum_spread: 0,
        maximum_spread: 0.002,
        swap_type: 'Points',
        swaps_long: -1.9,
        swaps_short: -3.35,
        three_day: 'Wednesday',
    },
    {
        src: icons.USDCHF,
        text: <Localize translate_text="USD/CHF" />,
        path: <Localize translate_text="_t_Forex Major_t_" />,
        raw_spread: 0.00007,
        markup: 0.00006,
        full_spread: 0.00009,
        standard_deviation: 0.00017,
        minimum_spread: 0,
        maximum_spread: 0.0018,
        swap_type: 'Points',
        swaps_long: 8.44,
        swaps_short: -12.46,
        three_day: 'Wednesday',
    },
    {
        src: icons.USDJPY,
        text: <Localize translate_text="USD/JPY" />,
        path: <Localize translate_text="_t_Forex Major_t_" />,
        raw_spread: 0.006,
        markup: 0.006,
        full_spread: 0.013,
        standard_deviation: 0.009,
        minimum_spread: 0,
        maximum_spread: 0.17,
        swap_type: 'Points',
        swaps_long: 11.774,
        swaps_short: -18.646,
        three_day: 'Wednesday',
    },
]

export const metals: MarketSymbol[] = [
    {
        src: icons.ALUMINIUMUSD,
        text: <Localize translate_text="Aluminium/USD" />,
    },
    {
        src: icons.COPPERUSD,
        text: <Localize translate_text="Copper/USD" />,
    },
    {
        src: icons.GOLDEUR,
        text: <Localize translate_text="Gold/EUR" />,
    },
    {
        src: icons.GOLDUSD,
        text: <Localize translate_text="Gold/USD" />,
    },
    {
        src: icons.LEADUSD,
        text: <Localize translate_text="Lead/USD" />,
    },
    {
        src: icons.NICKELUSD,
        text: <Localize translate_text="Nickel/USD" />,
    },
    {
        src: icons.PALLADIUMUSD,
        text: <Localize translate_text="Palladium/USD" />,
    },
    {
        src: icons.PLATINUMUSD,
        text: <Localize translate_text="Platinum/USD" />,
    },
    {
        src: icons.SILVEREUR,
        text: <Localize translate_text="Silver/EUR" />,
    },
    {
        src: icons.SILVERUSD,
        text: <Localize translate_text="Silver/USD" />,
    },
    {
        src: icons.ZINCUSD,
        text: <Localize translate_text="Zinc/USD" />,
    },
]
export const metals_options: MarketSymbol[] = [
    {
        src: icons.GOLDUSD,
        text: <Localize translate_text="Gold/USD" />,
    },
    {
        src: icons.PALLADIUMUSD,
        text: <Localize translate_text="Palladium/USD" />,
    },
    {
        src: icons.PLATINUMUSD,
        text: <Localize translate_text="Platinum/USD" />,
    },
    {
        src: icons.SILVERUSD,
        text: <Localize translate_text="Silver/USD" />,
    },
]

export const range_break: MarketSymbol[] = [
    {
        src: icons.RANGEBREAK100New,
        text: <Localize translate_text="Range Break 100 Index" />,
    },
    {
        src: icons.RANGEBREAK200New,
        text: <Localize translate_text="Range Break 200 Index" />,
    },
]

export const micro_pairs: MarketSymbol[] = [
    {
        src: icons.AUDCAD,
        text: <Localize translate_text="AUD/CAD" />,
    },
    {
        src: icons.AUDCHF,
        text: <Localize translate_text="AUD/CHF" />,
    },
    {
        src: icons.AUDJPY,
        text: <Localize translate_text="AUD/JPY" />,
    },
    {
        src: icons.AUDNZD,
        text: <Localize translate_text="AUD/NZD" />,
    },
    {
        src: icons.AUDUSD,
        text: <Localize translate_text="AUD/USD" />,
    },
    {
        src: icons.EURAUD,
        text: <Localize translate_text="EUR/AUD" />,
    },
    {
        src: icons.EURCAD,
        text: <Localize translate_text="EUR/CAD" />,
    },
    {
        src: icons.EURCHF,
        text: <Localize translate_text="EUR/CHF" />,
    },
    {
        src: icons.EURGBP,
        text: <Localize translate_text="EUR/GBP" />,
    },
    {
        src: icons.EURJPY,
        text: <Localize translate_text="EUR/JPY" />,
    },
    {
        src: icons.EURNZD,
        text: <Localize translate_text="EUR/NZD" />,
    },
    {
        src: icons.EURUSD,
        text: <Localize translate_text="EUR/USD" />,
    },
    {
        src: icons.GBPCHF,
        text: <Localize translate_text="GBP/CHF" />,
    },
    {
        src: icons.GBPJPY,
        text: <Localize translate_text="GBP/JPY" />,
    },
    {
        src: icons.GBPUSD,
        text: <Localize translate_text="GBP/USD" />,
    },
    {
        src: icons.NZDUSD,
        text: <Localize translate_text="NZD/USD" />,
    },
    {
        src: icons.USDCAD,
        text: <Localize translate_text="USD/CAD" />,
    },
    {
        src: icons.USDCHF,
        text: <Localize translate_text="USD/CHF" />,
    },
    {
        src: icons.USDJPY,
        text: <Localize translate_text="USD/JPY" />,
    },
]

export const smart_gold_index: MarketSymbol[] = [
    {
        src: icons.GOLDUSD,
        text: <Localize translate_text="Smart Gold Index" />,
    },
]

export const minor_pairs: MarketSymbol[] = [
    {
        src: icons.AUDCAD,
        text: <Localize translate_text="AUD/CAD" />,
        path: <Localize translate_text="_t_Forex Minor_t_" />,
        raw_spread: 0.00009,
        markup: 0.0001,
        full_spread: 0.00019,
        standard_deviation: 0.00018,
        minimum_spread: 0,
        maximum_spread: 0.0025,
        swap_type: 'Points',
        swaps_long: -3.8,
        swaps_short: 0.467,
        three_day: 'Wednesday',
    },
    {
        src: icons.AUDCHF,
        text: <Localize translate_text="AUD/CHF" />,
        path: <Localize translate_text="_t_Forex Minor_t_" />,
        raw_spread: 0.00006,
        markup: 0.00008,
        full_spread: 0.00014,
        standard_deviation: 0.00015,
        minimum_spread: 0,
        maximum_spread: 0.00422,
        swap_type: 'Points',
        swaps_long: -3.8,
        swaps_short: 0.467,
        three_day: 'Wednesday',
    },
    {
        src: icons.AUDNZD,
        text: <Localize translate_text="AUD/NZD" />,
        path: <Localize translate_text="_t_Forex Minor_t_" />,

        raw_spread: 0.00015,
        markup: 0.00015,
        full_spread: 0.00025,
        standard_deviation: 0.00014,
        minimum_spread: 0.00001,
        maximum_spread: 0.00528,
        swap_type: 'Points',
        swaps_long: -3.08,
        swaps_short: -0.93,
        three_day: 'Wednesday',
    },
    {
        src: icons.CADCHF,
        text: <Localize translate_text="CAD/CHF" />,
        path: <Localize translate_text="_t_Forex Minor_t_" />,
        raw_spread: 0.00016,
        markup: 0.00008,
        full_spread: 0.00022,
        standard_deviation: 0.00022,
        minimum_spread: 0.00001,
        maximum_spread: 0.0054,
        swap_type: 'Points',
        swaps_long: 5.73,
        swaps_short: -9.12,
        three_day: 'Wednesday',
    },
    {
        src: icons.CADJPY,
        text: <Localize translate_text="CAD/JPY" />,
        path: <Localize translate_text="_t_Forex Minor_t_" />,
        raw_spread: 0.008,
        markup: 0.01,
        full_spread: 0.017,
        standard_deviation: 0.011,
        minimum_spread: 0,
        maximum_spread: 0.271,
        swap_type: 'Points',
        swaps_long: 9.225,
        swaps_short: -12.83,
        three_day: 'Wednesday',
    },
    {
        src: icons.CHFJPY,
        text: <Localize translate_text="CHF/JPY" />,
        path: <Localize translate_text="_t_Forex Minor_t_" />,
        raw_spread: 0.02,
        markup: 0.01,
        full_spread: 0.021,
        standard_deviation: 0.043,
        minimum_spread: 0,
        maximum_spread: 0.507,
        swap_type: 'Points',
        swaps_long: -1.26,
        swaps_short: -3.541,
        three_day: 'Wednesday',
    },
    {
        src: icons.EURNOK,
        text: <Localize translate_text="EUR/NOK" />,
        path: <Localize translate_text="_t_Forex Minor_t_" />,
        raw_spread: 0.0035,
        markup: 0.001,
        full_spread: 0.0039,
        standard_deviation: 0.00276,
        minimum_spread: 0.00001,
        maximum_spread: 0.11938,
        swap_type: 'Points',
        swaps_long: -45.367,
        swaps_short: 23.233,
        three_day: 'Wednesday',
    },
    {
        src: icons.EURNZD,
        text: <Localize translate_text="EUR/NZD" />,
        path: <Localize translate_text="_t_Forex Minor_t_" />,
        raw_spread: 0.00024,
        markup: 0.0001,
        full_spread: 0.00041,
        standard_deviation: 0.00111,
        minimum_spread: 0,
        maximum_spread: 0.0182,
        swap_type: 'Points',
        swaps_long: -11.606,
        swaps_short: 4.756,
        three_day: 'Wednesday',
    },
    {
        src: icons.EURLPN,
        text: <Localize translate_text="EUR/PLN" />,
        path: <Localize translate_text="_t_Forex Minor_t_" />,
        raw_spread: 0.00176,
        markup: 0.00058,
        full_spread: 0.00337,
        standard_deviation: 0.00295,
        minimum_spread: 0,
        maximum_spread: 0.033,
        swap_type: 'Points',
        swaps_long: -79.767,
        swaps_short: 58.667,
        three_day: 'Wednesday',
    },
    {
        src: icons.EURSEK,
        text: <Localize translate_text="EUR/SEK" />,
        path: <Localize translate_text="_t_Forex Minor_t_" />,
        raw_spread: 0.00432,
        markup: 0.0009,
        full_spread: 0.00533,
        standard_deviation: 0.00009,
        minimum_spread: 0,
        maximum_spread: 0.09022,
        swap_type: 'Points',
        swaps_long: -32.631,
        swaps_short: -23.985,
        three_day: 'Wednesday',
    },
    {
        src: icons.GBPCAD,
        text: <Localize translate_text="GBP/CAD" />,
        path: <Localize translate_text="_t_Forex Minor_t_" />,
        raw_spread: 0.00021,
        markup: 0.00012,
        full_spread: 0.00029,
        standard_deviation: 0.00009,
        minimum_spread: 0,
        maximum_spread: 0.0054,
        swap_type: 'Points',
        swaps_long: -5.933,
        swaps_short: 0.967,
        three_day: 'Wednesday',
    },
    {
        src: icons.GBPCHF,
        text: <Localize translate_text="GBP/CHF" />,
        path: <Localize translate_text="_t_Forex Minor_t_" />,
        raw_spread: 0.00016,
        markup: 0.0001,
        full_spread: 0.00497,
        standard_deviation: 0.00475,
        minimum_spread: 0,
        maximum_spread: 0.00341,
        swap_type: 'Points',
        swaps_long: 5.833,
        swaps_short: -12.333,
        three_day: 'Wednesday',
    },
    {
        src: icons.GBPNOK,
        text: <Localize translate_text="GBP/NOK" />,
        path: <Localize translate_text="_t_Forex Minor_t_" />,
        raw_spread: 0.00595,
        markup: 0.0012,
        full_spread: 0.00034,
        standard_deviation: 0.00054,
        minimum_spread: 0,
        maximum_spread: 0.11707,
        swap_type: 'Points',
        swaps_long: -3.133,
        swaps_short: -27.767,
        three_day: 'Wednesday',
    },
    {
        src: icons.GBPNZD,
        text: <Localize translate_text="GBP/NZD" />,
        path: <Localize translate_text="_t_Forex Minor_t_" />,
        raw_spread: 0.00023,
        markup: 0.00014,
        full_spread: 0.0076,
        standard_deviation: 0.00018,
        minimum_spread: 0,
        maximum_spread: 0.02066,
        swap_type: 'Points',
        swaps_long: -5.598,
        swaps_short: -3.299,
        three_day: 'Wednesday',
    },
    {
        src: icons.GBPSEK,
        text: <Localize translate_text="GBP/SEK" />,
        path: <Localize translate_text="_t_Forex Minor_t_" />,
        raw_spread: 0.00537,
        markup: 0.0012,
        full_spread: 0.00027,
        standard_deviation: 0.017,
        minimum_spread: 0.00001,
        maximum_spread: 0.13602,
        swap_type: 'Points',
        swaps_long: 28.3,
        swaps_short: -69.067,
        three_day: 'Wednesday',
    },
    {
        src: icons.NZDCAD,
        text: <Localize translate_text="NZD/CAD" />,
        path: <Localize translate_text="_t_Forex Minor_t_" />,
        raw_spread: 0.00019,
        markup: 0.0001,
        full_spread: 0.018,
        standard_deviation: 0.00009,
        minimum_spread: 0.00001,
        maximum_spread: 0.0054,
        swap_type: 'Points',
        swaps_long: -2.97,
        swaps_short: -0.71,
        three_day: 'Wednesday',
    },
    {
        src: icons.NZDJPY,
        text: <Localize translate_text="NZD/JPY" />,
        path: <Localize translate_text="_t_Forex Minor_t_" />,
        raw_spread: 0.013,
        markup: 0.009,
        full_spread: 0.00013,
        standard_deviation: 0.00026,
        minimum_spread: 0.001,
        maximum_spread: 0.945,
        swap_type: 'Points',
        swaps_long: 5.757,
        swaps_short: -10.245,
        three_day: 'Wednesday',
    },
    {
        src: icons.NZDUSD,
        text: <Localize translate_text="NZD/USD" />,
        path: <Localize translate_text="_t_Forex Minor_t_" />,
        raw_spread: 0.00006,
        markup: 0.00006,
        full_spread: 0.00126,
        standard_deviation: 0.00552,
        minimum_spread: 0.00001,
        maximum_spread: 0.00659,
        swap_type: 'Points',
        swaps_long: -1.97,
        swaps_short: -0.13,
        three_day: 'Wednesday',
    },
    {
        src: icons.USDMXN,
        text: <Localize translate_text="USD/MXN" />,
        path: <Localize translate_text="_t_Forex Minor_t_" />,
        raw_spread: 0.00047,
        markup: 0.0009,
        full_spread: 0.00013,
        standard_deviation: 0.00342,
        minimum_spread: 0,
        maximum_spread: 0.00543,
        swap_type: 'Points',
        swaps_long: 50.833,
        swaps_short: -76.133,
        three_day: 'Wednesday',
    },
    {
        src: icons.USDCNH,
        text: <Localize translate_text="USD/CNH" />,
        path: <Localize translate_text="_t_Forex Minor_t_" />,
        raw_spread: 0.00288,
        markup: 0.0009,
        full_spread: 0.00013,
        standard_deviation: 0.00342,
        minimum_spread: 0,
        maximum_spread: 0.00543,
        swap_type: 'Points',
        swaps_long: 50.833,
        swaps_short: -76.133,
        three_day: 'Wednesday',
    },
    {
        src: icons.USDNOK,
        text: <Localize translate_text="USD/NOK" />,
        path: <Localize translate_text="_t_Forex Minor_t_" />,
        raw_spread: 0.00343,
        markup: 0.0009,
        full_spread: 0.00353,
        standard_deviation: 0.00269,
        minimum_spread: 0,
        maximum_spread: 0.17739,
        swap_type: 'Points',
        swaps_long: 24.1,
        swaps_short: -44.367,
        three_day: 'Wednesday',
    },
    {
        src: icons.USDPLN,
        text: <Localize translate_text="USD/PLN" />,
        path: <Localize translate_text="_t_Forex Minor_t_" />,
        raw_spread: 0.002,
        markup: 0.00049,
        full_spread: 0.00226,
        standard_deviation: 0.0012,
        minimum_spread: 0.00004,
        maximum_spread: 0.02477,
        swap_type: 'Points',
        swaps_long: -48.029,
        swaps_short: 26.104,
        three_day: 'Wednesday',
    },
    {
        src: icons.USDSEK,
        text: <Localize translate_text="USD/SEK" />,
        path: <Localize translate_text="_t_Forex Minor_t_" />,
        raw_spread: 0.00412,
        markup: 0.00114,
        full_spread: 0.00685,
        standard_deviation: 0.00269,
        minimum_spread: 0.0004,
        maximum_spread: 0.06957,
        swap_type: 'Points',
        swaps_long: 46.09,
        swaps_short: -90.786,
        three_day: 'Wednesday',
    },
    {
        src: icons.USDZAR,
        text: <Localize translate_text="USD/ZAR" />,
        path: <Localize translate_text="_t_Forex Minor_t_" />,
        raw_spread: 0.00632,
        markup: 0.0015,
        full_spread: 0.00699,
        standard_deviation: 0.00805,
        minimum_spread: 0,
        maximum_spread: 0.1376,
        swap_type: 'Points',
        swaps_long: -30,
        swaps_short: -30,
        three_day: 'Monday',
    },
]
export const minor_options_pairs: MarketSymbol[] = [
    {
        src: icons.AUDCAD,
        text: <Localize translate_text="AUD/CAD" />,
    },
    {
        src: icons.AUDCHF,
        text: <Localize translate_text="AUD/CHF" />,
    },
    {
        src: icons.AUDNZD,
        text: <Localize translate_text="AUD/NZD" />,
    },
    {
        src: icons.EURNZD,
        text: <Localize translate_text="EUR/NZD" />,
    },
    {
        src: icons.GBPCAD,
        text: <Localize translate_text="GBP/CAD" />,
    },
    {
        src: icons.GBPCHF,
        text: <Localize translate_text="GBP/CHF" />,
    },
    {
        src: icons.GBPNOK,
        text: <Localize translate_text="GBP/NOK" />,
    },
    {
        src: icons.GBPNZD,
        text: <Localize translate_text="GBP/NZD" />,
    },
    {
        src: icons.NZDJPY,
        text: <Localize translate_text="NZD/JPY" />,
    },
    {
        src: icons.NZDUSD,
        text: <Localize translate_text="NZD/USD" />,
    },
    {
        src: icons.USDMXN,
        text: <Localize translate_text="USD/MXN" />,
    },
    {
        src: icons.USDNOK,
        text: <Localize translate_text="USD/NOK" />,
    },
    {
        src: icons.USDPLN,
        text: <Localize translate_text="USD/PLN" />,
    },
    {
        src: icons.USDSEK,
        text: <Localize translate_text="USD/SEK" />,
    },
]

export const stocks_american_indices: MarketSymbol[] = [
    {
        src: icons.STOCKSUS500,
        text: <Localize translate_text="US 500" />,
    },
    {
        src: icons.STOCKSUSTECH100,
        text: <Localize translate_text="US Tech 100" />,
    },
    {
        src: icons.STOCKSWALLSTREET30,
        text: <Localize translate_text="Wall Street 30" />,
    },
]

export const stocks_asian_indices: MarketSymbol[] = [
    {
        src: icons.STOCKSAUS200,
        text: <Localize translate_text="Australia 200" />,
    },
    {
        src: icons.STOCKSJAPAN225,
        text: <Localize translate_text="Japan 225" />,
    },
]

export const stocks_european_indices: MarketSymbol[] = [
    {
        src: icons.STOCKSEUROPE50,
        text: <Localize translate_text="Euro 50" />,
        eu: true,
    },
    {
        src: icons.STOCKSFRANCE40,
        text: <Localize translate_text="France 40" />,
        eu: true,
    },
    {
        src: icons.STOCKSGERMANY40,
        text: <Localize translate_text="Germany 40" />,
        eu: true,
    },
    {
        src: icons.STOCKSNETHERLANDS25,
        text: <Localize translate_text="Netherlands 25" />,
        eu: false,
    },
    {
        src: icons.STOCKSSPAIN35,
        text: <Localize translate_text="Spain 35" />,
        eu: true,
    },
    {
        src: icons.STOCKSUK100,
        text: <Localize translate_text="UK 100" />,
        eu: true,
    },
]

export const american_stocks: MarketSymbol[] = [
    {
        src: icons.STOCKSADIDASSALOMON,
        text: <Localize translate_text="Adidas Salomon" />,
    },
    {
        src: icons.STOCKSADVANCEDMICRODEVICES,
        text: <Localize translate_text="Advanced Micro Devices Inc" />,
    },
    {
        src: icons.STOCKSAIRBNB,
        text: <Localize translate_text="Airbnb" />,
    },
    {
        src: icons.STOCKSAIRBUSSE,
        text: <Localize translate_text="Airbus SE" />,
    },
    {
        src: icons.STOCKSAIRFRANCE,
        text: <Localize translate_text="Air France KLM SA" />,
    },
    {
        src: icons.STOCKSALIBABAGROUP,
        text: <Localize translate_text="Alibaba Group Holding Ltd" />,
    },
    {
        src: icons.STOCKSALPHABET,
        text: <Localize translate_text="Alphabet Inc Class C" />,
    },
    {
        src: icons.STOCKSAMAZON,
        text: <Localize translate_text="Amazon.com Inc" />,
    },
    {
        src: icons.STOCKSAIRLINESGROUP,
        text: <Localize translate_text="American Airlines Group Inc" />,
    },
    {
        src: icons.STOCKSAMERICANINTERNATIONAL,
        text: <Localize translate_text="American International Group" />,
    },
    {
        src: icons.STOCKSAPPLE,
        text: <Localize translate_text="Apple" />,
    },
    {
        src: icons.STOCKSBANKOFAMERICA,
        text: <Localize translate_text="Bank of America" />,
    },

    {
        src: icons.STOCKSBAYERAG,
        text: <Localize translate_text="Bayer AG" />,
    },
    {
        src: icons.STOCKSBIOGEN,
        text: <Localize translate_text="Biogen Inc" />,
    },

    {
        src: icons.STOCKSBMW,
        text: <Localize translate_text="BMW" />,
    },
    {
        src: icons.STOCKSBOEING,
        text: <Localize translate_text="Boeing" />,
    },
    {
        src: icons.STOCKSCISCO,
        text: <Localize translate_text="Cisco Systems" />,
    },
    {
        src: icons.STOCKSCITIGROUP,
        text: <Localize translate_text="Citigroup" />,
    },
    {
        src: icons.STOCKSCOCACOLA,
        text: <Localize translate_text="Coca-Cola" />,
    },
    {
        src: icons.STOCKSCONTINENTAL,
        text: <Localize translate_text="Continental AG" />,
    },
    {
        src: icons.STOCKSDELTAAIRLINES,
        text: <Localize translate_text="Delta Air Lines" />,
    },
    {
        src: icons.STOCKSDEUTSCHEBANK,
        text: <Localize translate_text="Deutsche Bank AG" />,
    },
    {
        src: icons.STOCKSLUFTHANSA,
        text: <Localize translate_text="Deutsche Lufthansa AG" />,
    },
    {
        src: icons.STOCKSEBAY,
        text: <Localize translate_text="eBay Inc" />,
    },
    {
        src: icons.STOCKSFACEBOOK,
        text: <Localize translate_text="Facebook Inc" />,
    },
    {
        src: icons.STOCKSFEDEX,
        text: <Localize translate_text="Fedex" />,
    },
    {
        src: icons.STOCKSFOX,
        text: <Localize translate_text="Fox Corp Class B" />,
    },
    {
        src: icons.STOCKSGENERALMOTORSCOMP,
        text: <Localize translate_text="General Motors Company" />,
    },
    {
        src: icons.STOCKSGOLDMANSACHS,
        text: <Localize translate_text="Goldman Sachs Group" />,
    },
    {
        src: icons.STOCKSHOME,
        text: <Localize translate_text="Home Depot Inc" />,
    },
    {
        src: icons.STOCKSHPINC,
        text: <Localize translate_text="HP Inc" />,
    },
    {
        src: icons.STOCKSIBM,
        text: <Localize translate_text="IBM" />,
    },
    {
        src: icons.STOCKSINTEL,
        text: <Localize translate_text="Intel" />,
    },
    {
        src: icons.STOCKSJOHNSONJOHNSON,
        text: <Localize translate_text="Johnson & Johnson" />,
    },
    {
        src: icons.STOCKSJPMORGANCHASE,
        text: <Localize translate_text="JP Morgan Chase" />,
    },
    {
        src: icons.STOCKSMASTERCARDINC,
        text: <Localize translate_text="Mastercard Inc" />,
    },
    {
        src: icons.STOCKSMCDONALDS,
        text: <Localize translate_text="McDonalds" />,
    },
    {
        src: icons.STOCKSMICROSOFT,
        text: <Localize translate_text="Microsoft Corporation" />,
    },
    {
        src: icons.STOCKSMODERNA,
        text: <Localize translate_text="Moderna Inc" />,
    },
    {
        src: icons.STOCKSNETFLIX,
        text: <Localize translate_text="Netflix Inc" />,
    },
    {
        src: icons.STOCKSNIKE,
        text: <Localize translate_text="Nike" />,
    },
    {
        src: icons.STOCKSNVIDIA,
        text: <Localize translate_text="NVIDIA Corp" />,
    },
    {
        src: icons.STOCKSPAYPAL,
        text: <Localize translate_text="Paypal" />,
    },
    {
        src: icons.STOCKSPEPSICO,
        text: <Localize translate_text="PepsiCo Inc" />,
    },
    {
        src: icons.STOCKSPFIZER,
        text: <Localize translate_text="Pfizer" />,
    },
    {
        src: icons.STOCKSPORSCHE,
        text: <Localize translate_text="Porsche Automobil Holding SE" />,
    },
    {
        src: icons.STOCKSPROCTERGAMBLE,
        text: <Localize translate_text="Procter & Gamble" />,
    },
    {
        src: icons.STOCKSPUMA,
        text: <Localize translate_text="Puma SE" />,
    },
    {
        src: icons.STOCKSSALESFORCE,
        text: <Localize translate_text="Salesforce.com Inc" />,
    },
    {
        src: icons.STOCKSSONY,
        text: <Localize translate_text="Sony Group Corp" />,
    },
    {
        src: icons.STOCKSTESLA,
        text: <Localize translate_text="Tesla Inc" />,
    },
    {
        src: icons.STOCKSTEVAPHARMACEUTICAL,
        text: <Localize translate_text="Teva Pharmaceutical Inds" />,
    },
    {
        src: icons.STOCKSUBER,
        text: <Localize translate_text="Uber Technologies Inc" />,
    },
    {
        src: icons.STOCKSVISA,
        text: <Localize translate_text="Visa" />,
    },
    {
        src: icons.STOCKSWALMART,
        text: <Localize translate_text="Wal-Mart Stores Inc" />,
    },
    {
        src: icons.STOCKSWALTDISNEY,
        text: <Localize translate_text="Walt Disney Company" />,
    },
    {
        src: icons.STOCKSZOOM,
        text: <Localize translate_text="Zoom Video Communications Inc" />,
    },
]

export const cryptocurrencies_trade_type: MarketSymbol[] = [
    {
        src: icons.BTCUSD,
        text: <Localize translate_text="BTC/USD" />,
    },
    {
        src: icons.ETHUSD,
        text: <Localize translate_text="ETH/USD" />,
    },
]

export const commodities_spreader_energy: MarketSymbol[] = [
    {
        src: icons.CLBRENT,
        text: <Localize translate_text="_t_CL_BREN_t_" />,
        path: <Localize translate_text="_t_Energies_t_" />,
        raw_spread: 0.036,
        markup: 0.03,
        full_spread: 0.064,
        standard_deviation: 0.003,
        minimum_spread: 0.023,
        maximum_spread: 0.166,
        swap_type: 'Points',
        swaps_long: 44.863,
        swaps_short: -65.884,
        three_day: 'Friday',
    },
    {
        src: icons.TWTIOIL,
        text: <Localize translate_text="_t_TWTI_OIL_t_" />,
        path: <Localize translate_text="_t_Energies_t_" />,
        raw_spread: 0.035,
        markup: 0.03,
        full_spread: 0.065,
        standard_deviation: 0.006,
        minimum_spread: 0.023,
        maximum_spread: 0.283,
        swap_type: 'Points',
        swaps_long: 29.597,
        swaps_short: -45.103,
        three_day: 'Friday',
    },
]

export const commodities_spreader_metal: MarketSymbol[] = [
    {
        src: icons.XAGEUR,
        text: <Localize translate_text="XAGEUR" />,
        path: <Localize translate_text="_t_Metals_t_" />,
        raw_spread: 0.005,
        markup: 0.01,
        full_spread: 0.014,
        standard_deviation: 0.002,
        minimum_spread: 0,
        maximum_spread: 0.074,
        swap_type: 'Points',
        swaps_long: -1.24,
        swaps_short: 0.578,
        three_day: 'Wednesday',
    },
    {
        src: icons.XAGUSD,
        text: <Localize translate_text="XAGUSD" />,
        path: <Localize translate_text="_t_Metals_t_" />,
        raw_spread: 0.011,
        markup: 0.008,
        full_spread: 0.022,
        standard_deviation: 0.004,
        minimum_spread: 0,
        maximum_spread: 0.191,
        swap_type: 'Points',
        swaps_long: -3.446,
        swaps_short: 1.547,
        three_day: 'Wednesday',
    },
    {
        src: icons.XALUSD,
        text: <Localize translate_text="XALUSD" />,
        path: <Localize translate_text="_t_Metals_t_" />,
        raw_spread: 4.79,
        markup: 0.15,
        full_spread: 3.85,
        standard_deviation: 1.63,
        minimum_spread: 3.4,
        maximum_spread: 20.85,
        swap_type: 'Points',
        swaps_long: -11.87835,
        swaps_short: -2.28735,
        three_day: 'Wednesday',
    },
    {
        src: icons.XAUEUR,
        text: <Localize translate_text="XAUEUR" />,
        path: <Localize translate_text="_t_Metals_t_" />,
        raw_spread: 0.21,
        markup: 0.12,
        full_spread: 0.37,
        standard_deviation: 0.09,
        minimum_spread: 0,
        maximum_spread: 2,
        swap_type: 'Points',
        swaps_long: -11.728,
        swaps_short: 3.453,
        three_day: 'Wednesday',
    },
    {
        src: icons.XAUUSD,
        text: <Localize translate_text="XAUUSD" />,
        path: <Localize translate_text="_t_Metals_t_" />,
        raw_spread: 0.12,
        markup: 0.1,
        full_spread: 0.17,
        standard_deviation: 0.05,
        minimum_spread: 0.05,
        maximum_spread: 1.24,
        swap_type: 'Points',
        swaps_long: -19.89,
        swaps_short: 11.72,
        three_day: 'Wednesday',
    },
    {
        src: icons.XCUUSD,
        text: <Localize translate_text="XCUUSD" />,
        path: <Localize translate_text="_t_Metals_t_" />,
        raw_spread: 7.34,
        markup: 0.7,
        full_spread: 6.55,
        standard_deviation: 2.34,
        minimum_spread: 4.85,
        maximum_spread: 29.75,
        swap_type: 'Points',
        swaps_long: -1.59,
        swaps_short: 1.82505,
        three_day: 'Wednesday',
    },
    {
        src: icons.XNIUSD,
        text: <Localize translate_text="XNIUSD" />,
        path: <Localize translate_text="_t_Metals_t_" />,
        raw_spread: 81.08,
        markup: 1.1,
        full_spread: 85.04,
        standard_deviation: 50.99,
        minimum_spread: 15.94,
        maximum_spread: 800.94,
        swap_type: 'Points',
        swaps_long: -95.324,
        swaps_short: 42.882,
        three_day: 'Wednesday',
    },
    {
        src: icons.XPBUSD,
        text: <Localize translate_text="XPBUSD" />,
        path: <Localize translate_text="_t_Metals_t_" />,
        raw_spread: 3.94,
        markup: 0.14,
        full_spread: 3.09,
        standard_deviation: 1.37,
        minimum_spread: 2.7,
        maximum_spread: 25.55,
        swap_type: 'Points',
        swaps_long: -0.42435,
        swaps_short: 0.6555,
        three_day: 'Wednesday',
    },
    {
        src: icons.XPDUSD,
        text: <Localize translate_text="XPDUSD" />,
        path: <Localize translate_text="_t_Metals_t_" />,
        raw_spread: 9.3,
        markup: 0.2,
        full_spread: 12.38,
        standard_deviation: 3.56,
        minimum_spread: 0,
        maximum_spread: 84.17,
        swap_type: 'Points',
        swaps_long: -27.979,
        swaps_short: 6.067,
        three_day: 'Wednesday',
    },
    {
        src: icons.XPTUSD,
        text: <Localize translate_text="XPTUSD" />,
        path: <Localize translate_text="_t_Metals_t_" />,
        raw_spread: 2.57,
        markup: 0.12,
        full_spread: 4.94,
        standard_deviation: 0.79,
        minimum_spread: 0,
        maximum_spread: 11.67,
        swap_type: 'Points',
        swaps_long: -16.12,
        swaps_short: 2.365,
        three_day: 'Wednesday',
    },
    {
        src: icons.XZNUSD,
        text: <Localize translate_text="XZNUSD" />,
        path: <Localize translate_text="_t_Metals_t_" />,
        raw_spread: 4.14,
        markup: 0.2,
        full_spread: 4.17,
        standard_deviation: 0.63,
        minimum_spread: 3.02,
        maximum_spread: 22.72,
        swap_type: 'Points',
        swaps_long: 11.288,
        swaps_short: -19.998,
        three_day: 'Wednesday',
    },
]
export const cryptocurrencies_cfds: MarketSymbol[] = [
    {
        src: icons.ADAUSD,
        text: <Localize translate_text="ADA/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.00028,
        markup: 0.00035,
        full_spread: 0.00057,
        standard_deviation: 0.00006,
        minimum_spread: 0.00012,
        maximum_spread: 0.00139,
        swap_type: 'Percentage',
        swaps_long: -15,
        swaps_short: -15,
        three_day: 'Monday',
    },
    {
        src: icons.ALGORAND,
        text: <Localize translate_text="ALG/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.0004,
        markup: 0.0002,
        full_spread: 0.0007,
        standard_deviation: 0.0001,
        minimum_spread: 0.0003,
        maximum_spread: 0.0023,
        swap_type: 'Percentage',
        swaps_long: -15,
        swaps_short: -15,
        three_day: 'Monday',
    },
    {
        src: icons.AVALANCHE,
        text: <Localize translate_text="AVA/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.02,
        markup: 0.02,
        full_spread: 0.04,
        standard_deviation: 0.01,
        minimum_spread: 0.02,
        maximum_spread: 0.15,
        swap_type: 'Percentage',
        swaps_long: -25,
        swaps_short: -25,
        three_day: 'Monday',
    },

    {
        src: icons.BAT,
        text: <Localize translate_text="BAT/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.00025,
        markup: 0.00017,
        full_spread: 0.00039,
        standard_deviation: 0.00006,
        minimum_spread: 0.00012,
        maximum_spread: 0.00182,
        swap_type: 'Percentage',
        swaps_long: -15,
        swaps_short: -15,
        three_day: 'Monday',
    },
    {
        src: icons.BCHNEW,
        text: <Localize translate_text="BCH/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.628,
        markup: 0.091,
        full_spread: 0.733,
        standard_deviation: 0.015,
        minimum_spread: 0.17,
        maximum_spread: 0.983,
        swap_type: 'Percentage',
        swaps_long: -17,
        swaps_short: -17,
        three_day: 'Monday',
    },
    {
        src: icons.BNBUSD,
        text: <Localize translate_text="BNB/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.07,
        markup: 0.237,
        full_spread: 0.265,
        standard_deviation: 0.027,
        minimum_spread: 0.014,
        maximum_spread: 1.901,
        swap_type: 'Percentage',
        swaps_long: -20,
        swaps_short: -20,
        three_day: 'Monday',
    },
    {
        src: icons.BTCETH,
        text: <Localize translate_text="BTC/ETH" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.02893,
        markup: 0.00992,
        full_spread: 0.04023,
        standard_deviation: 0.00055,
        minimum_spread: 0.02797,
        maximum_spread: 0.07934,
        swap_type: 'Percentage',
        swaps_long: -20,
        swaps_short: -20,
        three_day: 'Monday',
    },
    {
        src: icons.BTCLTC,
        text: <Localize translate_text="BTC/LTC" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.59319,
        markup: 0.2,
        full_spread: 0.76292,
        standard_deviation: 0.02563,
        minimum_spread: 0.54446,
        maximum_spread: 1.73755,
        swap_type: 'Percentage',
        swaps_long: -20,
        swaps_short: -20,
        three_day: 'Monday',
    },

    {
        src: icons.BTCUSD,
        text: <Localize translate_text="BTC/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 2.756,
        markup: 16.5,
        full_spread: 18.924,
        standard_deviation: 0.572,
        minimum_spread: 0,
        maximum_spread: 68.324,
        swap_type: 'Percentage',
        swaps_long: -20,
        swaps_short: -20,
        three_day: 'Monday',
    },
    {
        src: icons.DOGUSD,
        text: <Localize translate_text="DOG/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.00008,
        markup: 0.00006,
        full_spread: 0.00009,
        standard_deviation: 0.00002,
        minimum_spread: 0.00003,
        maximum_spread: 0.00108,
        swap_type: 'Percentage',
        swaps_long: -15,
        swaps_short: -15,
        three_day: 'Monday',
    },
    {
        src: icons.DOTUSD,
        text: <Localize translate_text="DOT/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.005,
        markup: 0.006,
        full_spread: 0.01,
        standard_deviation: 0.001,
        minimum_spread: 0.003,
        maximum_spread: 0.032,
        swap_type: 'Percentage',
        swaps_long: -15,
        swaps_short: -15,
        three_day: 'Monday',
    },
    {
        src: icons.DSHUSD1,
        text: <Localize translate_text="DSH/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.035,
        markup: 0.03,
        full_spread: 0.069,
        standard_deviation: 0.018,
        minimum_spread: 0.012,
        maximum_spread: 1.4,
        swap_type: 'Percentage',
        swaps_long: -21,
        swaps_short: -21,
        three_day: 'Monday',
    },
    {
        src: icons.EOSUSD1,
        text: <Localize translate_text="EOS/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.00216,
        markup: 0.00081,
        full_spread: 0.00201,
        standard_deviation: 0.00053,
        minimum_spread: 0.0008,
        maximum_spread: 0.0154,
        swap_type: 'Percentage',
        swaps_long: -24,
        swaps_short: -24,
        three_day: 'Monday',
    },
    {
        src: icons.ETCUSD,
        text: <Localize translate_text="ETC/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.01,
        markup: 0.017,
        full_spread: 0.03,
        standard_deviation: 0.003,
        minimum_spread: 0.003,
        maximum_spread: 0.126,
        swap_type: 'Percentage',
        swaps_long: -15,
        swaps_short: -15,
        three_day: 'Monday',
    },
    {
        src: icons.ETHUSD,
        text: <Localize translate_text="ETH/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.61577,
        markup: 0.82,
        full_spread: 1.4,
        standard_deviation: 0.04932,
        minimum_spread: 0,
        maximum_spread: 4.691,
        swap_type: 'Percentage',
        swaps_long: -15,
        swaps_short: -15,
        three_day: 'Monday',
    },
    {
        src: icons.FILUSD,
        text: <Localize translate_text="FIL/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.02,
        markup: 0.01,
        full_spread: 0.03,
        standard_deviation: 0,
        minimum_spread: 0.02,
        maximum_spread: 0.05,
        swap_type: 'Percentage',
        swaps_long: -15,
        swaps_short: -15,
        three_day: 'Monday',
    },
    {
        src: icons.IOTUSD,
        text: <Localize translate_text="IOT/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.0005,
        markup: 0.0002,
        full_spread: 0.0007,
        standard_deviation: 0.0003,
        minimum_spread: 0.0003,
        maximum_spread: 0.0105,
        swap_type: 'Percentage',
        swaps_long: -15,
        swaps_short: -15,
        three_day: 'Monday',
    },
    {
        src: icons.LNKUSD,
        text: <Localize translate_text="LNK/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.003,
        markup: 0.006,
        full_spread: 0.008,
        standard_deviation: 0.001,
        minimum_spread: 0.001,
        maximum_spread: 0.028,
        swap_type: 'Percentage',
        swaps_long: -15,
        swaps_short: -15,
        three_day: 'Monday',
    },
    {
        src: icons.LTCUSD,
        text: <Localize translate_text="LTC/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.17251,
        markup: 0.0545,
        full_spread: 0.21314,
        standard_deviation: 0.01068,
        minimum_spread: 0.063,
        maximum_spread: 3.22,
        swap_type: 'Percentage',
        swaps_long: -20,
        swaps_short: -20,
        three_day: 'Monday',
    },
    {
        src: icons.MKRUSD,
        text: <Localize translate_text="MKR/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.35,
        markup: 0.57,
        full_spread: 0.96,
        standard_deviation: 0.11,
        minimum_spread: 0.12,
        maximum_spread: 3.34,
        swap_type: 'Percentage',
        swaps_long: -15,
        swaps_short: -15,
        three_day: 'Monday',
    },
    {
        src: icons.MTCUSD,
        text: <Localize translate_text="MTC/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.00029,
        markup: 0.00077,
        full_spread: 0.00107,
        standard_deviation: 0.0001,
        minimum_spread: 0.00012,
        maximum_spread: 0.00593,
        swap_type: 'Percentage',
        swaps_long: -15,
        swaps_short: -15,
        three_day: 'Monday',
    },
    {
        src: icons.NEOUSD,
        text: <Localize translate_text="NEO/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.02,
        markup: 0.01,
        full_spread: 0.04,
        standard_deviation: 0.01,
        minimum_spread: 0.02,
        maximum_spread: 0.13,
        swap_type: 'Percentage',
        swaps_long: -15,
        swaps_short: -15,
        three_day: 'Monday',
    },
    {
        src: icons.OMGUSD,
        text: <Localize translate_text="OMG/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.005,
        markup: 0.002,
        full_spread: 0.007,
        standard_deviation: 0.001,
        minimum_spread: 0.002,
        maximum_spread: 0.014,
        swap_type: 'Percentage',
        swaps_long: -15,
        swaps_short: -15,
        three_day: 'Monday',
    },
    {
        src: icons.SOLUSD,
        text: <Localize translate_text="SOL/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.008,
        markup: 0.012,
        full_spread: 0.017,
        standard_deviation: 0.003,
        minimum_spread: 0.003,
        maximum_spread: 0.269,
        swap_type: 'Percentage',
        swaps_long: -15,
        swaps_short: -15,
        three_day: 'Monday',
    },
    {
        src: icons.TRXUSD,
        text: <Localize translate_text="TRX/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.00011,
        markup: 0.00005,
        full_spread: 0.00013,
        standard_deviation: 0.00003,
        minimum_spread: 0.00003,
        maximum_spread: 0.00095,
        swap_type: 'Percentage',
        swaps_long: -22,
        swaps_short: -22,
        three_day: 'Monday',
    },
    {
        src: icons.UNIUSD,
        text: <Localize translate_text="UNI/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.0042,
        markup: 0.005,
        full_spread: 0.0082,
        standard_deviation: 0.0011,
        minimum_spread: 0.0012,
        maximum_spread: 0.0547,
        swap_type: 'Percentage',
        swaps_long: -15,
        swaps_short: -15,
        three_day: 'Monday',
    },
    {
        src: icons.XLMUSD,
        text: <Localize translate_text="XLM/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.00008,
        markup: 0.00009,
        full_spread: 0.00017,
        standard_deviation: 0.00001,
        minimum_spread: 0.00003,
        maximum_spread: 0.00066,
        swap_type: 'Percentage',
        swaps_long: -10,
        swaps_short: -10,
        three_day: 'Monday',
    },
    {
        src: icons.XMRUSD,
        text: <Localize translate_text="XMR/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.146,
        markup: 0.114,
        full_spread: 0.215,
        standard_deviation: 0.033,
        minimum_spread: 0.012,
        maximum_spread: 0.614,
        swap_type: 'Percentage',
        swaps_long: -15,
        swaps_short: -15,
        three_day: 'Monday',
    },
    {
        src: icons.XRPUSD1,
        text: <Localize translate_text="XRP/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.0004,
        markup: 0.0002,
        full_spread: 0.0005,
        standard_deviation: 0.0001,
        minimum_spread: 0.0001,
        maximum_spread: 0.0117,
        swap_type: 'Percentage',
        swaps_long: -15,
        swaps_short: -15,
        three_day: 'Monday',
    },
    {
        src: icons.XTZUSD,
        text: <Localize translate_text="XTZ/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.00452,
        markup: 0.00085,
        full_spread: 0.00485,
        standard_deviation: 0.00076,
        minimum_spread: 0.00101,
        maximum_spread: 0.012,
        swap_type: 'Percentage',
        swaps_long: -15,
        swaps_short: -15,
        three_day: 'Monday',
    },
    {
        src: icons.ZECUSD,
        text: <Localize translate_text="ZEC/USD" />,
        path: <Localize translate_text="_t_Crypto_t_" />,
        raw_spread: 0.035,
        markup: 0.034,
        full_spread: 0.074,
        standard_deviation: 0.008,
        minimum_spread: 0.012,
        maximum_spread: 0.36,
        swap_type: 'Percentage',
        swaps_long: -15,
        swaps_short: -15,
        three_day: 'Monday',
    },
]
export const cryptocurrencies_multipliers: MarketSymbol[] = [
    {
        src: icons.BTCUSD,
        text: <Localize translate_text="BTC/USD" />,
    },
    {
        src: icons.ETHUSD,
        text: <Localize translate_text="ETH/USD" />,
    },
]
export const jump_indices: MarketSymbol[] = [
    {
        src: icons.JUMP10NEW,
        text: <Localize translate_text="Jump 10 Index" />,
    },
    {
        src: icons.JUMP25NEW,
        text: <Localize translate_text="Jump 25 Index" />,
    },
    {
        src: icons.JUMP50NEW,
        text: <Localize translate_text="Jump 50 Index" />,
    },
    {
        src: icons.JUMP75NEW,
        text: <Localize translate_text="Jump 75 Index" />,
    },
    {
        src: icons.JUMP100NEW,
        text: <Localize translate_text="Jump 100 Index" />,
    },
]

export const energy: MarketSymbol[] = [
    {
        src: icons.POUNDBRENT,
        text: <Localize translate_text="Brent crude oil" />,
    },
    {
        src: icons.USDBRENT,
        text: <Localize translate_text="West Texas Intermediate" />,
    },
]

export const energy_options: MarketSymbol[] = [
    {
        src: icons.USDBRENT,
        text: <Localize translate_text="Oil/USD" />,
    },
]
export const volatility_indices_trade_type_eu: MarketSymbol[] = [
    {
        src: icons.VOLATILITY200EU,
        text: <Localize translate_text="Volatility 200 Index" />,
    },
    {
        src: icons.VOLATILITY300EU,
        text: <Localize translate_text="Volatility 300 Index" />,
    },
]

export const crash_boom_trade_type_eu: MarketSymbol[] = [
    {
        src: icons.CRASH300EU,
        text: <Localize translate_text="Crash 300 Index" />,
        path: <Localize translate_text="_t_Crash Boom Indices_t_" />,
        raw_spread: 0.095,
        markup: 0.115,
        full_spread: 0.214,
        standard_deviation: 0.004,
        minimum_spread: 0.087,
        maximum_spread: 0.105,
        swap_type: 'Percentage',
        swaps_long: -30,
        swaps_short: -30,
        three_day: 'Monday',
    },
    {
        src: icons.BOOM300EU,
        text: <Localize translate_text="Boom 300 Index " />,
        path: <Localize translate_text="_t_Crash Boom Indices_t_" />,
        raw_spread: 0.377,
        markup: 0.085,
        full_spread: 0.433,
        standard_deviation: 0.018,
        minimum_spread: 0.335,
        maximum_spread: 0.413,
        swap_type: 'Percentage',
        swaps_long: -30,
        swaps_short: -30,
        three_day: 'Monday',
    },
]

export const swap_free_pairs: MarketSymbol[] = [
    {
        src: icons.AUDCAD,
        text: <Localize translate_text="AUD/CAD" />,
    },
    {
        src: icons.AUDCHF,
        text: <Localize translate_text="AUD/CHF" />,
    },
    {
        src: icons.AUDJPY,
        text: <Localize translate_text="AUD/JPY" />,
    },
    {
        src: icons.AUDNZD,
        text: <Localize translate_text="AUD/NZD" />,
    },
    {
        src: icons.AUDUSD,
        text: <Localize translate_text="AUD/USD" />,
    },
    {
        src: icons.EURAUD,
        text: <Localize translate_text="EUR/AUD" />,
    },
    {
        src: icons.EURCAD,
        text: <Localize translate_text="EUR/CAD" />,
    },
    {
        src: icons.EURCHF,
        text: <Localize translate_text="EUR/CHF" />,
    },
    {
        src: icons.EURGBP,
        text: <Localize translate_text="EUR/GBP" />,
    },
    {
        src: icons.EURJPY,
        text: <Localize translate_text="EUR/JPY" />,
    },
    {
        src: icons.EURNZD,
        text: <Localize translate_text="EUR/NZD" />,
    },
    {
        src: icons.EURUSD,
        text: <Localize translate_text="EUR/USD" />,
    },
    {
        src: icons.GBPCHF,
        text: <Localize translate_text="GBP/CHF" />,
    },
    {
        src: icons.GBPJPY,
        text: <Localize translate_text="GBP/JPY" />,
    },
    {
        src: icons.GBPUSD,
        text: <Localize translate_text="GBP/USD" />,
    },
    {
        src: icons.NZDUSD,
        text: <Localize translate_text="NZD/USD" />,
    },
    {
        src: icons.USDCAD,
        text: <Localize translate_text="USD/CAD" />,
    },
    {
        src: icons.USDCHF,
        text: <Localize translate_text="USD/CHF" />,
    },
    {
        src: icons.USDJPY,
        text: <Localize translate_text="USD/JPY" />,
    },
]

export const basket_indices_cfds: MarketSymbol[] = [
    {
        src: icons.AUDBASKET,
        text: <Localize translate_text="AUD Basket" />,
    },
    {
        src: icons.EURBASKET,
        text: <Localize translate_text="EUR Basket" />,
    },
    {
        src: icons.GBPBASKET,
        text: <Localize translate_text="GBP Basket" />,
    },
    {
        src: icons.USDBASKET,
        text: <Localize translate_text="USD Basket" />,
    },
]

export const basket_indices_commodities: MarketSymbol[] = [
    {
        src: icons.GOLDBASKET,
        text: <Localize translate_text="Gold Basket" />,
    },
]

export const step_indices = [
    {
        src: icons.STEPINDICES,
        text: <Localize translate_text="Step Index" />,
    },
]
export const stock_spreader_indices = [
    {
        src: icons.AUS200,
        text: <Localize translate_text="AUS_200" />,
        path: <Localize translate_text="_t_Stock Indices_t_" />,
        raw_spread: 3.91,
        markup: 0.35,
        full_spread: 5.05,
        standard_deviation: 1.32,
        minimum_spread: 1.7,
        maximum_spread: 4.7,
        swap_type: 'Points',
        swaps_long: -172.594,
        swaps_short: 0.101,
        three_day: 'Friday',
    },
    {
        src: icons.STOCKSGERMANY40,
        text: <Localize translate_text="DAX_40" />,
        path: <Localize translate_text="_t_Stock Indices_t_" />,
        raw_spread: 0.73,
        markup: 0.7,
        full_spread: 2,
        standard_deviation: 0.17,
        minimum_spread: 0.6,
        maximum_spread: 4.8,
        swap_type: 'Points',
        swaps_long: -336.235,
        swaps_short: -113.901,
        three_day: 'Friday',
    },
    {
        src: icons.ESP35,
        text: <Localize translate_text="ESP_35" />,
        path: <Localize translate_text="_t_Stock Indices_t_" />,
        raw_spread: 5.5,
        markup: 0.4,
        full_spread: 5.9,
        standard_deviation: 0,
        minimum_spread: 5.5,
        maximum_spread: 5.5,
        swap_type: 'Points',
        swaps_long: -193.504,
        swaps_short: -65.921,
        three_day: 'Friday',
    },
    {
        src: icons.EUR50,
        text: <Localize translate_text="EUR_50" />,
        path: <Localize translate_text="_t_Stock Indices_t_" />,
        raw_spread: 1.76,
        markup: 0.18,
        full_spread: 2.98,
        standard_deviation: 0.28,
        minimum_spread: 1.6,
        maximum_spread: 2.8,
        swap_type: 'Points',
        swaps_long: -91.69,
        swaps_short: -31.235,
        three_day: 'Friday',
    },
    {
        src: icons.FRA40,
        text: <Localize translate_text="FRA_40" />,
        path: <Localize translate_text="_t_Stock Indices_t_" />,
        raw_spread: 0.91,
        markup: 0.28,
        full_spread: 1.08,
        standard_deviation: 0.21,
        minimum_spread: 0.8,
        maximum_spread: 1.3,
        swap_type: 'Points',
        swaps_long: -155.333,
        swaps_short: -52.918,
        three_day: 'Friday',
    },
    {
        src: icons.JP225,
        text: <Localize translate_text="JP_225" />,
        path: <Localize translate_text="_t_Stock Indices_t_" />,
        raw_spread: 7.94,
        markup: 1.5,
        full_spread: 9.5,
        standard_deviation: 1.22,
        minimum_spread: 6,
        maximum_spread: 10,
        swap_type: 'Points',
        swaps_long: -441.083,
        swaps_short: -470.435,
        three_day: 'Friday',
    },
    {
        src: icons.UK100,
        text: <Localize translate_text="UK_100" />,
        path: <Localize translate_text="_t_Stock Indices_t_" />,
        raw_spread: 1.1,
        markup: 0.36,
        full_spread: 1.76,
        standard_deviation: 0.95,
        minimum_spread: 0.5,
        maximum_spread: 4.9,
        swap_type: 'Points',
        swaps_long: -214.758,
        swaps_short: -1.97,
        three_day: 'Friday',
    },
    {
        src: icons.US100,
        text: <Localize translate_text="US_100" />,
        path: <Localize translate_text="_t_Stock Indices_t_" />,
        raw_spread: 0.73,
        markup: 0.66,
        full_spread: 1.56,
        standard_deviation: 0.2,
        minimum_spread: 0.5,
        maximum_spread: 0.9,
        swap_type: 'Points',
        swaps_long: -311.999,
        swaps_short: -48.769,
        three_day: 'Friday',
    },
    {
        src: icons.US30,
        text: <Localize translate_text="US_30" />,
        path: <Localize translate_text="_t_Stock Indices_t_" />,
        raw_spread: 1.05,
        markup: 1.5,
        full_spread: 2.7,
        standard_deviation: 0.15,
        minimum_spread: 0.9,
        maximum_spread: 1.2,
        swap_type: 'Points',
        swaps_long: -895.835,
        swaps_short: -142.017,
        three_day: 'Friday',
    },
    {
        src: icons.US500,
        text: <Localize translate_text="US_500" />,
        path: <Localize translate_text="_t_Stock Indices_t_" />,
        raw_spread: 0.36,
        markup: 0.2,
        full_spread: 0.6,
        standard_deviation: 0.05,
        minimum_spread: 0.3,
        maximum_spread: 0.6,
        swap_type: 'Points',
        swaps_long: -96.922,
        swaps_short: 1.263,
        three_day: 'Friday',
    },
]

export const derived_fx: MarketSymbol[] = [
    {
        src: icons.GBPUSD10,
        text: <Localize translate_text="GBP/USD DFX10 Index" />,
    },
    {
        src: icons.EURUSD10,
        text: <Localize translate_text="EUR/USD DFX10 Index" />,
    },
    {
        src: icons.AUDUSD10,
        text: <Localize translate_text="AUD/USD DFX10 Index" />,
    },
    {
        src: icons.USDJPY10,
        text: <Localize translate_text="USD/JPY DFX10 Index" />,
    },
    {
        src: icons.USDCHF10,
        text: <Localize translate_text="USD/CHF DFX10 Index" />,
    },
]
