import React from 'react'
import { StyledCard, StyledCalculatedButton, StyledTrap, StyledText } from './_style'
import { Table, TRAPREVERSE, TC } from './_table'
import { Localize } from 'components/localization'
import { Header, Text } from 'components/elements/typography'
import { Li, Ul } from 'components/elements'
import { TString } from 'types/generics'

type AffiliateType = {
    title: TString
    data: TString[]
}[]

const revenueData: AffiliateType = [
    {
        title: '_t_Net revenue_t_',
        data: ['_t_≤ 20,000 USD per month_t_', '_t_> 20,000 USD per month_t_'],
    },
    {
        title: '_t_Commission_t_',
        data: ['_t_30%_t_', '_t_45%_t_'],
    },
]

const RevenueShare = () => {
    return (
        <StyledCard height="auto" tabletHeight="auto" padding="2.4rem">
            <div>
                <Header as="h4" type="sub-section-title" mb="0.8rem">
                    <Localize translate_text="_t_Revenue share_t_" />
                </Header>
                <Text>
                    <Localize translate_text="_t_Earn based on the monthly net revenue generated by your clients._t_" />
                </Text>
                <Table grid_col_number={2}>
                    {revenueData.map(({ title, data }, index) => (
                        <TC grid_area={'area' + index} key={index}>
                            <StyledTrap isTitle="true">
                                <StyledText weight="bold">
                                    <Localize translate_text={title} />
                                </StyledText>
                            </StyledTrap>
                            {data.map((data, idx) => (
                                <TRAPREVERSE even={idx % 2 ? 'true' : ''} key={idx}>
                                    <StyledText>
                                        <Localize translate_text={data} />
                                    </StyledText>
                                </TRAPREVERSE>
                            ))}
                        </TC>
                    ))}
                </Table>
                <Text mb="0.8rem" mt="2.4rem">
                    <Localize
                        translate_text="_t_<0>Disclaimer:</0>_t_"
                        components={[<strong key={0} />]}
                    />
                </Text>
                <Ul>
                    <Li>
                        <Text>
                            <Localize
                                translate_text="_t_<0>This plan is not available for affiliates who promote to clients residing in the EU.</0>_t_"
                                components={[<strong key={0} />]}
                            />
                        </Text>
                    </Li>
                    <Li>
                        <Text>
                            <Localize
                                translate_text="_t_<0>Affiliates residing in the EU may sign up for the Revenue share plan. However, only clients residing outside of the EU can be referred under this plan.</0>_t_"
                                components={[<strong key={0} />]}
                            />
                        </Text>
                    </Li>
                </Ul>
            </div>
            <div>
                <StyledCalculatedButton secondary>
                    <Localize translate_text="_t_How it’s calculated_t_" />
                </StyledCalculatedButton>
            </div>
        </StyledCard>
    )
}

export default RevenueShare
