name: Crowdin Branch Clean-Up

on:
    push:
        branches:
            - 'master*'

jobs:
    crowdin-branch-delete:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - name: Latest Merged Branch
              uses: actions/checkout@v2
              uses: tonynguyenit18/github-action-custom-vars@v1
              run: echo $RECENT_MERGED_BRANCH_NAME
              id: last_merged_branch
            - name: Checkout 🛎️
              uses: actions/checkout@v2.3.1
            - name: Setup Node
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: '14.x'
            - run: npm i -g @crowdin/cli
            - run: npm ci
            - name: Git Setup
              run: 
                  echo "Setting up Git identity"
                  git config --global user.name "DerivFE"
                  git config --global user.email "80095553+DerivFE@users.noreply.github.com"
            - name: Delete Crowdin Branch 🗑️
              run:  
                  crowdin branch delete -b ${{ steps.last_merged_branch.outputs.branch }} -T ${{ secrets.CROWDIN_API_KEY }}
                    

        

     