name: Core Web Vitals Audit

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  pull-requests: write
  statuses: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  core_web_vitals_audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Core Web Vitals Audit
        run: npm run audit

      - name: Install Datadog CI
        run: npm install -g @datadog/datadog-ci

      - name: Sync results with Datadog
        run: |
          datadog-ci synthetics upload --config datadog-ci.json
          datadog-ci synthetics results --config datadog-ci.json > results.json
        env:
          DATADOG_API_KEY: ${{ secrets.GATSBY_DATADOG_CLIENT_TOKEN }}
          DATADOG_APP_KEY: ${{ secrets.GATSBY_DATADOG_APPLICATION_ID }}
      
      - name: Post audit comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: Core Web Vitals Audit
          message: |
              ### Core Web Vitals Results
              - Largest Contentful Paint: ${{ steps.results.outputs.lcp }}
              - First Input Delay: ${{ steps.results.outputs.fid }}
              - Cumulative Layout Shift: ${{ steps.results.outputs.cls }}
      
      - name: Slack Notification 📣
        uses: 8398a7/action-slack@v3
        if: ${{ failure() }}
        with:
          status: custom
          fields: workflow,job,commit,repo
          custom_payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "plain_text",
                    "emoji": true,
                    "text": "It appears that this pull request has not met the required Core Web Vitals score."
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*User: <${{ github.event.pull_request.user.url }}|${{ github.event.pull_request.user.login }}>*\n*Link:* ${{ github.event.pull_request.html_url }}\n*Title:* ${{ github.event.pull_request.title }}\n*Status:* ${{ github.event.pull_request.state }}"
                  },
                  "accessory": {
                    "type": "image",
                    "image_url": "${{ github.event.pull_request.user.avatar_url }}",
                    "alt_text": "${{ github.event.pull_request.user.login }}"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "image",
                      "image_url": "https://api.slack.com/img/blocks/bkb_template_images/notificationsWarningIcon.png",
                      "alt_text": "notifications warning icon"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*<!subteam^S04RV6RFCTW> please check the PR*"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
