name: Debug

on:
  workflow_run:
    workflows:
      - lint.yml
    types:
      - completed

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Print Error Logs
        uses: actions/github-script@v5
        with:
          script: |
            const runId = context.payload.workflow_run.id;
            const response = await github.actions.getWorkflowRunLogs({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runId
            });
            const logs = await response.text();
            console.log(logs);
