name: Deploy test links
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: Cache dependencies
              uses: actions/cache@v1
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Compile application
              run: |
                  npm ci
                  npm run test
                  npm run build
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  BRANCH: gh-pages # The branch the action should deploy to.
                  FOLDER: public
                  TARGET_FOLDER: ${GITHUB_REF#refs/heads/}
