name: Deploy test links
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Git checkout
              uses: actions/checkout@v1
            - name: Branch name
              run: echo running on branch ${GITHUB_REF}
