name: Translation Push

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
        - 'master*'
        
jobs:
    push-translation:
        runs-on: ubuntu-latest
        if:  startsWith(github.head_ref, 'translation-') && startsWith(github.head_ref, 'stp-')
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2.3.1
            - name: Git Setup
              run: 
                  echo "Setting up Git identity"
                  git config --global user.name "DerivFE"
                  git config --global user.email "80095553+DerivFE@users.noreply.github.com"
            - uses: mshick/add-pr-comment@v1
              with:
                message: |
                  PUSH_STRINGS_TO_CROWDIN
                allow-repeats: true # This is the default

